//! Mathematical constants and float-compatibility constants for every
//! decimal width.
//!
//! # Constants provided
//!
//! The [`DecimalConstants`] trait exposes `pi`, `tau`, `half_pi`,
//! `quarter_pi`, `golden`, and `e` as methods on every width. A single
//! generic impl over `D<Int<N>, SCALE>` serves every width, sourced from
//! the unified per-scale table in [`crate::consts`].
//!
//! Two inherent associated constants, `EPSILON` and `MIN_POSITIVE`, are
//! provided as analogues to `f64::EPSILON` and `f64::MIN_POSITIVE` so
//! that generic code parameterised over numeric types continues to
//! compile when `T` is any of the decimal widths.
//!
//! # Precision strategy
//!
//! Constants are sourced from an oracle-computed per-scale table — no
//! `f64` anywhere. Each entry is
//! `floor(const × 10^SCALE)` (narrowest-fit limbs) plus a `round_up`
//! bit, from which the correct rounding under any [`RoundingMode`] is
//! derived directly — `Trunc`/`Floor` = floor, `Ceiling` = floor+1, and
//! the three half-modes = floor + round_up (the constants are
//! irrational, so the dropped tail is never an exact tie). The selected
//! work-integer value is then checked against the type's storage range.
//! Because the entry is already keyed on the
//! caller's `SCALE` there is no rescale step and no precision loss:
//!
//! **0.5 ULP at every supported scale**, with no exceptions in the
//! precision contract. The only constraint is the width's *storage
//! range*: a value that mathematically exceeds the type's
//! `Storage::MAX / 10^SCALE` cannot be represented at all. At
//! `D38<38>` the storage range is approximately ±1.70141, so the three
//! larger-magnitude constants — `pi ≈ 3.14159`, `tau ≈ 6.28318`,
//! `e ≈ 2.71828` — overflow `i128` and the corresponding methods panic
//! with a clear "constant out of storage range" message;
//! `half_pi ≈ 1.57080`, `quarter_pi ≈ 0.78540`, and `golden ≈ 1.61803`
//! all fit inside ±1.70141 and remain correctly-rounded to 0.5 ULP.
//!
//! [`RoundingMode`]: crate::support::rounding::RoundingMode
//!
//! # Sources
//!
//! The constant table is generated by `scripts/gen_const_table.py`
//! (mpmath oracle): pi/tau/pi-2/pi-4 (ISO 80000-2), e (OEIS A001113),
//! golden ratio (OEIS A001622), plus deg_per_rad (180/pi) and
//! rad_per_deg (pi/180).



pub use crate::types::traits::consts::DecimalConstants;


/// Unwraps a storage-range-checked constant, panicking with the canonical
/// "out of storage range" message when the value does not fit `Int<N>` at the
/// requested `SCALE`. Generic over the storage width — the single
/// [`DecimalConstants`] impl below uses it for every tier.
#[inline]
pub(crate) fn checked_storage<const N: usize>(
    value: Option<crate::int::types::Int<N>>,
    name: &'static str,
    scale: u32,
) -> crate::int::types::Int<N> {
    match value {
        Some(v) => v,
        None => panic!(
            "constant out of storage range: {name} cannot fit storage at SCALE = {scale} \
             (storage range is +/- Int::<N>::MAX / 10^SCALE)"
        ),
    }
}

// ─── The SINGLE DecimalConstants impl for EVERY decimal width ──────────
//
// One generic impl over `D<Int<N>, SCALE>` replaces all the former per-tier
// impls — the narrow `decl_decimal_consts!` macro (D18 = Int<1>, D38 = Int<2>),
// the wide hand impls (D76/D153/D307 = Int<4>/<8>/<16>), and the
// `decl_wide_consts_tier!` macro (D57/D115/D230/D462/D616/D924/D1232) — and the
// System-B `*_RAW_*` / build-time `wide_consts.rs` path they were sourced from.
//
// Every constant is sourced from the unified per-scale table (`crate::consts`)
// at the caller's const `SCALE`, range-CHECKED to the storage `Int<N>`: a value
// past the tier's representable scale (pi/tau/e at a scale whose 10^scale lift
// exceeds `Int<N>`, or deg_per_rad ~57.3 near a tier's top) panics with the
// canonical "out of storage range" message, matching the prior per-tier impls.
// The lookup is keyed on the const `SCALE`, so it folds to the one entry.
//
// We deliberately do NOT use the strong-fold `*_const_n` `const {}` bake here:
// a `const {}` that overflows would be a COMPILE error, whereas an over-scale
// request must be a RUNTIME panic — so the checked runtime accessor is the
// behaviour-preserving choice. The internal kernel path (ln/exp/trig) uses the
// unchecked `*_by_scale` / `*_by_working_scale` into a wide work integer.
impl<const N: usize, const SCALE: u32> DecimalConstants
    for crate::D<crate::int::types::Int<N>, SCALE>
{
    #[inline]
    fn pi() -> Self {
        Self::pi_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn tau() -> Self {
        Self::tau_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn half_pi() -> Self {
        Self::half_pi_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn quarter_pi() -> Self {
        Self::quarter_pi_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn golden() -> Self {
        Self::golden_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn e() -> Self {
        Self::e_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn deg_per_rad() -> Self {
        Self::deg_per_rad_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn rad_per_deg() -> Self {
        Self::rad_per_deg_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }
    #[inline]
    fn log10_2() -> Self {
        Self::log10_2_with(crate::support::rounding::DEFAULT_ROUNDING_MODE)
    }

    #[inline]
    fn pi_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::pi_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "pi",
            SCALE,
        ))
    }
    #[inline]
    fn tau_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::tau_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "tau",
            SCALE,
        ))
    }
    #[inline]
    fn half_pi_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::half_pi_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "half_pi",
            SCALE,
        ))
    }
    #[inline]
    fn quarter_pi_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::quarter_pi_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "quarter_pi",
            SCALE,
        ))
    }
    #[inline]
    fn golden_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::golden_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "golden",
            SCALE,
        ))
    }
    #[inline]
    fn e_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::e_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "e",
            SCALE,
        ))
    }
    #[inline]
    fn deg_per_rad_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::deg_per_rad_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "deg_per_rad",
            SCALE,
        ))
    }
    #[inline]
    fn rad_per_deg_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::rad_per_deg_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "rad_per_deg",
            SCALE,
        ))
    }
    #[inline]
    fn log10_2_with(mode: crate::support::rounding::RoundingMode) -> Self {
        Self(checked_storage::<N>(
            crate::consts::log10_2_by_scale_checked::<crate::int::types::Int<N>>(SCALE, mode),
            "log10_2",
            SCALE,
        ))
    }
}

// EPSILON / MIN_POSITIVE for every width are now emitted by
// `decl_decimal_basics!`. The D38-specific inherent impl that used
// to live here has been removed in favour of the macro-emitted ones
// so D18 / D38 / D57 / D76 / D115 / D153 / D230 / D307 / D462 /
// D616 / D924 / D1232 all share the same EPSILON / MIN_POSITIVE
// surface.

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::widths::D38s12;

    // Bit-exact assertions at SCALE = 12.
    //
    // At SCALE = 12 each constant is the 37-digit raw integer divided by
    // 10^23, rounded half-to-even.

    /// pi at SCALE=12: raw / 10^23.
    /// Truncated 13 digits: 3_141_592_653_589.
    /// 14th digit is 7 (from position 14 of the raw) -> round up.
    /// Expected: 3_141_592_653_590.
    #[test]
    fn pi_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::pi().to_bits().as_i128(), 3_141_592_653_590_i128);
    }

    /// tau at SCALE=12: raw / 10^23.
    /// Truncated 13 digits: 6_283_185_307_179.
    /// 14th digit is 5 -> round up. Expected: 6_283_185_307_180.
    #[test]
    fn tau_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::tau().to_bits().as_i128(), 6_283_185_307_180_i128);
    }

    /// half_pi at SCALE=12: raw / 10^23.
    /// Truncated 13 digits: 1_570_796_326_794.
    /// 14th digit is 8 -> round up. Expected: 1_570_796_326_795.
    #[test]
    fn half_pi_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::half_pi().to_bits().as_i128(), 1_570_796_326_795_i128);
    }

    /// quarter_pi at SCALE=12: raw / 10^23.
    /// Truncated 12 digits: 785_398_163_397.
    /// 13th digit is 4 -> no round-up. Expected: 785_398_163_397.
    #[test]
    fn quarter_pi_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::quarter_pi().to_bits().as_i128(), 785_398_163_397_i128);
    }

    /// e at SCALE=12: raw / 10^23.
    /// Truncated 13 digits: 2_718_281_828_459.
    /// 14th digit is 0 -> no round-up. Expected: 2_718_281_828_459.
    #[test]
    fn e_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::e().to_bits().as_i128(), 2_718_281_828_459_i128);
    }

    /// golden at SCALE=12: raw / 10^23.
    /// Truncated 13 digits: 1_618_033_988_749.
    /// 14th digit is 8 -> round up. Expected: 1_618_033_988_750.
    #[test]
    fn golden_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(D38s12::golden().to_bits().as_i128(), 1_618_033_988_750_i128);
    }

    /// deg_per_rad (180/pi ≈ 57.29577951308232...) at SCALE=12.
    /// raw floor at scale 12 = 57_295_779_513_082, dropped tail < 1/2
    /// (round_up = 0), so half-to-even keeps the floor.
    #[test]
    fn deg_per_rad_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(
            D38s12::deg_per_rad().to_bits().as_i128(),
            57_295_779_513_082_i128
        );
    }

    /// rad_per_deg (pi/180 ≈ 0.017453292519943295...) at SCALE=12.
    /// raw floor at scale 12 = 17_453_292_519, dropped tail >= 1/2
    /// (round_up = 1), so half-to-even rounds up to 17_453_292_520.
    #[test]
    fn rad_per_deg_is_bit_exact_at_scale_12() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        assert_eq!(
            D38s12::rad_per_deg().to_bits().as_i128(),
            17_453_292_520_i128
        );
    }

    /// Directed-mode siblings: `deg_per_rad_with(Ceiling)` bumps the
    /// floor (the tail is non-zero for an irrational), and
    /// `rad_per_deg_with(Floor)` keeps the floor. Independent of the
    /// crate-default mode, so no half-to-even guard.
    #[test]
    fn deg_rad_directed_modes_at_scale_12() {
        use crate::support::rounding::RoundingMode::{Ceiling, Floor};
        assert_eq!(
            D38s12::deg_per_rad_with(Ceiling).to_bits().as_i128(),
            57_295_779_513_083_i128
        );
        assert_eq!(
            D38s12::rad_per_deg_with(Floor).to_bits().as_i128(),
            17_453_292_519_i128
        );
    }

    // Closeness checks against core::f64::consts.
    // These verify that the correct reference digits were selected; the
    // bit-exact tests above are the primary acceptance criteria.

    /// pi() converted to f64 is within 1e-11 of `core::f64::consts::PI`.
    /// At SCALE=12, 1 LSB = 1e-12, so 1e-11 covers rescale rounding plus
    /// the f64 conversion step.
    #[test]
    fn pi_close_to_f64_pi() {
        let diff = (D38s12::pi().to_f64() - core::f64::consts::PI).abs();
        assert!(diff < 1e-11, "pi diverges from f64 PI by {diff}");
    }

    #[test]
    fn tau_close_to_f64_tau() {
        let diff = (D38s12::tau().to_f64() - core::f64::consts::TAU).abs();
        assert!(diff < 1e-11, "tau diverges from f64 TAU by {diff}");
    }

    #[test]
    fn half_pi_close_to_f64_frac_pi_2() {
        let diff = (D38s12::half_pi().to_f64() - core::f64::consts::FRAC_PI_2).abs();
        assert!(
            diff < 1e-11,
            "half_pi diverges from f64 FRAC_PI_2 by {diff}"
        );
    }

    #[test]
    fn quarter_pi_close_to_f64_frac_pi_4() {
        let diff = (D38s12::quarter_pi().to_f64() - core::f64::consts::FRAC_PI_4).abs();
        assert!(
            diff < 1e-11,
            "quarter_pi diverges from f64 FRAC_PI_4 by {diff}"
        );
    }

    #[test]
    fn e_close_to_f64_e() {
        let diff = (D38s12::e().to_f64() - core::f64::consts::E).abs();
        assert!(diff < 1e-11, "e diverges from f64 E by {diff}");
    }

    /// golden() converted to f64 is within 1e-11 of the closed form
    /// `(1 + sqrt(5)) / 2`. Requires std for `f64::sqrt`.
    #[cfg(feature = "std")]
    #[test]
    fn golden_close_to_closed_form() {
        let expected = (1.0_f64 + 5.0_f64.sqrt()) / 2.0;
        let diff = (D38s12::golden().to_f64() - expected).abs();
        assert!(diff < 1e-11, "golden diverges from closed-form by {diff}");
    }

    // EPSILON / MIN_POSITIVE

    #[test]
    fn epsilon_is_one_ulp() {
        assert_eq!(D38s12::EPSILON.to_bits().as_i128(), 1_i128);
        assert!(D38s12::EPSILON > D38s12::ZERO);
    }

    #[test]
    fn min_positive_is_one_ulp() {
        assert_eq!(D38s12::MIN_POSITIVE.to_bits().as_i128(), 1_i128);
        assert_eq!(D38s12::MIN_POSITIVE, D38s12::EPSILON);
    }

    /// At SCALE = 6 the LSB is 10^-6; EPSILON is still raw 1.
    #[test]
    fn epsilon_at_scale_6_is_one_ulp() {
        type D6 = crate::D<crate::int::types::Int<2>, 6>;
        assert_eq!(D6::EPSILON.to_bits().as_i128(), 1_i128);
        assert_eq!(D6::MIN_POSITIVE.to_bits().as_i128(), 1_i128);
    }

    // Cross-scale exercises

    /// At SCALE = 6, pi() should equal 3.141593 (rounded half-to-even from
    /// 3.1415926535...). Expected raw bits: 3_141_593.
    #[test]
    fn pi_at_scale_6_is_bit_exact() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        type D6 = crate::D<crate::int::types::Int<2>, 6>;
        assert_eq!(D6::pi().to_bits().as_i128(), 3_141_593_i128);
    }

    /// At SCALE = 0, pi() rounds to 3 (first fractional digit is 1, no
    /// round-up).
    #[test]
    fn pi_at_scale_0_is_three() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        type D0 = crate::D<crate::int::types::Int<2>, 0>;
        assert_eq!(D0::pi().to_bits().as_i128(), 3_i128);
    }

    /// `D38<37>::pi()` is the canonical pi rounded half-to-even to 37
    /// fractional digits. The 75-digit Int<4> reference is rescaled
    /// down to 37 digits; the result is bit-identical to the
    /// hand-tabulated constant.
    #[test]
    fn pi_at_scale_37_matches_canonical_37_digit_rounding() {
        type D37 = crate::D<crate::int::types::Int<2>, 37>;
        // pi to 38 digits: 3.14159265358979323846264338327950288420
        //                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        //                   keep 37 frac digits; the 38th digit is 0
        //                   so half-to-even rounds down — no bump.
        let expected: i128 = 31_415_926_535_897_932_384_626_433_832_795_028_842;
        assert_eq!(D37::pi().to_bits().as_i128(), expected);
    }

    // `D38<38>` storage range is approximately ±1.70141 (i128::MAX /
    // 10^38). The three constants whose magnitude exceeds that bound
    // must panic with a clear "out of storage range" message:
    //
    // - pi    ≈ 3.14159    > 1.70141 → must panic
    // - tau   ≈ 6.28318    > 1.70141 → must panic
    // - e     ≈ 2.71828    > 1.70141 → must panic
    //
    // The three that DO fit must be correctly rounded to 0.5 ULP:
    //
    // - half_pi    ≈ 1.57079   < 1.70141 → must round to 0.5 ULP
    // - quarter_pi ≈ 0.78540   < 1.70141 → must round to 0.5 ULP
    // - golden     ≈ 1.61803   < 1.70141 → must round to 0.5 ULP

    #[test]
    #[should_panic(expected = "out of storage range")]
    fn pi_at_scale_38_panics_storage_range() {
        let _ = crate::D::<crate::int::types::Int<2>, 38>::pi();
    }

    #[test]
    #[should_panic(expected = "out of storage range")]
    fn tau_at_scale_38_panics_storage_range() {
        let _ = crate::D::<crate::int::types::Int<2>, 38>::tau();
    }

    #[test]
    #[should_panic(expected = "out of storage range")]
    fn e_at_scale_38_panics_storage_range() {
        let _ = crate::D::<crate::int::types::Int<2>, 38>::e();
    }

    /// `half_pi` / `quarter_pi` / `golden` at `D38<38>` must not panic
    /// (their magnitudes are inside the type's ±1.7 storage range) and
    /// each must be correctly rounded to 0.5 ULP (= 1 LSB).
    #[test]
    fn fitting_constants_at_scale_38_are_correctly_rounded() {
        // half_pi to 38 digits: 1.57079632679489661923132169163975144210
        let expected_half_pi: i128 = 157_079_632_679_489_661_923_132_169_163_975_144_210;
        let got = crate::D::<crate::int::types::Int<2>, 38>::half_pi().to_bits().as_i128();
        let diff = (got - expected_half_pi).abs();
        assert!(
            diff <= 1,
            "half_pi: got {got}, expected {expected_half_pi}, diff {diff} > 1 LSB"
        );

        // quarter_pi to 38 digits: 0.78539816339744830961566084581987572105
        let expected_quarter_pi: i128 = 78_539_816_339_744_830_961_566_084_581_987_572_105;
        let got = crate::D::<crate::int::types::Int<2>, 38>::quarter_pi().to_bits().as_i128();
        let diff = (got - expected_quarter_pi).abs();
        assert!(
            diff <= 1,
            "quarter_pi: got {got}, expected {expected_quarter_pi}, diff {diff} > 1 LSB"
        );

        // golden to 38 digits: 1.61803398874989484820458683436563811772
        let expected_golden: i128 = 161_803_398_874_989_484_820_458_683_436_563_811_772;
        let got = crate::D::<crate::int::types::Int<2>, 38>::golden().to_bits().as_i128();
        let diff = (got - expected_golden).abs();
        assert!(
            diff <= 1,
            "golden: got {got}, expected {expected_golden}, diff {diff} > 1 LSB"
        );
    }

    /// Negative-side rounding: negating pi gives the expected raw bits.
    #[test]
    fn neg_pi_round_trip() {
        if !crate::support::rounding::DEFAULT_IS_HALF_TO_EVEN {
            return;
        }
        let pi = D38s12::pi();
        let neg_pi = -pi;
        assert_eq!(neg_pi.to_bits().as_i128(), -3_141_592_653_590_i128);
    }

    // (`rescale_from_ref` boundary tests removed: the rounding logic now
    // lives in `D38::rescale` / `src/rounding.rs::apply_rounding` and is
    // covered by the tests in those modules.)
}
