//! Historical decimal-scaled releases as golden subjects.
//!
//! One erased subject per pinned release (the same `Value = String` shape as the
//! live `DsSubject` in decimal-scale-test), generated by [`historical_subject!`] so
//! each version module carries exactly its own API era: its crate, its cell list,
//! and its honest overflow contract. The version-history gates (`tests/history.rs`)
//! run these beside the live subject over the same golden set — a historical
//! version FAILING cells is the expected, reported outcome, never adapted away.
//!
//! Era notes (verified against the published sources):
//!
//! - **0.4.4** shares the live tier table (`D18`..`D1232`, `MAX_SCALE = name - 1`)
//!   and the live trait surface (`DecimalArithmetic` / `DecimalTranscendental`,
//!   the `*_strict_with` family, inherent `mul_with` / `div_with`), so its adapter
//!   covers every live band-edge cell.
//! - **0.3.3** has the same trait surface but a different odd-tier table
//!   (`D56`/`D114`/`D461`/`D615`/`D923`/`D1231`); its adapter covers the six
//!   widths whose names and digit capacities match the live surface
//!   (`D18`/`D38`/`D76`/`D153`/`D230`/`D307`).
//! - **Overflow contract of both eras**: strict transcendentals panic on an
//!   out-of-range result in every build; the narrow primitive-storage tiers
//!   (`D18` on `i64`, `D38` on `i128`) follow the primitive integer contract for
//!   arithmetic — panic in debug, two's-complement WRAP in release — while the
//!   wide `Int`-storage tiers panic in release too. The adapters declare the
//!   profile-faithful policy (`cfg!(debug_assertions)`): `Overflow::Wrap` for
//!   narrow arithmetic in release, `Overflow::Panic` everywhere else. (The live
//!   0.5.0 contract panics everywhere in every build — that difference is
//!   exactly what the report shows.)

/// Generate one historical-version subject module: the crate-era bridge
/// (`RoundingMode` map + inherent `mul_with`/`div_with` ops trait), the generic
/// compute/limits leaves, the `(width, scale)` dispatch over that version's cell
/// list, and the erased `Subject`. `supports` is the version's honest
/// per-`(width, function)` support predicate — a function a width's API cannot
/// run to completion (see the 0.3.3 width-18 note) is NOT declared, per the
/// golden-subjects rule: omitting beats declaring something that aborts the gate.
macro_rules! historical_subject {
    (
        $(#[$mod_doc:meta])*
        mod $m:ident, crate $ds:ident, version $ver:literal,
        supports $supports:expr,
        types { $($T:ident),+ $(,)? },
        cells { $($D:ident < $s:literal > => $w:literal),+ $(,)? }
    ) => {
        $(#[$mod_doc])*
        pub mod $m {
            use std::collections::BTreeMap;

            use $ds::{
                DecimalArithmetic, DecimalTranscendental, RoundingMode as HistMode, $($T),+
            };
            use decimal_scaled_golden::{
                Capabilities, Computed, DecimalSubject, FnSupport, Function, Limits, Overflow,
                Radix, RoundingMode,
            };

            use crate::FUNCS;

            /// The pinned release this module adapts.
            pub const VERSION: &str = $ver;

            /// The live band-edge `(width, scale)` cells this version also exposes
            /// (a subset of [`crate::CELLS`]; the sync is asserted in
            /// decimal-scale-test's `tests/history.rs` gate).
            pub const CELLS: &[(u32, u32)] = &[ $( ($w, $s) ),+ ];

            /// Map the harness rounding mode onto this era's `RoundingMode` — the
            /// six variants are identical across 0.3.x..0.5.0, but each crate
            /// version is its own type.
            fn hist_mode(m: RoundingMode) -> HistMode {
                match m {
                    RoundingMode::HalfToEven => HistMode::HalfToEven,
                    RoundingMode::HalfAwayFromZero => HistMode::HalfAwayFromZero,
                    RoundingMode::HalfTowardZero => HistMode::HalfTowardZero,
                    RoundingMode::Ceiling => HistMode::Ceiling,
                    RoundingMode::Floor => HistMode::Floor,
                    RoundingMode::Trunc => HistMode::Trunc,
                }
            }

            /// This era's rounded mul/div are inherent (not on a width-generic
            /// trait), so bridge them locally — same shape as the live `DsOps`.
            trait HistOps: Sized {
                fn h_mul_with(self, o: Self, m: HistMode) -> Self;
                fn h_div_with(self, o: Self, m: HistMode) -> Self;
            }
            $(
                impl<const S: u32> HistOps for $T<S> {
                    fn h_mul_with(self, o: Self, m: HistMode) -> Self { self.mul_with(o, m) }
                    fn h_div_with(self, o: Self, m: HistMode) -> Self { self.div_with(o, m) }
                }
            )+

            /// The op only (after parse, before format), at this version's types.
            fn compute<D>(func: Function, x: D, d2: Option<D>, m: HistMode) -> D
            where
                D: DecimalArithmetic + DecimalTranscendental + HistOps + Copy,
            {
                let bin = || d2.expect("binary function needs two operands");
                match func {
                    Function::Sqrt => x.sqrt_strict_with(m),
                    Function::Cbrt => x.cbrt_strict_with(m),
                    Function::Exp => x.exp_strict_with(m),
                    Function::Ln => x.ln_strict_with(m),
                    Function::Log2 => x.log2_strict_with(m),
                    Function::Log10 => x.log10_strict_with(m),
                    Function::Exp2 => x.exp2_strict_with(m),
                    Function::Sin => x.sin_strict_with(m),
                    Function::Cos => x.cos_strict_with(m),
                    Function::Tan => x.tan_strict_with(m),
                    Function::Atan => x.atan_strict_with(m),
                    Function::Asin => x.asin_strict_with(m),
                    Function::Acos => x.acos_strict_with(m),
                    Function::Sinh => x.sinh_strict_with(m),
                    Function::Cosh => x.cosh_strict_with(m),
                    Function::Tanh => x.tanh_strict_with(m),
                    Function::Asinh => x.asinh_strict_with(m),
                    Function::Acosh => x.acosh_strict_with(m),
                    Function::Atanh => x.atanh_strict_with(m),
                    Function::Log => x.log_strict_with(bin(), m),
                    Function::Atan2 => x.atan2_strict_with(bin(), m),
                    Function::Powf => x.powf_strict_with(bin(), m),
                    Function::Hypot => x.hypot_strict_with(bin(), m),
                    Function::Add => x + bin(),
                    Function::Sub => x - bin(),
                    Function::Mul => x.h_mul_with(bin(), m),
                    Function::Div => x.h_div_with(bin(), m),
                    Function::Rem => x % bin(),
                }
            }

            /// Parse → compute → format at one concrete decimal type of this
            /// version. Panics (incl. the era's strict overflow panics) are caught
            /// by the harness as `Computed::Panic` and judged against the cell.
            fn compute_typed<D>(func: Function, inputs: &[String], m: HistMode) -> Computed<String>
            where
                D: DecimalArithmetic
                    + DecimalTranscendental
                    + HistOps
                    + core::str::FromStr
                    + core::fmt::Display
                    + Copy,
            {
                let parse = |s: &str| {
                    s.parse::<D>()
                        .unwrap_or_else(|_| panic!("could not parse representable input {s:?}"))
                };
                let x = parse(&inputs[0]);
                let d2 = inputs.get(1).map(|s| parse(s));
                Computed::Value(compute(func, x, d2, m).to_string())
            }

            /// The exact storage envelope of one concrete decimal type — this
            /// version's own MIN/MAX constants and fixed fractional depth.
            fn limits_typed<D>(scale: u32) -> Limits
            where
                D: DecimalArithmetic + core::fmt::Display,
            {
                Limits {
                    min_value: Some(<D as DecimalArithmetic>::MIN.to_string()),
                    max_value: Some(<D as DecimalArithmetic>::MAX.to_string()),
                    max_precision: scale,
                    max_significant_digits: None,
                }
            }

            fn dispatch_compute(
                width: u32, scale: u32, func: Function, inputs: &[String], m: HistMode,
            ) -> Computed<String> {
                match (width, scale) {
                    $( ($w, $s) => compute_typed::<$D<$s>>(func, inputs, m), )+
                    _ => panic!(
                        "no decimal-scaled {} cell for (width={width}, scale={scale})", VERSION
                    ),
                }
            }

            fn dispatch_limits(width: u32, scale: u32) -> Limits {
                match (width, scale) {
                    $( ($w, $s) => limits_typed::<$D<$s>>($s), )+
                    _ => panic!(
                        "no decimal-scaled {} cell for (width={width}, scale={scale})", VERSION
                    ),
                }
            }

            /// One erased subject of this historical release: a `(width, scale)`
            /// cell tested under one rounding `mode`, `Value = String`.
            #[derive(Clone, Copy)]
            pub struct Subject {
                pub width: u32,
                pub scale: u32,
                pub mode: RoundingMode,
            }

            impl Subject {
                /// A subject tested under the default half-to-even rounding.
                pub fn new(width: u32, scale: u32) -> Subject {
                    Subject::with_mode(width, scale, RoundingMode::HalfToEven)
                }

                /// A subject tested under a specific rounding `mode`.
                pub fn with_mode(width: u32, scale: u32, mode: RoundingMode) -> Subject {
                    Subject { width, scale, mode }
                }

                /// This era's honest overflow contract per function at this width,
                /// faithful to the PROFILE under test: strict transcendentals and
                /// wide `Int`-storage arithmetic panic in every build, while
                /// arithmetic on the narrow primitive-storage tiers (width <= 38)
                /// follows the primitive integer contract — panic in debug,
                /// two's-complement wrap in release.
                fn overflow(&self, func: Function) -> Overflow {
                    use Function::*;
                    match func {
                        Add | Sub | Mul | Div | Rem
                            if self.width <= 38 && !cfg!(debug_assertions) =>
                        {
                            Overflow::Wrap
                        }
                        _ => Overflow::Panic,
                    }
                }
            }

            impl DecimalSubject for Subject {
                type Value = String;

                fn name(&self) -> String {
                    format!("decimal-scaled@{} D{}<{}> {:?}", VERSION, self.width, self.scale, self.mode)
                }

                fn capabilities(&self) -> Capabilities {
                    let supports: fn(u32, Function) -> bool = $supports;
                    let mut functions = BTreeMap::new();
                    for &f in FUNCS {
                        if !supports(self.width, f) {
                            continue;
                        }
                        functions.insert(f, FnSupport { mode: self.mode, overflow: self.overflow(f) });
                    }
                    let mut config = BTreeMap::new();
                    config.insert("width".into(), self.width.to_string());
                    config.insert("scale".into(), self.scale.to_string());
                    config.insert("mode".into(), format!("{:?}", self.mode));
                    config.insert("version".into(), VERSION.into());
                    Capabilities {
                        name: format!("decimal-scaled@{VERSION}"),
                        radix: Radix::Decimal,
                        config,
                        functions,
                    }
                }

                fn string_to_value(&self, s: &str) -> String {
                    // Erased: the concrete parse happens inside `execute` at the
                    // dispatched type, outside any timed span's compute loop.
                    s.to_string()
                }

                fn value_to_string(&self, v: &String) -> String {
                    v.clone()
                }

                fn limits(&self, _value: &str) -> Limits {
                    dispatch_limits(self.width, self.scale)
                }

                fn execute(
                    &self,
                    func: Function,
                    mode: RoundingMode,
                    _overflow: Overflow,
                ) -> impl Fn(&[String]) -> Computed<String> {
                    let (width, scale, m) = (self.width, self.scale, hist_mode(mode));
                    move |inputs| dispatch_compute(width, scale, func, inputs, m)
                }
            }
        }
    };
}

#[cfg(feature = "history-044")]
historical_subject! {
    /// decimal-scaled 0.4.4 — the immediately-previous release. Same tier table
    /// and trait surface as live, so it covers every live band-edge cell and
    /// every golden function at every width.
    mod v044, crate ds_044, version "0.4.4",
    supports |_width, _func| true,
    types { D18, D38, D57, D76, D115, D153, D230, D307, D462, D616, D924, D1232 },
    cells {
        // D18 — i64 storage in this era
        D18<0> => 18, D18<3> => 18, D18<4> => 18, D18<9> => 18, D18<13> => 18, D18<17> => 18,
        // D38 — i128
        D38<0> => 38, D38<2> => 38, D38<6> => 38, D38<9> => 38, D38<10> => 38, D38<12> => 38,
        D38<17> => 38, D38<18> => 38, D38<19> => 38, D38<28> => 38, D38<37> => 38,
        // D57 — 192-bit
        D57<0> => 57, D57<14> => 57, D57<20> => 57, D57<28> => 57, D57<30> => 57, D57<42> => 57,
        D57<56> => 57,
        // D76 — 256-bit
        D76<0> => 76, D76<18> => 76, D76<19> => 76, D76<38> => 76, D76<40> => 76, D76<57> => 76,
        D76<75> => 76,
        // D115 — 384-bit
        D115<0> => 115, D115<28> => 115, D115<50> => 115, D115<57> => 115, D115<86> => 115,
        D115<114> => 115,
        // D153 — 512-bit
        D153<0> => 153, D153<38> => 153, D153<76> => 153, D153<114> => 153, D153<152> => 153,
        // D230 — 768-bit
        D230<0> => 230, D230<57> => 230, D230<115> => 230, D230<172> => 230, D230<229> => 230,
        // D307 — 1024-bit
        D307<0> => 307, D307<30> => 307, D307<50> => 307, D307<70> => 307, D307<76> => 307,
        D307<120> => 307, D307<153> => 307, D307<230> => 307, D307<290> => 307, D307<306> => 307,
        // D462 — 1536-bit
        D462<0> => 462, D462<30> => 462, D462<100> => 462, D462<115> => 462, D462<180> => 462,
        D462<231> => 462, D462<346> => 462, D462<461> => 462,
        // D616 — 2048-bit
        D616<0> => 616, D616<30> => 616, D616<130> => 616, D616<154> => 616, D616<240> => 616,
        D616<308> => 616, D616<462> => 616, D616<590> => 616, D616<615> => 616,
        // D924 — 3072-bit
        D924<0> => 924, D924<30> => 924, D924<180> => 924, D924<231> => 924, D924<350> => 924,
        D924<462> => 924, D924<693> => 924, D924<900> => 924, D924<923> => 924,
        // D1232 — 4096-bit
        D1232<0> => 1232, D1232<30> => 1232, D1232<250> => 1232, D1232<308> => 1232,
        D1232<470> => 1232, D1232<616> => 1232, D1232<924> => 1232, D1232<1200> => 1232,
        D1232<1231> => 1232,
    }
}

#[cfg(feature = "history-033")]
historical_subject! {
    /// decimal-scaled 0.3.3 — the last 0.3.x release. Its odd tiers were named
    /// (and sized) differently (D56/D114/D461/D615/D923/D1231), so only the six
    /// widths whose digit capacities match the live surface are adapted.
    ///
    /// Width-18 transcendentals are NOT declared: 0.3.3's `D18` has no inherent
    /// `*_strict_with` forms (only the no-mode `*_strict`, bridged via `D38`), so
    /// its `DecimalTranscendental` impl's `<D18<SCALE>>::<fn>_strict_with(..)`
    /// delegation resolves back to the trait method itself — infinite recursion
    /// and a stack-overflow ABORT on any input (verified against the published
    /// source and reproduced in isolation). An abort cannot be caught or graded,
    /// so the mode-taking transcendental surface at width 18 is genuinely
    /// unusable in this era and is omitted from the capability map; arithmetic
    /// (operators + inherent `mul_with`/`div_with`) is real at width 18 and
    /// stays declared.
    mod v033, crate ds_033, version "0.3.3",
    supports |width, func| {
        use Function::*;
        width > 18 || matches!(func, Add | Sub | Mul | Div | Rem)
    },
    types { D18, D38, D76, D153, D230, D307 },
    cells {
        // D18 — i64 storage in this era
        D18<0> => 18, D18<3> => 18, D18<4> => 18, D18<9> => 18, D18<13> => 18, D18<17> => 18,
        // D38 — i128
        D38<0> => 38, D38<2> => 38, D38<6> => 38, D38<9> => 38, D38<10> => 38, D38<12> => 38,
        D38<17> => 38, D38<18> => 38, D38<19> => 38, D38<28> => 38, D38<37> => 38,
        // D76 — 256-bit
        D76<0> => 76, D76<18> => 76, D76<19> => 76, D76<38> => 76, D76<40> => 76, D76<57> => 76,
        D76<75> => 76,
        // D153 — 512-bit
        D153<0> => 153, D153<38> => 153, D153<76> => 153, D153<114> => 153, D153<152> => 153,
        // D230 — 768-bit
        D230<0> => 230, D230<57> => 230, D230<115> => 230, D230<172> => 230, D230<229> => 230,
        // D307 — 1024-bit
        D307<0> => 307, D307<30> => 307, D307<50> => 307, D307<70> => 307, D307<76> => 307,
        D307<120> => 307, D307<153> => 307, D307<230> => 307, D307<290> => 307, D307<306> => 307,
    }
}

