"""Provable exactness — the terminate-vs-truncate decision.

The golden format encodes a CLAIM in the stored length: a value stripped shorter
than `gen_precision` fractional digits asserts the result is EXACTLY that decimal
(residual zero — no rounding bump in any mode); a full-length value asserts a
truncation (a nonzero residual exists below, classified by the guard digits).

The adapters' zero-run heuristic (strip when ~40 guard digits beyond the precision
are all zero) is sound for typical values but produces guaranteed FALSE EXACTS on
near-zero transcendentals, whose series structure puts the first residual digit
arbitrarily deep: `sinh(1e-1231) = 1e-1231 + 1.67e-3694 + ...` shows ~2,400
structural zeros, so every finite window concludes "terminated" — yet sinh of a
nonzero rational is irrational by theorem and can never terminate.

This module makes the claim honest: a value may stay STRIPPED only when exactness
is PROVABLE — by theorem (the pure-transcendental family is irrational everywhere
except its known exact points) or by exact rational inverse-check (sqrt/cbrt/
hypot/powf/log..). Everything else is re-padded to the full-precision truncated
form. No digit ever changes: when the heuristic fired, every digit between the
stripped tail and the guard window was zero, so the truthful truncated form IS the
stripped digits right-padded with zeros.
"""
from fractions import Fraction
from typing import List

# Generated by an EXACT rational engine (the fraction oracle): its strip decision
# is itself a proof (the reduced denominator divides 10^precision), never override.
_EXACT_BY_CONSTRUCTION = {"add", "sub", "mul", "div", "rem"}

# Bounds for the rational inverse-checks: a reduced exponent outside these is
# astronomically unlikely to yield a rational result from harvested inputs; we
# then conservatively claim TRUNCATED (and report, so a false pad is visible in
# the run log rather than silent).
_MAX_ROOT = 4096        # q in b^(p/q)
_MAX_POW = 20000        # |p| and integer exponents
_MAX_DIGITS = 2_000_000 # size guard on exact big-rational powers


def _frac_len(s: str) -> int:
    i = s.find(".")
    return 0 if i < 0 else len(s) - i - 1


def _pow_fits(base: Fraction, p: int) -> bool:
    digits = max(len(str(base.numerator)), len(str(base.denominator)))
    return digits * max(1, abs(p)) <= _MAX_DIGITS


def _checked_pow(base: Fraction, p: int):
    """`base**p` as an exact Fraction, or None when out of the size guard."""
    if abs(p) > _MAX_POW or not _pow_fits(base, p):
        return None
    return base ** p


def _provably_exact(func: str, inputs: List[str], value: str) -> bool:
    """True only when `value` (a terminating decimal) is PROVABLY the exact result."""
    x = [Fraction(s) for s in inputs]
    c = Fraction(value)
    a = x[0]
    b = x[1] if len(x) > 1 else None

    # Pure-transcendental family: irrational for every in-domain nonzero rational
    # input (Lindemann-Weierstrass and corollaries) — exact ONLY at the known points.
    if func in ("exp", "sin", "tan", "asin", "atan", "sinh", "tanh", "asinh", "atanh"):
        return a == 0  # f(0) = 0 (exp(0) = 1)
    if func in ("cos", "cosh"):
        return a == 0  # = 1
    if func == "ln":
        return a == 1  # = 0
    if func in ("acos", "acosh"):
        return a == 1  # = 0
    if func == "atan2":
        return a == 0 and b is not None and b > 0  # atan2(0, +x) = 0

    # Algebraic / power family: decide by exact rational inverse-check.
    if func == "sqrt":
        return c * c == a
    if func == "cbrt":
        return c ** 3 == a
    if func == "hypot":
        return c >= 0 and c * c == a * a + b * b
    if func == "exp2":
        if b is not None or a.denominator != 1 or abs(a.numerator) > _MAX_POW:
            return False
        p = _checked_pow(Fraction(2), int(a))
        return p is not None and c == p
    if func in ("log2", "log10"):
        base = Fraction(2) if func == "log2" else Fraction(10)
        p, q = c.numerator, c.denominator
        if q > _MAX_ROOT:
            return False
        lhs = _checked_pow(base, p)
        rhs = _checked_pow(a, q)
        return lhs is not None and rhs is not None and lhs == rhs
    if func == "log":  # log base b of a
        p, q = c.numerator, c.denominator
        if q > _MAX_ROOT:
            return False
        lhs = _checked_pow(b, p)
        rhs = _checked_pow(a, q)
        return lhs is not None and rhs is not None and lhs == rhs
    if func == "powf":  # a ** b
        p, q = b.numerator, b.denominator
        if q > _MAX_ROOT:
            return False
        lhs = _checked_pow(c, q)
        rhs = _checked_pow(a, p)
        return lhs is not None and rhs is not None and lhs == rhs

    return False


def enforce_truncation_marker(func: str, inputs: List[str], value: str, precision: int) -> str:
    """Return `value` with an HONEST terminate-vs-truncate marker: a stripped
    (shorter-than-`precision`) value stays stripped only when provably exact;
    otherwise it is right-padded with zeros to exactly `precision` fractional
    digits — the truthful truncated form (identical digits, truthful claim)."""
    if func in _EXACT_BY_CONSTRUCTION:
        return value
    fl = _frac_len(value)
    if fl >= precision:
        return value  # already the truncated form
    try:
        if _provably_exact(func, inputs, value):
            return value
    except (ValueError, ZeroDivisionError, OverflowError):
        pass  # un-evaluable proof -> conservative: truncated
    pad = precision - fl
    if fl == 0:
        return f"{value}.{'0' * precision}"
    return value + "0" * pad
