"""Generate / revalidate the singular golden set.

generate:   harvest inputs, compute each with the per-function GENERATOR oracle,
            cross-check against EVERY other available oracle, write golden/<func>.au
            (accepted lines, each with a per-line provenance comment).
revalidate: re-check the committed golden set against the validator oracles.

Oracle choice is by RADIX, not convenience: the finite-result arithmetic ops and the
natively-correct base-10 transcendentals are generated by an EXACT/BASE-10 oracle
(a binary oracle has no finite form for an exact decimal, so it bakes a spurious tail
into the last digits); the genuinely-irrational functions are generated by binary
arbitrary precision. Every line is then cross-checked by all the other oracles — and
where a binary validator disagrees with a base-10 generator, the line comment records
the radix and the approximate difference, after validating that difference is a
legitimate radix-rounding artifact (within `ACCEPT_ULPS` at the generation precision),
not a real error.
"""
import argparse
import os
import sys
from pathlib import Path

from .exactness import enforce_truncation_marker
from .functions import FUNCTIONS
from .harvest import harvest
from .oracle import OracleUnavailable, get_oracle
# import adapters so they register themselves:
from .adapters import (  # noqa: F401
    decimal_oracle, flint_oracle, fraction_oracle, mpfr_oracle, mpmath_oracle, sympy_oracle,
)

GEN_PRECISION = 1233
# Guard digits beyond the widest tier's scale — spent deciding the rounding, not
# verifiable depth. GEN_PRECISION = max_decimal_width + GUARD.
GUARD = 2

# THE generator, for every function. There is no per-function table: a generator has to
# be able to PROVE its own answer, and only Arb's rigorous intervals + `unique_fmpz` can
# pin a truncation across the whole surface. `decimal` is exact base-10 but a point value
# behind a fixed window, and `mpmath` is a point float; neither can pin, and `decimal`'s
# inability to pin is exactly what produced four wrong `exp` rows that two oracles then
# agreed on. Everything else validates.
DEFAULT_GENERATOR = "flint"

# The oracles ALLOWED to generate, in preference order. Membership is a capability claim,
# not a convenience: a generator must be able to PIN its own answer.
#
#   flint     — Arb's rigorous intervals + `unique_fmpz` pin a truncation, and it escalates
#               precision until the floor resolves on the true side.
#   fraction  — exact rational arithmetic. It does not need to escalate because there is
#               nothing to resolve: the scaled floor is integer division of exact rationals,
#               so it pins by construction. It covers only the finite-result arithmetic ops,
#               which is precisely where flint's adapter stops (it implements no `rem`).
#
# NOTHING ELSE MAY GENERATE, and the reason is concrete rather than theoretical. `mpmath`
# is a binary point float: an exact decimal such as `1.04692317316873037` has no finite
# binary form, so rendering it to 1233 digits produces a spurious `...36999...` tail that
# the termination check then bakes in as a truncation. `decimal` is exact base-10 but a
# point value behind a fixed window — its inability to pin is what produced six wrong `exp`
# rows that two oracles then agreed on. Both are strong VALIDATORS and neither is fit to
# generate. A fallthrough that picked by validator order rather than by this list generated
# `rem` with mpmath and reproduced that exact tail on ten rows.
GENERATOR_ORDER = ["flint", "fraction"]

# Validator pool, in the order they appear in a line comment. Each is used wherever it
# supports the function AND is not that function's generator; an unavailable backend is
# skipped. More validators ⇒ stronger cross-check (the owner's directive).
VALIDATOR_ORDER = ["mpmath", "flint", "mpfr", "sympy", "decimal", "fraction"]

# Per-function validator EXCLUSIONS. A validator listed here is not consulted for that
# function — not because it is wrong in general, but because it is not viable THERE, and
# a non-viable validator does not merely abstain: a computed disagreement past the radix
# bound DROPS the line (see `_validate_line`), so it can veto a vector the reliable
# oracles agree on and leave a silent hole in coverage.
#
# EMPTY, deliberately — the facility is kept, nothing currently needs it.
#
# It previously excluded mpmath from log1p, atanh and acosh near their domain edges. That
# was diagnosed as a limitation of mpmath; it was not. The defect was OURS: this oracle's
# mpmath adapter budgeted working precision from the RESULT's integer digits with no term
# for the condition number, so for log1p at 1+t = 1e-70 it sized against ln(1e-70) ~= -161
# — three integer digits — while the derivative 1/(1+t) destroyed seventy. A hard cliff at
# A ~= 72, where the headroom was exactly dps - precision = 70.
#
# Fixed at the root (issue #66): the adapter now sizes by the worse of the result's
# magnitude and A = log10|x . grad f(x)|. mpmath then agrees with flint EXACTLY at every
# depth tested, to A ~= 1200 — zero delta annotations across 120/120 atanh and 120/120
# acosh lines — so it is a clean third opinion here, not a tolerated one. Re-excluding it
# would discard a working validator and, on a machine without gmpy2/sympy, drop these
# functions back to a single effective validator.
#
# Keep the mechanism. If a validator is genuinely non-viable for a function, list it —
# a non-viable validator does not merely abstain: a computed disagreement past the radix
# bound DROPS the line (see `_validate_line`), so it can veto a vector the reliable
# oracles agree on and leave a silent hole in coverage. But diagnose the root cause first;
# an exclusion added over an unproven "that library is just bad here" hides our own bug.
VALIDATOR_EXCLUDE: dict[str, set[str]] = {}

# How far a validator may differ from the generated value and still CONFIRM it: at most
# this many units at 10^-precision. Derived from the fetch contract, not tuned to
# observed noise — every oracle floors the SAME true value at the SAME depth, so the
# only legitimate difference is an internal error straddling the truncation boundary,
# which moves the floor by at most one. Beyond it the line is flagged, never silently
# kept: it is a genuine disagreement and a maintainer decides what to do about it.
#
# One is only safe because the generator can PIN. While the generator was a point value
# that could not, a delta of 1 was ambiguous — both the largest honest disagreement AND
# the signature of a straddle — and `2` swallowed flint's correct dissent on four `exp`
# rows for months. With flint generating, a non-pinning validator one unit away is
# showing its own resolution limit, which is a confirmation.
ACCEPT_ULPS = 1


def _frac_len(s: str) -> int:
    i = s.find(".")
    return 0 if i < 0 else len(s) - i - 1


def _scaled_int_at(s: str, n: int) -> int:
    """`s` as a signed integer scaled by 10^n (fraction padded/truncated to n)."""
    neg = s.startswith("-")
    body = s.lstrip("+-")
    ip, fp = body.split(".", 1) if "." in body else (body, "")
    fp = (fp + "0" * n)[:n]
    v = int((ip + fp) or "0")
    return -v if neg else v


def _diff_scaled(a: str, b: str):
    """`(|a-b|_int, n)`: the absolute difference of two decimal strings as a
    non-negative integer at scale 10^-n (n = the deeper fraction length), robust to a
    stripped value comparing against a zero-padded one."""
    n = max(_frac_len(a), _frac_len(b))
    return abs(_scaled_int_at(a, n) - _scaled_int_at(b, n)), n


def _approx_mag(diff_int: int, n: int) -> str:
    """Render `diff_int * 10^-n` as a short `D.DDe±K` magnitude (or `"0"`)."""
    if diff_int == 0:
        return "0"
    s = str(diff_int)
    exp = (len(s) - 1) - n
    lead = s[0] if len(s) == 1 else f"{s[0]}.{s[1:3]}"
    return f"{lead}e{exp:+d}"


def _within_bound(diff_int: int, n: int, precision: int, ulps: int = ACCEPT_ULPS) -> bool:
    """True if a disagreement is a legitimate radix-rounding artifact: at most `ulps`
    units at 10^-precision. A value finer than `precision` must match exactly."""
    if n >= precision:
        return diff_int <= ulps * (10 ** (n - precision))
    return diff_int == 0


def _build_oracles(pool):
    """Instantiate the available oracles named in `pool` (skipping unavailable
    backends), returning `{name: oracle}`."""
    built = {}
    for nm in pool:
        try:
            built[nm] = get_oracle(nm)
        except OracleUnavailable as e:
            print(f"[warn] oracle '{nm}' unavailable: {e}", file=sys.stderr)
    return built


def _generator_for(func, oracles, override):
    """`(name, oracle)` for `func`: the CLI override if given, else the first entry of
    [`GENERATOR_ORDER`] that is available AND implements `func`.

    The order is a preference among oracles that can PIN; it is not a fallthrough to
    whatever happens to answer. Choosing by [`VALIDATOR_ORDER`] instead — which is a
    reporting order, not a trust order — puts `mpmath` first, and generating `rem` with a
    binary point float rewrote ten exact decimals as `...36999...`, the spurious tail
    `fraction_oracle` documents. A non-pinning oracle must never generate.

    NOT SUPPORTING a function is not the same as being UNAVAILABLE, and this used to
    conflate them: only availability was checked, so asking flint for `rem` — which its
    adapter does not implement — flagged every row, wrote an EMPTY `.au`, and exited 0.
    Both cases now resolve to a capable generator or raise.
    """
    if override:
        if override in oracles and oracles[override].can_generate(func):
            return override, oracles[override]
        raise SystemExit(
            f"--generator {override} cannot generate {func}: "
            f"{'does not implement it' if override in oracles else 'unavailable'}")
    for nm in GENERATOR_ORDER:
        if nm in oracles and oracles[nm].can_generate(func):
            if nm != GENERATOR_ORDER[0]:
                print(f"[info] {GENERATOR_ORDER[0]} does not implement {func}; "
                      f"generating with '{nm}'", file=sys.stderr)
            return nm, oracles[nm]
    raise SystemExit(
        f"no generator implements {func} — refusing to write an empty {func}.au. "
        f"Generators tried: {', '.join(GENERATOR_ORDER)}.")


def _validators_for(func, gen_name, oracles):
    """Every available oracle that supports `func` except its generator and any listed
    in VALIDATOR_EXCLUDE for it, in VALIDATOR_ORDER (so a line comment lists them
    deterministically)."""
    excluded = VALIDATOR_EXCLUDE.get(func, frozenset())
    return [
        oracles[nm] for nm in VALIDATOR_ORDER
        if nm != gen_name and nm not in excluded
        and nm in oracles and oracles[nm].supports(func)
    ]


def _validate_line(func, inp, g, gen, validators, precision):
    """Cross-check generated value `g` against each validator. Returns the annotation
    list for the provenance comment, or `None` to DROP the line (a beyond-bound
    disagreement, or nothing could confirm it). A validator that cannot compute the
    input ABSTAINS — it never vetoes a generator-valid line; only a computed
    disagreement past the radix bound does."""
    annotations = []
    validated = 0
    for v in validators:
        try:
            vv = v.value(func, inp, precision)
        except Exception:
            continue  # abstain: this validator can't represent this input
        diff_int, n = _diff_scaled(g, vv)
        validated += 1
        if diff_int == 0:
            annotations.append(v.name())
        elif _within_bound(diff_int, n, precision):
            # The validator confirms, and differed on the way. Record WHICH oracle and
            # BY HOW MUCH — the fact — and nothing else. No causal category: the old
            # form appended the radix, and `flint(delta~1e-1233, binary)` sat on four
            # wrong rows for months precisely because "binary" pre-explained the
            # difference as benign and every reader skipped it. Whether a delta is
            # acceptable is `_within_bound`'s job, decided here; this string's job is
            # to keep the evidence findable by a human or a grep.
            annotations.append(f"{v.name()}(delta~{_approx_mag(diff_int, n)})")
        else:
            print(
                f"[FLAG] disagree {func}{inp}: {gen.name()}={g[:28]}.. "
                f"{v.name()}={vv[:28]}.. delta~{_approx_mag(diff_int, n)} > {ACCEPT_ULPS}ulp",
                file=sys.stderr,
            )
            return None
    if validated == 0:
        print(f"[FLAG] unvalidated {func}{inp}: no oracle could confirm", file=sys.stderr)
        return None
    return annotations


# --- parallel generation ------------------------------------------------------------
# One work item = one (func, input) line; lines are independent, so generation is
# embarrassingly parallel. Each worker process builds the oracle cache ONCE (the pool
# initializer) — full-precision compute on every oracle is the cost, so we spread it
# across cores rather than trade away validation depth.
_POOL_ORACLES = {}
_POOL_GEN_OVERRIDE = None


def _pool_init(validator_names, gen_override):
    global _POOL_ORACLES, _POOL_GEN_OVERRIDE
    _POOL_ORACLES = _build_oracles(
        set(validator_names) | {DEFAULT_GENERATOR}
    )
    _POOL_GEN_OVERRIDE = gen_override


def _gen_line(item):
    """Compute one golden line in a worker: `(func, (provenance, dataline))`, or
    `(func, None)` if the generator failed or the line was dropped."""
    func, inp, why, precision = item
    gen_name, gen = _generator_for(func, _POOL_ORACLES, _POOL_GEN_OVERRIDE)
    validators = _validators_for(func, gen_name, _POOL_ORACLES)
    try:
        g = gen.value(func, inp, precision)
    except Exception as e:
        print(f"[flag] generator {gen.name()} failed {func}{inp}: {e}", file=sys.stderr)
        return func, None
    # Honest terminate-vs-truncate marker: a stripped value stays stripped only
    # when exactness is PROVABLE (theorem / exact inverse-check); a false exact
    # from the adapters' zero-run heuristic is re-padded to the truncated form
    # (identical digits, truthful claim). See oracle/exactness.py.
    g = enforce_truncation_marker(func, inp, g, precision)
    annotations = _validate_line(func, inp, g, gen, validators, precision)
    if annotations is None:
        return func, None
    # The trailing clause is the input's WHY from its `.pb` file — the intent
    # provenance the gold keeps from its lead.
    prov = f"// generated by: {gen.name()}, validated by: [{', '.join(annotations)}] ; {why}"
    return func, (prov, " ".join(inp + [g]))


def _write_func(out_dir, func, rows, precision):
    """Sort + dedup a function's rows by data line (provenance is deterministic per
    line) and write its `.au` file — UTF-8, CRLF to match the committed convention."""
    seen, uniq = set(), []
    for prov, ln in sorted(rows, key=lambda pr: pr[1]):
        if ln in seen:
            continue
        seen.add(ln)
        uniq.append((prov, ln))
    # The header records the RUN's default precision, not a per-row depth, so a
    # `#precision=`-overridden row can legitimately carry MORE fraction digits than
    # the header names. That is not a bug and needs no widening: the harness only
    # ever tests `len(frac) >= gen_precision` (`GoldenValue::truncated_at`) to decide
    # a residual exists below the stored digits, and consumes every digit past the
    # graded scale, so a deeper row stays truthful under a shallower header.
    header = f"#gen_precision={precision}\n#guard={GUARD}\n"
    out_text = header + "".join(f"{prov}\n{ln}\n" for prov, ln in uniq)
    (out_dir / f"{func}.au").write_text(out_text, encoding="utf-8", newline="\r\n")
    return len(uniq)


def cmd_generate(args):
    validator_names = args.validators.split(",") if args.validators else VALIDATOR_ORDER
    src = Path(args.golden_src)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    funcs = args.functions.split(",")

    # Read every function's `.pb` cases, then flatten to
    # (func, input, why, precision) items.
    items = []
    for func in funcs:
        cases = harvest(func, src)
        if args.limit:
            cases = cases[: args.limit]
        # `_gen_line` and `_validate_line` have always taken precision PER ITEM;
        # this line was the only place that collapsed it to one scalar. A `.pb`
        # block may now override it (`#precision=`) for rows that are only
        # gradable when generated deeper than the set's default.
        items += [
            (func, inp, why, args.precision if prec is None else prec)
            for inp, why, prec in cases
        ]
    total = len(items)
    jobs = args.jobs if args.jobs else max(1, round((os.cpu_count() or 2) * 0.8))
    print(f"generating {total} lines, {len(funcs)} functions, {jobs} worker(s)", file=sys.stderr)

    results = {f: [] for f in funcs}
    done = 0

    def collect(func, row):
        nonlocal done
        if row is not None:
            results[func].append(row)
        done += 1
        if done % 2000 == 0 or done == total:
            print(f"  ...{done}/{total} lines", file=sys.stderr)

    if jobs <= 1:
        _pool_init(validator_names, args.generator)
        for item in items:
            collect(*_gen_line(item))
    else:
        import multiprocessing as mp
        with mp.Pool(jobs, initializer=_pool_init,
                     initargs=(validator_names, args.generator)) as pool:
            for func, row in pool.imap_unordered(_gen_line, items, chunksize=8):
                collect(func, row)

    empty = []
    for func in funcs:
        n = _write_func(out_dir, func, results[func], args.precision)
        print(f"{func}: wrote {n} lines")
        if n == 0:
            empty.append(func)
    # A `.au` with no rows still parses and the gate still passes — it simply grades
    # NOTHING. That has to be louder than a zero exit code, or a whole function can drop
    # out of coverage in silence.
    if empty:
        raise SystemExit(
            "wrote 0 rows for: " + ", ".join(empty) +
            " — every input was flagged or dropped, and those .au files are now empty. "
            "Restore them from git, fix the cause, and regenerate.")
    return 0


def cmd_revalidate(args):
    pool = args.validators.split(",") if args.validators else VALIDATOR_ORDER
    oracles = _build_oracles(set(pool) | {DEFAULT_GENERATOR})
    out_dir = Path(args.out)
    mismatches = 0
    for func in args.functions.split(","):
        path = out_dir / f"{func}.au"
        if not path.exists():
            continue
        f = FUNCTIONS[func]
        gen_name, _ = _generator_for(func, oracles, None)
        validators = _validators_for(func, gen_name, oracles)
        for line in path.read_text().splitlines():
            s = line.strip()
            if not s or s.startswith("#") or s.startswith("//"):
                continue
            fields = line.split()
            inp, stored = fields[: f.arity], fields[f.arity]
            # Re-verify each row at ITS OWN depth. A `#precision=`-overridden row is
            # stored deeper than `--precision`; recomputing it at the shallower
            # default would leave `_within_bound` comparing at `n` = the row's depth
            # against the default precision, i.e. a tolerance of `ulps * 10^(n-p)` —
            # astronomically loose, so the row would pass VACUOUSLY, verified only to
            # the default depth. The stored fraction length is the row's own
            # generation precision, so use it whenever it is the deeper of the two.
            row_precision = max(args.precision, _frac_len(stored))
            for v in validators:
                try:
                    vv = v.value(func, inp, row_precision)
                except Exception:
                    continue
                diff_int, n = _diff_scaled(stored, vv)
                if not _within_bound(diff_int, n, row_precision):
                    print(f"[MISMATCH] {func}{inp}: stored={stored[:28]}.. "
                          f"{v.name()}={vv[:28]}.. delta~{_approx_mag(diff_int, n)}", file=sys.stderr)
                    mismatches += 1
    print(f"revalidate: {mismatches} mismatch(es)")
    return 1 if mismatches else 0


def main(argv=None):
    p = argparse.ArgumentParser(prog="oracle.generate")
    sub = p.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate")
    g.add_argument("--functions", required=True)
    g.add_argument("--out", required=True)
    # The oracle's input source: the per-function `lead/<func>.lead` files
    # (the lead the generator transmutes into gold).
    g.add_argument("--golden-src", default="lead")
    g.add_argument("--config", default=None)
    g.add_argument("--generator", default=None)
    g.add_argument("--validators", default=None)
    g.add_argument("--precision", type=int, default=GEN_PRECISION)
    g.add_argument("--limit", type=int, default=None)
    g.add_argument("--jobs", type=int, default=None,
                   help="worker processes (default: ~80%% of CPU cores)")
    g.set_defaults(fn=cmd_generate)
    r = sub.add_parser("revalidate")
    r.add_argument("--functions", required=True)
    r.add_argument("--out", required=True)
    r.add_argument("--config", default=None)
    r.add_argument("--validators", default=None)
    r.add_argument("--precision", type=int, default=GEN_PRECISION)
    r.set_defaults(fn=cmd_revalidate)
    args = p.parse_args(argv)
    sys.exit(args.fn(args) or 0)


if __name__ == "__main__":
    main()
