//! The [`WidthLE`] trait — encodes "this storage type can losslessly
//! widen to that target storage type".
//!
//! Marker trait used by the cross-scale-op constructors (`mul_of`,
//! `add_of`, `cmp_of`, etc.) emitted on every decimal width: a source
//! storage `W` may participate in an operation targeted at storage
//! `Target` only when `W: WidthLE<Target>`.
//!
//! The trait is implemented for the reflexive case (`W: WidthLE<W>`)
//! and for every (narrower, wider) storage pair the crate ships. The
//! widening is performed by the existing
//! [`crate::int::types::traits::wide_cast`] helper for the wide tier and a
//! plain `as` cast for the narrow primitive tier.
//!
//! `WidthLE` is intentionally not exposed as a public trait method on
//! the decimal types — it is a *bound* used inside the per-width
//! `mul_of` / `cmp_of` / … inherent methods to limit the legal source
//! widths.
//!
//! # Trait surface
//!
//! ```ignore
//! pub trait WidthLE<Target>: Copy {
//!     /// Widens `self` to the `Target` storage type. Always lossless
//!     /// (every value representable in `Self` is representable in
//!     /// `Target`).
//!     fn widen_into(self) -> Target;
//! }
//! ```

/// Trait expressing "this storage type can losslessly widen to the
/// target storage type". Implemented for every (narrower, wider)
/// signed-integer storage pair the crate ships, plus the reflexive
/// (W → W) case.
pub trait WidthLE<Target>: Copy {
    /// Widens `self` to the `Target` storage type. Lossless by
    /// construction — `Target`'s range strictly covers `Self`'s.
    fn widen_into(self) -> Target;
}

// ── Reflexive impls (W → W) for every storage type. ──────────────────

impl WidthLE<i32> for i32 {
    #[inline]
    fn widen_into(self) -> i32 {
        self
    }
}
impl WidthLE<i64> for i64 {
    #[inline]
    fn widen_into(self) -> i64 {
        self
    }
}
impl WidthLE<i128> for i128 {
    #[inline]
    fn widen_into(self) -> i128 {
        self
    }
}

// ── Native widening (primitive → primitive). ─────────────────────────

impl WidthLE<i64> for i32 {
    #[inline]
    fn widen_into(self) -> i64 {
        self as i64
    }
}
impl WidthLE<i128> for i32 {
    #[inline]
    fn widen_into(self) -> i128 {
        self as i128
    }
}
impl WidthLE<i128> for i64 {
    #[inline]
    fn widen_into(self) -> i128 {
        self as i128
    }
}

// ── Wide-tier reflexive + cross impls. ───────────────────────────────
//
// Generated by `decl_width_le_wide_pair!` which expands to one impl per
// (source storage, target storage) ordering. The wide storages are
// `Int192 < Int256 < Int384 < Int512 < Int768 < Int1024 < Int1536 <
//  Int2048 < Int3072 < Int4096`. Primitive sources (`i32`/`i64`/`i128`)
// widen into every wide storage via the `wide_cast` helper.

#[cfg(any(
    feature = "d57",
    feature = "d76",
    feature = "d115",
    feature = "d153",
    feature = "d230",
    feature = "d307",
    feature = "d462",
    feature = "d616",
    feature = "d924",
    feature = "d1232",
    feature = "wide",
    feature = "x-wide",
    feature = "xx-wide",
))]
macro_rules! impl_width_le_wide_reflexive {
    ($Storage:ty) => {
        impl $crate::types::traits::width_le::WidthLE<$Storage> for $Storage {
            #[inline]
            fn widen_into(self) -> $Storage {
                self
            }
        }
    };
}

#[cfg(any(
    feature = "d57",
    feature = "d76",
    feature = "d115",
    feature = "d153",
    feature = "d230",
    feature = "d307",
    feature = "d462",
    feature = "d616",
    feature = "d924",
    feature = "d1232",
    feature = "wide",
    feature = "x-wide",
    feature = "xx-wide",
))]
macro_rules! impl_width_le_native_to_wide {
    ($Wide:ty, $Native:ty) => {
        impl $crate::types::traits::width_le::WidthLE<$Wide> for $Native {
            #[inline]
            fn widen_into(self) -> $Wide {
                $crate::int::types::traits::wide_cast(self as i128)
            }
        }
    };
}

#[cfg(any(
    feature = "d57",
    feature = "d76",
    feature = "d115",
    feature = "d153",
    feature = "d230",
    feature = "d307",
    feature = "d462",
    feature = "d616",
    feature = "d924",
    feature = "d1232",
    feature = "wide",
    feature = "x-wide",
    feature = "xx-wide",
))]
macro_rules! impl_width_le_wide_pair {
    ($Wider:ty, $Narrower:ty) => {
        impl $crate::types::traits::width_le::WidthLE<$Wider> for $Narrower {
            #[inline]
            fn widen_into(self) -> $Wider {
                $crate::int::types::traits::wide_cast(self)
            }
        }
    };
}

// Reflexive impls for each wide storage that exists.

#[cfg(any(feature = "d57", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int192);
#[cfg(any(feature = "d76", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int256);
#[cfg(any(feature = "d115", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int384);
#[cfg(any(feature = "d153", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int512);
#[cfg(any(feature = "d230", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int768);
#[cfg(any(feature = "d307", feature = "wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int1024);
#[cfg(any(feature = "d462", feature = "x-wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int1536);
#[cfg(any(feature = "d616", feature = "x-wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int2048);
#[cfg(any(feature = "d924", feature = "xx-wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int3072);
#[cfg(any(feature = "d1232", feature = "xx-wide"))]
impl_width_le_wide_reflexive!(crate::wide_int::Int4096);

// Native (i32/i64/i128) → wide impls.
//
// For every wide storage, allow widening from the three primitive
// integer storages. `wide_cast` accepts `i128` sources, so the i32 /
// i64 inputs are upcast to i128 first (always lossless).

macro_rules! impls_native_to_one_wide {
    ($Wide:ty) => {
        impl_width_le_native_to_wide!($Wide, i32);
        impl_width_le_native_to_wide!($Wide, i64);
        impl_width_le_native_to_wide!($Wide, i128);
    };
}

#[cfg(any(feature = "d57", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int192);
#[cfg(any(feature = "d76", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int256);
#[cfg(any(feature = "d115", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int384);
#[cfg(any(feature = "d153", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int512);
#[cfg(any(feature = "d230", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int768);
#[cfg(any(feature = "d307", feature = "wide"))]
impls_native_to_one_wide!(crate::wide_int::Int1024);
#[cfg(any(feature = "d462", feature = "x-wide"))]
impls_native_to_one_wide!(crate::wide_int::Int1536);
#[cfg(any(feature = "d616", feature = "x-wide"))]
impls_native_to_one_wide!(crate::wide_int::Int2048);
#[cfg(any(feature = "d924", feature = "xx-wide"))]
impls_native_to_one_wide!(crate::wide_int::Int3072);
#[cfg(any(feature = "d1232", feature = "xx-wide"))]
impls_native_to_one_wide!(crate::wide_int::Int4096);

// Wide → wide cross impls. For every ordered pair (narrower, wider).
// Each impl is independently gated on BOTH storages being available.

macro_rules! wide_pair {
    ($Wider:ty, $Narrower:ty, $WiderFeat:literal, $NarrowerFeat:literal,
     $WiderUmbrella:literal, $NarrowerUmbrella:literal) => {
        #[cfg(all(
                    any(feature = $WiderFeat, feature = $WiderUmbrella),
                    any(feature = $NarrowerFeat, feature = $NarrowerUmbrella),
                ))]
        impl_width_le_wide_pair!($Wider, $Narrower);
    };
}

// Int192 (D57) is widest of nothing narrower (D57 is the narrowest
// wide). Pairs where Int192 is the wider:
wide_pair!(
    crate::wide_int::Int256,
    crate::wide_int::Int192,
    "d76",
    "d57",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int384,
    crate::wide_int::Int192,
    "d115",
    "d57",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int512,
    crate::wide_int::Int192,
    "d153",
    "d57",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int768,
    crate::wide_int::Int192,
    "d230",
    "d57",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1024,
    crate::wide_int::Int192,
    "d307",
    "d57",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int192,
    "d462",
    "d57",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int192,
    "d616",
    "d57",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int192,
    "d924",
    "d57",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int192,
    "d1232",
    "d57",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int384,
    crate::wide_int::Int256,
    "d115",
    "d76",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int512,
    crate::wide_int::Int256,
    "d153",
    "d76",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int768,
    crate::wide_int::Int256,
    "d230",
    "d76",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1024,
    crate::wide_int::Int256,
    "d307",
    "d76",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int256,
    "d462",
    "d76",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int256,
    "d616",
    "d76",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int256,
    "d924",
    "d76",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int256,
    "d1232",
    "d76",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int512,
    crate::wide_int::Int384,
    "d153",
    "d115",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int768,
    crate::wide_int::Int384,
    "d230",
    "d115",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1024,
    crate::wide_int::Int384,
    "d307",
    "d115",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int384,
    "d462",
    "d115",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int384,
    "d616",
    "d115",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int384,
    "d924",
    "d115",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int384,
    "d1232",
    "d115",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int768,
    crate::wide_int::Int512,
    "d230",
    "d153",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1024,
    crate::wide_int::Int512,
    "d307",
    "d153",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int512,
    "d462",
    "d153",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int512,
    "d616",
    "d153",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int512,
    "d924",
    "d153",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int512,
    "d1232",
    "d153",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int1024,
    crate::wide_int::Int768,
    "d307",
    "d230",
    "wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int768,
    "d462",
    "d230",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int768,
    "d616",
    "d230",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int768,
    "d924",
    "d230",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int768,
    "d1232",
    "d230",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int1536,
    crate::wide_int::Int1024,
    "d462",
    "d307",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int1024,
    "d616",
    "d307",
    "x-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int1024,
    "d924",
    "d307",
    "xx-wide",
    "wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int1024,
    "d1232",
    "d307",
    "xx-wide",
    "wide"
);

wide_pair!(
    crate::wide_int::Int2048,
    crate::wide_int::Int1536,
    "d616",
    "d462",
    "x-wide",
    "x-wide"
);
wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int1536,
    "d924",
    "d462",
    "xx-wide",
    "x-wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int1536,
    "d1232",
    "d462",
    "xx-wide",
    "x-wide"
);

wide_pair!(
    crate::wide_int::Int3072,
    crate::wide_int::Int2048,
    "d924",
    "d616",
    "xx-wide",
    "x-wide"
);
wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int2048,
    "d1232",
    "d616",
    "xx-wide",
    "x-wide"
);

wide_pair!(
    crate::wide_int::Int4096,
    crate::wide_int::Int3072,
    "d1232",
    "d924",
    "xx-wide",
    "xx-wide"
);
