// SPDX-FileCopyrightText: 2026 John Moxley
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Baked binary Tang `ln(1 + i/M)` lookup table — the NARROW high
//! prefix (`M = 128`).
//!
//! GENERATED by `scripts/gen_ln_tang_table.py` (flint/Arb oracle —
//! every digit below is pinned by a rigorous interval bound). Do
//! NOT edit by hand; re-run the script and commit its output. This
//! file is NOT produced at build time — `build.rs` is untouched.
//!
//! Any change belongs in `scripts/gen_ln_tang_table.py`, never in
//! this file. Re-run the generator and commit both; a hand-edit here
//! is silently reverted the next time anyone regenerates.
//!
//! Each of the `M + 1 = 129` slots is the TRUNCATION of the matching
//! [`crate::algos::support::ln_tang_table`] slot to its top
//! `8` limbs. Both are emitted from the same oracle values in the
//! same generator run, so this table **is** the wide table's high-limb
//! prefix by construction — not a second data set to keep in step.
//! `ln_tang_slot`'s tests assert that identity wherever both compile.
//!
//! ## Why it exists
//!
//! Binary size, and nothing else. The wide table is `129 · 112 · 8 B`
//! ≈ 115 KB and is `_wide-support`-gated, so a narrow (`D18`/`D38`-only,
//! `no_std`) build must not carry it; this one is ≈ 8 KB.
//!
//! `B = 512` bits is sized against the narrow work rung `Int<12>`,
//! whose Ziv-escalation cap is `BITS/8 = 96` decimal digits — the
//! deepest working scale a narrow call can demand. The accessor needs
//! `ceil((96 · 3322/1000 + 64) / 64) = 6` limbs there, so the stored
//! `8` carry two limbs (≈ 38 decimal digits) of headroom.

/// Number of u64 limbs per stored narrow slot.
pub(crate) const LN_TANG_NARROW_LIMBS: usize = 8;

/// Binary fixed-point exponent of a narrow slot — the wide entry's
/// `round(ln(1+i/M) · 2^7168)` truncated to `2^512`.
pub(crate) const LN_TANG_NARROW_B: u32 = 512;

/// The `M + 1` narrow slots, each the top `8` limbs of the wide
/// entry, MOST-SIGNIFICANT limb first. Index by `i ∈ [0, 128]`. The
/// `i = 0` slot is `ln(1) = 0`; the `i = 128` slot is `ln 2`.
pub(crate) static LN_TANG_SLOTS_NARROW: [[u64; 8]; 129] = [
    // i = 0: ln(1 + 0/128)
    [
        0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
        0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000,
    ],
    // i = 1: ln(1 + 1/128)
    [
        0x01fe02a6b106788f, 0xc37690391dc282d2, 0xb3db2c3ef9a073a8, 0x767027886b5788c3,
        0xd122f7ff51bc9855, 0xe4c4a44afacf68d7, 0xd99e1b469bb0f82e, 0xd4520ee290d465bf,
    ],
    // i = 2: ln(1 + 2/128)
    [
        0x03f815161f807c79, 0xf3db4e9a6f57aadb, 0xeb03be903ddc5335, 0xd140fe0577122f83,
        0x7a59b490758dcd0b, 0x7841aece8f9f71cc, 0xba7510a93b4ede62, 0xe808e1531ef3a140,
    ],
    // i = 3: ln(1 + 3/128)
    [
        0x05ee46c1f56c46aa, 0x49fd531c5af00773, 0x53c40a9487466226, 0x96efb6733a835116,
        0xd0f00eba0efcad2b, 0x67ded6c545ddab78, 0x086d1607140b9e2f, 0x9bb5ffe031e125ae,
    ],
    // i = 4: ln(1 + 4/128)
    [
        0x07e0a6c39e0cc013, 0x3e3f04f1ef229fae, 0xaefae14cddf35ad1, 0xdf6c758fe3673dcd,
        0x8a38a3ffec979e9d, 0x55d9a7bae0a5d2e3, 0x9ce344310f6e3a39, 0x02127ef47cb29271,
    ],
    // i = 5: ln(1 + 5/128)
    [
        0x09cf43dcff5eafd4, 0x80ad90155c8a7235, 0x5eb87846f4c603a3, 0xd0eb0381a91dfcd4,
        0x747318fe3fa03b71, 0x28b7bf2948f34c0f, 0x5c3e9eb0d45e4a00, 0xd5872e7012db1d0e,
    ],
    // i = 6: ln(1 + 6/128)
    [
        0x0bba2c7b196e7e23, 0x1a7950f7252c163c, 0x9bf701b2a89d8cb0, 0x7d674deba3a2b779,
        0xe9b91ebf9f71bf4e, 0xf5c2a87697a6304c, 0x457ce7cdafeeec68, 0xc6e2905e5d61ffe8,
    ],
    // i = 7: ln(1 + 7/128)
    [
        0x0da16eb88cb8df61, 0x468a63ecfb66e94a, 0xbce26340fc53dc9e, 0x77778bea9e448511,
        0x1abee2d17d96a5a1, 0x766e7cbf647b0999, 0x6f275dc85665b730, 0x212b939ab0b4ed5d,
    ],
    // i = 8: ln(1 + 8/128)
    [
        0x0f85186008b15330, 0xbe64b8b775997898, 0xd3474d3375b52596, 0x71851f0a96f69849,
        0x6172da6bde861006, 0x908722d985badcca, 0x99f0cc1de7a9459e, 0x9bc3578977e6bc16,
    ],
    // i = 9: ln(1 + 9/128)
    [
        0x116536eea37ae0e8, 0x625c173dd325e46d, 0xa42905a6685a6aad, 0x37e6cb88264acee4,
        0x8b8cbcb12c6a3b15, 0x0d7918c77b015b41, 0x8b8cbbc77a5a64e0, 0x8e4540e2fe8e2388,
    ],
    // i = 10: ln(1 + 10/128)
    [
        0x1341d7961bd1d092, 0x998376104d137502, 0x1a0eca5b78467950, 0xe61038805d37b037,
        0x2b83c4527bb59c4a, 0x69e2cdb80bbafb1c, 0x684138933429d182, 0x9fec8cce9e866ba2,
    ],
    // i = 11: ln(1 + 11/128)
    [
        0x151b073f06183f69, 0x278e686a2f91584b, 0xc9c7e09bc3e10deb, 0x969611657aa339ed,
        0x84d7db82e7a295c0, 0x3e6b4fb0f457addf, 0xbb355b22f8ee1435, 0xed9027ae9de15b17,
    ],
    // i = 12: ln(1 + 12/128)
    [
        0x16f0d28ae56b4b9b, 0xe499b9ed19b640ce, 0x50c1ef65087fdf23, 0x812f38a034b59afd,
        0x284ac3feba4a6521, 0xc1e6a872644009ed, 0xfa8c6dd6dc5afe2a, 0xa047161ceed4c843,
    ],
    // i = 13: ln(1 + 13/128)
    [
        0x18c345d6319b20f5, 0xacb42a65edab4357, 0x02603e40d7c4c4b4, 0x799d33d000e87966,
        0x0ae26ff95115bbde, 0xcecb8c1d5de8d145, 0xff89c5d41025284d, 0xd1080d7cc69d37d7,
    ],
    // i = 14: ln(1 + 14/128)
    [
        0x1a926d3a4ad56365, 0x0bd22a9c3aa4c79a, 0x9f67e22ed398d01d, 0xeab11fa42911a622,
        0xef3f32ca7818f6b5, 0xf726f31bab52ff3b, 0x7748a795a02b9473, 0x48646831427b81cc,
    ],
    // i = 15: ln(1 + 15/128)
    [
        0x1c5e548f5bc74315, 0xd617ef8161b1769d, 0x966af8dc3772cac1, 0x163e7f6cbbc664d5,
        0x87d91901b458f0de, 0xf7d0cf3e3211078e, 0xe55d167eedfe76e2, 0xf159cd13d6fdaaad,
    ],
    // i = 16: ln(1 + 16/128)
    [
        0x1e27076e2af2e5e9, 0xea87ffe1fe9e155d, 0xb94ebc4017f6f957, 0xdd0897c1ff917c95,
        0x9e05a342cfca2ad7, 0xa023f5742646cc77, 0xfd2c1f6cf9a71577, 0x286a0066ec0c6459,
    ],
    // i = 17: ln(1 + 17/128)
    [
        0x1fec9131dbeabaaa, 0x2e5199f9324e3bfe, 0x91e2ba81202ec615, 0x272625363c82c160,
        0x8d96c694f63a8eac, 0x630d9164d807cbc2, 0x42245ab7cdfa2d56, 0x2c05bc00d8f25186,
    ],
    // i = 18: ln(1 + 18/128)
    [
        0x21aefcf9a11cb2cd, 0x2ee2f481855d1c48, 0x4cb4fd8d03860ef8, 0x80c716868c17ff3a,
        0x17139cd6d8c48b9f, 0xd424a286289698cb, 0x043a6981cbb335eb, 0x03ee435a48281841,
    ],
    // i = 19: ln(1 + 19/128)
    [
        0x236e55aa5ecf4052, 0x0c08d1cb35ce7e77, 0x8fd9099532ec12a6, 0xd406e0e46589e2cd,
        0xd04f42b419b53ea7, 0x1ca388fee004bec4, 0x964d36ff95174873, 0xf7fe68d82db638f1,
    ],
    // i = 20: ln(1 + 20/128)
    [
        0x252aa5f03fea4698, 0x0bb8e203edf4d109, 0xfbc9070f7e29fbad, 0x3603f226de50d341,
        0xbdef2e4cc81786ff, 0xe399a8f636cd3025, 0x6d706ec47a3b264f, 0x47b9f129c430292d,
    ],
    // i = 21: ln(1 + 21/128)
    [
        0x26e3f8403d1ee877, 0x9b2d8abc627f2e81, 0xf326daa75290329f, 0x744e54fde20dbc5c,
        0x3dce1f32ca360847, 0x727dc7fd815edc13, 0x50a7553d960168fc, 0xca484bb62e492011,
    ],
    // i = 22: ln(1 + 22/128)
    [
        0x289a56d996fa3ccf, 0xa7b2a1f0fc3c1882, 0xcaf99174f60aa4f8, 0x0b60281e0372cfc2,
        0x1e4be88c2aa9b674, 0x074dbd5a0ec2218f, 0x5bf7c41b1d45c958, 0x70f9c3c89bffbbee,
    ],
    // i = 23: ln(1 + 23/128)
    [
        0x2a4dcbc743686f45, 0xc803adc796334db7, 0x98c76a888aa87317, 0xb14f7cdaa66f4587,
        0x7c45f28623162370, 0xc8651fb18ae86452, 0x22d074e059700ee3, 0x0cfa87ee08278a9d,
    ],
    // i = 24: ln(1 + 24/128)
    [
        0x2bfe60e14f27a790, 0xe7c4140e424775fc, 0xd55c7355fdf3e631, 0xc0acfed6d928291d,
        0xedbafdfd023311f9, 0x97d44cc5b541268f, 0x4baeb699b88a7375, 0xad7848e7fb5d87b5,
    ],
    // i = 25: ln(1 + 25/128)
    [
        0x2dac1fce33a4391a, 0xa8ecb89974378df6, 0x8c9609738dac1eee, 0x4e8db6cc968814de,
        0xff787daeae503ade, 0x30ab184dac01a942, 0x971ceb8ae1505b15, 0xc42d57f063f3206f,
    ],
    // i = 26: ln(1 + 26/128)
    [
        0x2f57120421b21237, 0xc6d65ad40c100c8f, 0xfc2929b1021656ae, 0xc62cba077969d04f,
        0x35ca286ff91588f5, 0x4175c8e206b19fb0, 0x257473ac8f0a96aa, 0xa99801dda6ded1b1,
    ],
    // i = 27: ln(1 + 27/128)
    [
        0x30ff40ca41922120, 0x401202fb932ef5a5, 0x5704b6b7eb4ebea2, 0x8a6cd2cd02e9b86e,
        0x83edc1bd4d29abb4, 0xde8c1375727ee8b2, 0xb8ade2b5d5c664fa, 0xdb5f513f87ccd984,
    ],
    // i = 28: ln(1 + 28/128)
    [
        0x32a4b539e8ad68ec, 0x8260ea71712cec4c, 0xa0bed3cf71766947, 0x13daa19ed7f0a39d,
        0x9ba61844978b7d19, 0x421b1cf777b20123, 0x45a5f1bad8375221, 0x17b14e8646577c95,
    ],
    // i = 29: ln(1 + 29/128)
    [
        0x3447783fc56ac632, 0x6e2360f533184fc7, 0xe36cdb1665bcc380, 0x99f2aab1c2c7880f,
        0xa048eef8d4945cea, 0xd7c1d20a43732b59, 0x0d91f71407d3dd44, 0x1e544a43b58674cb,
    ],
    // i = 30: ln(1 + 30/128)
    [
        0x35e7929d017fe5b1, 0x9cc0326f99eb9767, 0x69b8b9a5d50ca14a, 0x7622eb26036bf0e3,
        0xc52dbae0adc20980, 0xb9509e418124d050, 0xb5322b036c95595e, 0x3b6ab9a17d1d4ffe,
    ],
    // i = 31: ln(1 + 31/128)
    [
        0x37850ce85b19ac53, 0xf39d121c3d53c3c5, 0x87b948d9079ada33, 0xcbd352031118cc85,
        0xe6ccfad966f4429f, 0x87f65b0b7a1bf371, 0xc271e75284d501a8, 0x148f89ff54f5bfa1,
    ],
    // i = 32: ln(1 + 32/128)
    [
        0x391fef8f35344358, 0x4bb03de5ff734495, 0xc765ea7411adc1b1, 0x70f133f564bfc746,
        0xa192a8fd7cdd3baa, 0x3103360ed08de46d, 0xe9fc85bfc087279f, 0x78383094d75732ea,
    ],
    // i = 33: ln(1 + 33/128)
    [
        0x3ab842d69f7722b7, 0x221acbf26a00e1e3, 0x673d12bf9c69752d, 0xccd07cf7f33a42b8,
        0xd71548c2883386a2, 0x557eeedf31c6c7e8, 0xf0d2680eb3c62df4, 0x47720fb7c8b2aae1,
    ],
    // i = 34: ln(1 + 34/128)
    [
        0x3c4e0edc55e5cbd3, 0xd50fffc3fd3c2abb, 0x729d78802fedf2af, 0xba112f83ff22f92b,
        0x3c0b46859f9455af, 0x4047eae84c8d98ef, 0xfa583ed9f34e2aee, 0x50d400cdd818c8b2,
    ],
    // i = 35: ln(1 + 35/128)
    [
        0x3de15b97b8b26ca4, 0x31bca86e106429f5, 0xa5098683a47c3a3c, 0xa5834a1a19f5f6a3,
        0x4ec45e6782bad112, 0x1f3c6b40e4ebb654, 0x56ed233160784393, 0x51af64df2aa5fc55,
    ],
    // i = 36: ln(1 + 36/128)
    [
        0x3f7230dabc7c551a, 0xaa8cd86f29a59412, 0x40584455b22c817b, 0x165f74d56916ddaa,
        0xe9c83e0f6589e221, 0xc716725509140995, 0xc58402fb435a44c6, 0x63a59c53eb00ad03,
    ],
    // i = 37: ln(1 + 37/128)
    [
        0x41009652d341036b, 0x89ef42d7ee95e444, 0x7660cbc0efa11c83, 0x505da98548270514,
        0x2bcb4cfd6974da47, 0x86dcddc9b133b751, 0x86dfc9f0cff561d8, 0x7a4aaf895409c55c,
    ],
    // i = 38: ln(1 + 38/128)
    [
        0x428c9389ce438d7d, 0xcfde8061c030e28d, 0xe035afbe0972de36, 0xdde3a1dc7a329bfb,
        0x154ca7094166ef5c, 0xd18ef4d0bc5a554a, 0xc283489d5d032b5d, 0x5fdd4e11b593b0e7,
    ],
    // i = 39: ln(1 + 39/128)
    [
        0x44162fe6b92b5462, 0x7e82ad32cc73e14c, 0xe58b9bf13912b4d3, 0xe31965f62e0e2fd5,
        0xeb3fa702515ef682, 0x61dab337c40830ce, 0x2c0c163b9d09ded5, 0xd76ad167b5e7b48f,
    ],
    // i = 40: ln(1 + 40/128)
    [
        0x459d72aeae98380e, 0x731f55c41b8b823f, 0x067d04a43c19f534, 0xc3c8dc3995940f17,
        0x499727b2dc48152f, 0x8bc0169b4c529944, 0x85bd4ee8794371e8, 0xcfef83501638a398,
    ],
    // i = 41: ln(1 + 41/128)
    [
        0x47226305a667ebef, 0x1a39d500e3bbc33b, 0x882eeb5ecaf5d936, 0x4aacab7bb04fcaa5,
        0x99468d465f4ccf5a, 0xe412447ac91d35ce, 0x8e1fc408b6c78ecb, 0x06f89ca5a0a294d1,
    ],
    // i = 42: ln(1 + 42/128)
    [
        0x48a507ef3de59689, 0x0a14f69d750cbd2e, 0x9aad37a78762e747, 0xe27652fffbb65f90,
        0x030583695b634bb0, 0xc18a58e85648c138, 0x83ed51dda8306d3e, 0x13fb881e4f3def00,
    ],
    // i = 43: ln(1 + 43/128)
    [
        0x4a25684f7a1a8d7a, 0xd24c13f040e58b5a, 0x8eab2f9615eadf89, 0x9db59698d8b9a5b3,
        0x8bc0a13fd1fd3cd1, 0x37f84239db87f307, 0x48dad606b23188ec, 0xd5e2494ee769ec0e,
    ],
    // i = 44: ln(1 + 44/128)
    [
        0x4ba38aeb8474c270, 0xb3246a14206cf37b, 0x77ad6fb226f15213, 0x4cf267553164478e,
        0xf5fc616e20cd5936, 0x3f7d530e8d291024, 0x519f62aaff797e15, 0x53c8ac43a3830fa5,
    ],
    // i = 45: ln(1 + 45/128)
    [
        0x4d1f766a61f55359, 0x159d3fb73043dca2, 0x14b0167661deaff0, 0x7944fcf1ccdd5195,
        0x8bec4a7d589a72d3, 0x5ee0ecb5ae0ffe68, 0x0957c91755731574, 0x58defae2c2614cde,
    ],
    // i = 46: ln(1 + 46/128)
    [
        0x4e993155a517a71c, 0xbcd735d034237d6f, 0x479dcfc053c8dc26, 0x69bfc8cf9d61357a,
        0xaee32a4918383eba, 0x2ce6ff8dc01a5b18, 0xcd553bc96ae2a114, 0x5bae293400562cdb,
    ],
    // i = 47: ln(1 + 47/128)
    [
        0x5010c21a1a9f8ef4, 0x3049f7d319298564, 0x1827d9d91a2da0d4, 0xf2206c9599756243,
        0xc9dd6cfc3727a0cb, 0xf2e9de8134cdee5b, 0xe488f3969ce225ca, 0x187f46b1c62bfb2d,
    ],
    // i = 48: ln(1 + 48/128)
    [
        0x51862f08717b09f4, 0x2decdeccf1cd1057, 0x72cd24c00b44393c, 0xb5eeb55ca973fc98,
        0xaf120d6ebba85f7d, 0xb092567e72ff7a30, 0x14e48b957336c01f, 0x81891c558f613c57,
    ],
    // i = 49: ln(1 + 49/128)
    [
        0x52f97e55dde2836d, 0x326527dbf6191eb9, 0x53458673d2f053f5, 0x6b6568785b6423f7,
        0x973e059be66f28fb, 0x4dc65b36ab6cfc39, 0xb5f790cbfdccd96a, 0x031e755c364f586a,
    ],
    // i = 50: ln(1 + 50/128)
    [
        0x546ab61cb7e0b427, 0x24f5833eabc623a9, 0xe9e6af97f5c12be2, 0x1f9a5c5aeb0a988a,
        0x530626d4f28d4eb6, 0x59dd743353d7e4fb, 0x7cf05d1ac5bc69cd, 0x6656eb99698a8e93,
    ],
    // i = 51: ln(1 + 51/128)
    [
        0x55d9dc5d1569b152, 0x6adb283660bd00f8, 0xb83433193f7be028, 0x314796aaf884f564,
        0x8cdf71b2f128ae8a, 0xdaacd3be4d975abc, 0xf694717f32197790, 0x039642d18667d12d,
    ],
    // i = 52: ln(1 + 52/128)
    [
        0x5746f6fd60272942, 0x36383dc7fe1159f3, 0x80b4a6b429a4bb09, 0x4df9cbb7645143dc,
        0x3f984c404ca76681, 0xd1272b82f6d4b0e5, 0xe728a52cba2e3d16, 0xa0a230fbc3639743,
    ],
    // i = 53: ln(1 + 53/128)
    [
        0x58b20bcae71e54bd, 0xbd7c8a980728b9c8, 0x9b1577495fd12d40, 0x0b2333cf512b4182,
        0x8f0834da1cfcf075, 0x42a5195958ca07d9, 0xbc837911828e3253, 0x6a80098582541b8e,
    ],
    // i = 54: ln(1 + 54/128)
    [
        0x5a1b207a6c52bb11, 0x0af840538e1a592d, 0xeded1c3395996523, 0xfa9ae6166df3361f,
        0x47379cb4a4096771, 0x2db73e1e9dbdcdef, 0xce37213657d3ae92, 0xbf36d16f7083bbd4,
    ],
    // i = 55: ln(1 + 55/128)
    [
        0x5b823aa8ae878e30, 0x4e4c635c5f0bc0c5, 0xab9f4e6581f708d9, 0x856f669fbedf033a,
        0xfee3c8c70c449327, 0xd7723dcab20273f7, 0x603b642044bb4bc0, 0xdd2941c223ee0a2b,
    ],
    // i = 56: ln(1 + 56/128)
    [
        0x5ce75fdaef401a73, 0x89314feb4fbde5aa, 0xdde10dcea59757bb, 0xbc92784d23446f02,
        0x505d2dc14ac65d2a, 0xc49b7c7b9e14a268, 0xe0427ff797f25769, 0x1f632a2fb1351588,
    ],
    // i = 57: ln(1 + 57/128)
    [
        0x5e4a957f751e89f0, 0x57691fe9ed68159f, 0xc32ef1838fd7bd5e, 0xa6f5261c43109a88,
        0x5f81d74a44f4c2aa, 0x149cdf05075b1493, 0x576cf4843ac24dee, 0xbff221be9b875c17,
    ],
    // i = 58: ln(1 + 58/128)
    [
        0x5fabe0ee0abf0d92, 0xce979ed295043716, 0x0cbfcbf71ee8d4b3, 0xcd06766663c82c88,
        0xa53a25716f275bc2, 0xa865819e5a917809, 0x43dec3c772aed8b9, 0x0b07be72af30b4d9,
    ],
    // i = 59: ln(1 + 59/128)
    [
        0x610b47687a2c5d24, 0xec519784676688f0, 0x461471f380f95ed3, 0x2773d467406a94e2,
        0x1084e7da9a2e6f84, 0x41197957f8ba56fa, 0xaed557b35ae005be, 0x1d4c73df0747f86e,
    ],
    // i = 60: ln(1 + 60/128)
    [
        0x6268ce1b05096ad6, 0x9c620440f055b3ff, 0xc63281b40515a31f, 0x501f739cc6f53831,
        0x2fbbd96820267cbf, 0x29843ae0f0427892, 0x778b0d3873edae34, 0x507eaaddd94be1bd,
    ],
    // i = 61: ln(1 + 61/128)
    [
        0x63c47a1cd98b1df8, 0x5da755a61a29979c, 0xbfcbc0e45410ee8c, 0xa0d173fb95258bac,
        0xe79ccaf5ac124007, 0x2be40c0f729965bc, 0x82e96e5572ea875f, 0xf85983b7024507f1,
    ],
    // i = 62: ln(1 + 62/128)
    [
        0x651e5070845beae9, 0x337451f441baba92, 0x9cc25dca0fa1a7e3, 0x319e32cc3de7f064,
        0x8f4da6fa7f104da3, 0xc8d782d485cf0afd, 0x35ab3c5979119b15, 0x25b0797cd2b4ba9f,
    ],
    // i = 63: ln(1 + 63/128)
    [
        0x667656045f822b2e, 0xa4bbb11e0c6fdd25, 0xdb8e4afa251912da, 0xec7c7be13ffdd7f5,
        0x129be5cd5a75462f, 0xff4f6e881fc77988, 0xcfc3fac0244db6e1, 0xef36c7bbbd1d19ce,
    ],
    // i = 64: ln(1 + 64/128)
    [
        0x67cc8fb2fe612fca, 0xda35d9bd01488606, 0x7d20ffb34547d7c2, 0xb38ad78ec59e3b60,
        0xc2df0cb19edaebb7, 0xfadca437b8a073c4, 0x752d66d15d6f9b5d, 0xa7e09dc7febb0e3f,
    ],
    // i = 65: ln(1 + 65/128)
    [
        0x6921024396ec28af, 0xf29adc3ad3a4b273, 0xadea18d6c6bda28d, 0x03289542fc13c079,
        0xc15be7c756cb539a, 0x9faad02b111baed5, 0xd2abcb73e0205868, 0xfaeee8143ad738fe,
    ],
    // i = 66: ln(1 + 66/128)
    [
        0x6a73b26a68212635, 0x213fd4bc950d7be1, 0x1fc8ee26768c44e9, 0xf35aa69b763554ce,
        0xc08704e2adf8a19b, 0x2fb43fcd7df08a48, 0x871bbf43573447c1, 0xe875edb0181342cf,
    ],
    // i = 67: ln(1 + 67/128)
    [
        0x6bc4a4c91de1ac44, 0xce11285770a030e2, 0x6824be4383242af8, 0x84cbd5943cb06ae4,
        0x3d38c1421468b8c3, 0x731e5306483fe591, 0x2fa2777a98be79c0, 0x8fe97f1b1daeaf7f,
    ],
    // i = 68: ln(1 + 68/128)
    [
        0x6d13ddef323d8a32, 0xfbb6aba63878ef20, 0x53ab4d08603cf111, 0xaa8920b12b96a198,
        0xf528ac22e8c5ff87, 0x775c37c2725e6611, 0x0e4e7e63f8dfce5a, 0x777506394064e2d7,
    ],
    // i = 69: ln(1 + 69/128)
    [
        0x6e61625a4c43ed66, 0x3ec53e23bc39ef20, 0x73ab462020505b04, 0xc95f40096133b646,
        0xfc2b97f797b8243a, 0x0b479be1524e778b, 0x9cb28ef4b7cd15b4, 0x0d2b465186ae07d5,
    ],
    // i = 70: ln(1 + 70/128)
    [
        0x6fad36769c6defde, 0x1874deaef06b25b5, 0x2c1be100233b3294, 0x92f74d1ea905792e,
        0x4d17b0b18b728a55, 0x50b64bf2994646a8, 0x1210ab026cddd596, 0xa9f31cbc7b6da0b1,
    ],
    // i = 71: ln(1 + 71/128)
    [
        0x70f75e9f36b535ce, 0xcf052dea69b60bb5, 0x18e57d814099fe79, 0xd2bd6d07f0a1b552,
        0x9e8a6c59682717c8, 0x82649140a2533c60, 0x0c272ece98048347, 0xd7b83c6794468a54,
    ],
    // i = 72: ln(1 + 72/128)
    [
        0x723fdf1e6a6886b0, 0x97607bcbfee6892b, 0x8ecbd4e8235b8362, 0xe1e267eac97f8e8d,
        0x432551faf9ba7754, 0x62066c1da11bc8db, 0xd3f90b7f810e4f3e, 0xf0706129aeae65d4,
    ],
    // i = 73: ln(1 + 73/128)
    [
        0x7386bc2e17cfaded, 0xf4af2ab426749c43, 0x19180165ede56473, 0x30f2257a6940f2da,
        0xac982b713e4cab06, 0xf09f4cae5046a410, 0xbaaa4e9f0d5e87c6, 0x6ec32e265c1d0e27,
    ],
    // i = 74: ln(1 + 74/128)
    [
        0x74cbf9f803af5587, 0x7b232fafa36fd18a, 0xb4dff5efd6e583ff, 0x1279aed9025705ed,
        0xe48da1636915d53c, 0xe57cd3270abb7696, 0x2651580b90b72371, 0x17c86357efccd9a7,
    ],
    // i = 75: ln(1 + 75/128)
    [
        0x760f9c9628bcf941, 0x456e8bb25110ea50, 0x94cc182477ebd803, 0x50800d473363c7fc,
        0x5a74aeb924b62912, 0x188320b4e62627e5, 0x55e66b44ea7efd86, 0x0333ac1d2a826c1a,
    ],
    // i = 76: ln(1 + 76/128)
    [
        0x7751a813071282fb, 0x989a927476e1fe9f, 0x50684ce6bafcfd59, 0x250ff6995c94d3aa,
        0x2451e71d7d60fbbe, 0x8b63c7113e5b508f, 0x0f1e32ef4518e0fc, 0x43a3f55176a1ca55,
    ],
    // i = 77: ln(1 + 77/128)
    [
        0x78922069f1b09872, 0xf63d16552918d8a8, 0x07be2ec9c3da432c, 0x8750a8cacdd6a4f1,
        0x8b5ae70ce2671dcb, 0xf819a863d9a1ee03, 0xaf8088bb03e16c65, 0xdbddcce8c257dfed,
    ],
    // i = 78: ln(1 + 78/128)
    [
        0x79d109875a1e1f8d, 0xf68dbcf2ed1bb404, 0xa18e2aa5ee015120, 0xa956c38f1899206a,
        0xb2114303946cb64f, 0xb9a877bbee0ef38a, 0x19386ee60f3da399, 0xa9caba57d0dde8c5,
    ],
    // i = 79: ln(1 + 79/128)
    [
        0x7b0e67491a33005d, 0x73b94fcd4e5bfb08, 0x972fca0ebd8e5113, 0x999b100f22d5eb97,
        0xee62d1041a908802, 0x64bf71efc45b6ee0, 0xdd6e9f6491996ce0, 0x47cd2a969d4179e1,
    ],
    // i = 80: ln(1 + 80/128)
    [
        0x7c4a3d7ebc1bb2cd, 0x720ec44c73d75cf5, 0x649117429ec747b1, 0xea5ce16b9dfd6268,
        0xc07f81b3669c3df9, 0x9cd3cbbb0a0ba86f, 0xbda7391f3bffd807, 0x9727ebe75906267b,
    ],
    // i = 81: ln(1 + 81/128)
    [
        0x7d848fe9c0a2b185, 0x15b0f2db34148654, 0x4829981609381f6e, 0x769bb433829c25b6,
        0x9ccd0b6bbddb7177, 0x4866a3442840a0bf, 0x6093422f2bc13395, 0x2f01653d8abec40d,
    ],
    // i = 82: ln(1 + 82/128)
    [
        0x7ebd623de3cc7b66, 0xbecf93aa1afec6d4, 0xcde2ef184dc7b6e6, 0x34ba102efa53d65d,
        0xeb29d0b0592550d9, 0xbcc34caa1ce07db2, 0x6fb9d4a839ca9988, 0x4827b3e4ed8fd682,
    ],
    // i = 83: ln(1 + 83/128)
    [
        0x7ff4b8215fd26156, 0x5f40d9321af246e3, 0x379d3ea68e29866b, 0x3b38ae3b1790e838,
        0xeee7b8f973b2b50d, 0xf921e3451fc312eb, 0x8a334b0f383503a1, 0x12704f769d15cc1e,
    ],
    // i = 84: ln(1 + 84/128)
    [
        0x812a952d2e87f634, 0xe34aebf73ffe346e, 0x4b8b8c4c34ebb89e, 0xa25591cfd7258b51,
        0x0ba664483605037f, 0xe2af09cf0c759abe, 0x3a732eb6e89d878e, 0x9406276067a46987,
    ],
    // i = 85: ln(1 + 85/128)
    [
        0x825efced4936932f, 0xe60804593bed4da1, 0x1c88e1e218e0a7e0, 0x9e3bf732eeafe183,
        0xb21e3f7c16f3e26d, 0xf203975363f372ff, 0xec760e66fd9b2fd0, 0xf04505f94136900c,
    ],
    // i = 86: ln(1 + 86/128)
    [
        0x8391f2e0e6fa0272, 0xbcb1c488b755b2b7, 0xa5d75211210f75ce, 0x80a11439aa7c2a28,
        0x297156dc20e6ea98, 0x23989734184fb062, 0x690afdf2e81a013e, 0x76def4c853b65adc,
    ],
    // i = 87: ln(1 + 87/128)
    [
        0x84c37a7ab9a905c8, 0xfed4a7fa1fe03811, 0x3f135a26389f13c4, 0xbde39b4a96240ed5,
        0x978f0a6b9daa94e0, 0x7080891d5db6f492, 0x3b9be86ac000a5b4, 0xcc00dcd87ada428f,
    ],
    // i = 88: ln(1 + 88/128)
    [
        0x85f39721295415b4, 0xc4bdd99effe69b64, 0x366fbbf35d3ed11a, 0x90936f50c52fb7f6,
        0x60e4aff46ea5168f, 0x9b0099abdee7403c, 0x7259863e5716b0d4, 0xd04a9e2eeac77298,
    ],
    // i = 89: ln(1 + 89/128)
    [
        0x87224c2e8e645fb7, 0x572ef4b4b1f1a3f7, 0x59ee145b430bd090, 0xb3c6baddf9cabf0a,
        0x50cba9e17ba5461a, 0x9401a2c5809d44d5, 0xcc6ff342f24b352a, 0xb28d415bd95cf419,
    ],
    // i = 90: ln(1 + 90/128)
    [
        0x884f9cf16a64b7ef, 0x1f64d85bc8c5f241, 0x63e6f9907e4ae138, 0xa2072c7e945a0a58,
        0x2e64de1d9f62ab2c, 0xf02ede9f3b889e3b, 0xd1d2fd21ed9b187a, 0xe5b1269d0eb07925,
    ],
    // i = 91: ln(1 + 91/128)
    [
        0x897b8cac9f7de298, 0x0918ce3e86a5a24e, 0xc9d5fd4048cde6bb, 0x3451ee1551b63a9a,
        0xd9f2a988779f7757, 0xcf0146bde1370c8f, 0x7967d0532922d148, 0xabcee12246e32681,
    ],
    // i = 92: ln(1 + 92/128)
    [
        0x8aa61e97a6af4d4c, 0x799d1cb2f14054ed, 0x3a330f341cf1faee, 0x26dfe9520e33c3df,
        0x50a4b66c38859b27, 0xe1958c8d438d5e9d, 0xfee1115533bde7be, 0xf9c14cea66b86f42,
    ],
    // i = 93: ln(1 + 93/128)
    [
        0x8bcf55dec4cd05fe, 0x30737d03e970d58e, 0x37d86476147c6d48, 0x5be2007634f3fab2,
        0x21f25c1f45224e00, 0x2d5aee948fc6853a, 0x5798053d23a91da6, 0x32eb4370d0ece291,
    ],
    // i = 94: ln(1 + 94/128)
    [
        0x8cf735a33e4b7662, 0xe5eebbc0ef3d5710, 0x78ea06c2c371d36f, 0xe98ec9b5a3ef0ea2,
        0x80ce3afe66f272b7, 0xde764d2def6da3e9, 0xe29dd595d7aac1ac, 0xef9a8ef1c2eb376c,
    ],
    // i = 95: ln(1 + 95/128)
    [
        0x8e1dc0fb89e125e4, 0xa7c766fde2efc77f, 0x4c2379b2ef8dce37, 0x815595258a493f54,
        0x411af4cc02e8f0cc, 0x4eccce8c7dbcefc9, 0xb660ecca6dfa8df5, 0x13c9d868a482791d,
    ],
    // i = 96: ln(1 + 96/128)
    [
        0x8f42faf3820681ef, 0x62cd2f9f1e35f2e7, 0xca4f4817696ad39f, 0x9a4b1c065ba0cde2,
        0x6e709121ab58d60f, 0xe678c55edeac4090, 0xfdbe964cdd0bf7cf, 0x4f6620b128e74d7e,
    ],
    // i = 97: ln(1 + 97/128)
    [
        0x9066e68c955b6c9a, 0x81e87badfd849e89, 0x481a91283b527cba, 0xbeeaffacc9110b22,
        0xe12af53dc984a22c, 0x022a6191c7629553, 0xd1252aec7ab564b6, 0x18da61909abaca2d,
    ],
    // i = 98: ln(1 + 98/128)
    [
        0x918986bdf5fa1416, 0xf1b439165240a471, 0xbcdfcc1f5b0c6c60, 0x5a9f09308150f4a5,
        0xf29881dc53349bf8, 0x37e3a91620b70553, 0x228fec0cd9225675, 0x4656306744f5ae8c,
    ],
    // i = 99: ln(1 + 99/128)
    [
        0x92aade74c7be59e0, 0x21d6d6881e710847, 0x50a06eb301ae8308, 0xfeca10f43894e474,
        0x72804429ac221819, 0x3a28cb9e1c66423a, 0xd3e059e88607f720, 0x9003f45b0075384d,
    ],
    // i = 100: ln(1 + 100/128)
    [
        0x93caf0944d88d75b, 0xc1f9edcb438ffc03, 0x527d7309433bbdf4, 0x7437d6659ec6647e,
        0xb09a0aaea10dfdb1, 0x92b0f0fd6de19a53, 0xc0dc1d6b15fa0ed3, 0x5558e6affa1895f4,
    ],
    // i = 101: ln(1 + 101/128)
    [
        0x94e9bff615845642, 0xe6b65d2e67db5d0c, 0xfc1f55966a10aa67, 0x33a48e4f1d0d3dfd,
        0x53a0d1b8e0814130, 0x0c7b750cb25cde63, 0x36d6e47d44803285, 0xfa880bc2c23e9c20,
    ],
    // i = 102: ln(1 + 102/128)
    [
        0x96074f6a24745dcb, 0xd4e18dd14f312a40, 0xa546f842b745196d, 0x2d83ac4288043648,
        0xf1efd6bec7a398d4, 0xf59eb28a6ea286d6, 0xca3f05b758797f08, 0x979b5ac4888c4872,
    ],
    // i = 103: ln(1 + 103/128)
    [
        0x9723a1b720134202, 0xa10c34910d589296, 0x794a2964475e2e71, 0x79b791963f080baf,
        0xf8a9352197f074ad, 0x3c526d19bf521374, 0x9aa1da7dec7a3208, 0x51789fa5a599dff0,
    ],
    // i = 104: ln(1 + 104/128)
    [
        0x983eb99a7885f0fd, 0xac850fab36cdee18, 0x0b7013338119ba91, 0x4042089c636df445,
        0xd3bc93b7e748ff9a, 0x879fae5152740265, 0x4556832dceab26fa, 0xdb24c6951304d6c1,
    ],
    // i = 105: ln(1 + 105/128)
    [
        0x995899c890eb8990, 0x2ab5b3d916b06715, 0xba133462ddf94bde, 0x6b3a547a56157af9,
        0xd14142a8246215d1, 0xa6b569febc7ef3d3, 0x0dc0b96c57cb315a, 0x8297bef5a5640a3c,
    ],
    // i = 106: ln(1 + 106/128)
    [
        0x9a7144ece70e98b7, 0x5c96c42e72757253, 0x1ddfd382b6be4109, 0xc765792d9d8edefe,
        0x5e8524f6366668d1, 0x3cf7c12f305274e7, 0xbad3588c35a6ed7e, 0xbf91ec4e45128ad4,
    ],
    // i = 107: ln(1 + 107/128)
    [
        0x9b88bdaa3a3dae2e, 0xe8124226efc8f895, 0x8d986c2816c364d0, 0xc110a7922bb4ff77,
        0xd14e82659d03b869, 0x5a8770efc0d05d00, 0x618792f83474d5d3, 0xc8b6db72b0a314a7,
    ],
    // i = 108: ln(1 + 108/128)
    [
        0x9c9f069ab150cd4e, 0x221301b6f8c38f62, 0x1717c9e700413260, 0x41e7a8452170e2c2,
        0xbc176f0ab57fe9db, 0xa87f09fa3dc6a386, 0x2df8d83061955f50, 0x829512bd48fe0250,
    ],
    // i = 109: ln(1 + 109/128)
    [
        0x9db4224fffe1157c, 0x76f60c2c9b341d6d, 0xe6d9b9591a54790d, 0x29adc2b4c90a2c44,
        0x880cc7924c9cf538, 0xb42d427939c54415, 0x2a5f91d4ca04f4bb, 0xe34b57697bd85e3d,
    ],
    // i = 110: ln(1 + 110/128)
    [
        0x9ec813538ab7d520, 0x2131e85693cf6b80, 0x9d96954adf1ff936, 0x0bd03b10f297662b,
        0xcfe36b8d89dee616, 0x76ffe83864671d5b, 0x97af626ac4b53d6d, 0xeb29783aa0ce0994,
    ],
    // i = 111: ln(1 + 111/128)
    [
        0x9fdadc268b7a12da, 0x74ea82e55dde6c84, 0xecf33acb4b72b4f9, 0x71168dc1bba84ce8,
        0xd8c6dbf64f170359, 0xed2d7b5ac5cd1a0d, 0x2e916e2d045b8bbc, 0x9d4d0b6b6fa22492,
    ],
    // i = 112: ln(1 + 112/128)
    [
        0xa0ec7f4233957323, 0x25e617a300bbca9c, 0x4486ea2756f59974, 0x247c0b842a5e02a7,
        0x6471b5af1bb82762, 0x2bdfda46892e5832, 0x5f29ec911df6c2fd, 0x2018ce5cd6124129,
    ],
    // i = 113: ln(1 + 113/128)
    [
        0xa1fcff17ce733bd3, 0x93dcdb0770cb6c1b, 0xb774c2fe7ce6611a, 0xe23ae16a76d75442,
        0x0a091231751d317a, 0x72e33343a3bb3481, 0x4995554ceafb93f5, 0x48f0123e82f9c9e0,
    ],
    // i = 114: ln(1 + 114/128)
    [
        0xa30c5e10e2f613e8, 0x5bd9bd99e39a20ae, 0xe59a498016887279, 0x6bdd6ab952e7f931,
        0x5e241add7750befb, 0x6124acfce5fef460, 0x29c9172ae66d803f, 0x031238ab1ec278af,
    ],
    // i = 115: ln(1 + 115/128)
    [
        0xa41a9e8f5446fb9e, 0xaf45d980fe84b0c1, 0xefbe78337535ca72, 0x6d9c0712c4c1348b,
        0xfeea53373e6f4167, 0x3b248f20052e0cb4, 0x6f85a5ab50bdc64b, 0xf8b49e95d6d3d6f1,
    ],
    // i = 116: ln(1 + 116/128)
    [
        0xa527c2ed81f5d811, 0x3dfa3d3761b6316e, 0x6f7191d8af47e744, 0x5bf1a66c84ebc206,
        0x23bd3235db555408, 0x322aec8e445c1b43, 0xd83cab84a883d1a7, 0x5c9fdf23369cb411,
    ],
    // i = 117: ln(1 + 117/128)
    [
        0xa633cd7e6771cd8b, 0x4766e98c37ec33b6, 0x1b11377c71eab2c3, 0x1b7a54a6905668df,
        0x96bb552065a33b31, 0xa85f6dd142ec4a7e, 0xf84b0423b966f5f9, 0xefad36ce17bc15c2,
    ],
    // i = 118: ln(1 + 118/128)
    [
        0xa73ec08dbadd84e5, 0x84c2b22c2aee1a18, 0xbd794408f774593d, 0xc9ea4c642eb5190b,
        0xaca74ac10464cdd9, 0xc1f3168cc1b47d5a, 0x3ab169cca0c9e024, 0x0b863a1be9bbbb42,
    ],
    // i = 119: ln(1 + 119/128)
    [
        0xa8489e600b435a5e, 0x59d2d85ab61ed2f2, 0x39ed8a989cbb2de3, 0xab09e04277258b86,
        0xae3a7fb068cf4ff3, 0x34a81880bf4cceff, 0x0955efb8f48a4b7d, 0x44a034cf5463ae30,
    ],
    // i = 120: ln(1 + 120/128)
    [
        0xa9516932de2d5773, 0xbe4578ad97aea7be, 0xd0920f6a4c39b31e, 0xa388b63329d4eb53,
        0xca138ee03e381ca3, 0x031e3061eceb1f55, 0xbbe00b2bd6775e9f, 0x8a7e5bd3c1df5ebf,
    ],
    // i = 121: ln(1 + 121/128)
    [
        0xaa59233ccca4bd48, 0xaa145a1ec1796894, 0x5d56af714ebab5f9, 0x916e796b3fd0d75b,
        0xd82bb3bae041db14, 0xcc6b990874fac90f, 0x37b0af6eba72c6bb, 0x07bdebd9b44ebf27,
    ],
    // i = 122: ln(1 + 122/128)
    [
        0xab5fcead9f9cca08, 0xe310b9b1fe59cdc1, 0x5631bf5c35094514, 0x52d39be02e3f55d3,
        0xe4b7faf87697b2fe, 0x9309a22c71a9ad49, 0xbdf5913f419576de, 0x68a891be860598be,
    ],
    // i = 123: ln(1 + 123/128)
    [
        0xac656dae6bcc4984, 0x9792ec984585513c, 0x601ab2b5c446c7b7, 0xcefc72f56848f351,
        0xcbf0d84890272b07, 0xdbe424b03754421a, 0x9f7e13a3a2cbcafc, 0x800743a312c4fabd,
    ],
    // i = 124: ln(1 + 124/128)
    [
        0xad6a0261acf967d9, 0x4d552f811cd40845, 0x839e04578161ccf7, 0x7753b3c85b324a78,
        0x0c7634647b2300e7, 0x869cbad304f30d08, 0xfaeab5b9d6b30d46, 0x77d0211814f3b1d7,
    ],
    // i = 125: ln(1 + 125/128)
    [
        0xae6d8ee360bb2467, 0xb71e2eb8418af602, 0x50ae328eb0db90f8, 0x72812da9ccb86b9a,
        0xff6f3b30066ebca8, 0x752dd2fa11141c98, 0xf5270b8d0b291788, 0xa0ec4685409651e0,
    ],
    // i = 126: ln(1 + 126/128)
    [
        0xaf70154920b3ab86, 0xb04afe92103ef4c6, 0x29f04ae4e7a29309, 0xe668810251d2f00f,
        0x5f3cbd97c523dc46, 0x46a4f0822036cccd, 0x486c32a24e559a75, 0x6502ee166e5357ef,
    ],
    // i = 127: ln(1 + 127/128)
    [
        0xb07197a23c46c653, 0xe44ad05a76554335, 0x17ce375accaabf0a, 0x96012a8ec1549af0,
        0xc5e4901afa3e3768, 0xbc66fd200ee934fc, 0xf91ab8af05a0089b, 0xbbdc25e64df8fd3f,
    ],
    // i = 128: ln(1 + 128/128)
    [
        0xb17217f7d1cf79ab, 0xc9e3b39803f2f6af, 0x40f343267298b62d, 0x8a0d175b8baafa2b,
        0xe7b876206debac98, 0x559552fb4afa1b10, 0xed2eae35c1382144, 0x27573b291169b825,
    ],
];

use crate::int::types::traits::BigInt;

/// `ln(1 + idx/M)` at working scale `w`, read from the narrow prefix
/// table into the work integer `W`.
///
/// The reconstruction lives ONCE, in
/// [`crate::algos::support::ln_tang_slot::ln_table_entry_from_slot`];
/// this wrapper only names which slot to read. `idx = 0` is `ln 1 = 0`.
///
/// # Panics
///
/// If `w` demands more than [`LN_TANG_NARROW_LIMBS`] limbs of slot —
/// the validity wall bounding this table against the narrow rung's
/// reach. A silently truncated slot would yield wrong digits.
#[inline]
pub(crate) fn ln_table_entry_narrow<W: BigInt>(w: u32, idx: usize, pow10_w: W) -> W {
    if idx == 0 {
        return W::ZERO;
    }
    crate::algos::support::ln_tang_slot::ln_table_entry_from_slot::<W>(
        w,
        &LN_TANG_SLOTS_NARROW[idx],
        pow10_w,
    )
}

