//! Shared support kernels consumed across the algorithm families.
//!
//! Unlike the per-family trees (`algos::sqrt`, `algos::ln`, …) these are
//! not tied to one mathematical family; they are the cross-cutting
//! building blocks the families and the arithmetic layer share:
//!
//! - [`mg_divide`] — the Moller-Granlund magic-number divide used by
//!   every multiplicative `÷ 10^SCALE` rescale path.
//! - [`fixed`] — the 256-bit sign-magnitude `Fixed` work integer the
//!   strict-transcendental fallback paths evaluate their series in.
//! - [`newton_reciprocal`] — the Newton-Raphson reciprocal divide for
//!   `n / 10^SCALE` at the wide tiers, head-to-head benched against
//!   [`mg_divide::div_wide_pow10_chain`] and routed in by
//!   [`newton_reciprocal::dispatch_wide_pow10`] at the cells where
//!   the bench matrix shows it wins.

pub(crate) mod fixed;
pub(crate) mod mg_divide;

// Typed-`W` Newton-root seed bridge over the cross-algorithm seed leaf
// (`algo_x_support::seed`). Used by the wide fixed-point `sqrt` kernel,
// which needs the over-estimate seed (not the final floor root) to start
// its own scaled Newton loop. The floor-root surface itself is
// `W::isqrt` / `W::icbrt`.
pub(crate) mod seed_bridge;

// Tier-generic surface over the per-tier wide guard-digit cores. The
// `WideTrigCore` trait + six `*_series` functions collapse the 60
// per-tier `*_strict_<tier>` wrappers in `algos::{exp,ln,trig}::wide_kernel`
// to one generic function per transcendental. Always compiled; the
// per-tier `impl WideTrigCore` blocks are emitted by
// `decl_wide_transcendental!`.
pub(crate) mod wide_trig_core;

// Baked binary Tang `ln(1 + i/M)` lookup table (`M = 128`) + the
// width-generic accessor that slices a slot to the tier's needed binary
// precision and reconstructs `round(ln(1+i/M) · 10^w)` at working scale
// `w`. Replaces the per-call `ln_fixed` Series recompute in the wide
// `ln` Tang kernel. Generated by `scripts/gen_ln_tang_table.py` (mpmath
// oracle), committed, NOT built at build time (`build.rs` untouched).
// Gated to `_wide-support`: only the wide tiers (D57..D1232) carry the
// Tang `ln` path; the narrow tiers (D18/D38) never reach it.
#[cfg(feature = "_wide-support")]
pub(crate) mod ln_tang_table;

// Baked binary Tang `(sin(c_j), cos(c_j))` lookup table (`M = 512`) + the
// width-generic accessor that slices each component to the tier's needed
// binary precision and reconstructs `round(value · 10^w)` at working
// scale `w`. Replaces the per-call `sin_cos_fixed` Series recompute in
// the wide trig Tang kernel. Generated by
// `scripts/gen_sincos_tang_table.py` (mpmath oracle), committed, NOT
// built at build time (`build.rs` untouched). Gated to `_wide-support`:
// only the wide tiers carry the Tang trig path; the narrow tiers
// (D18/D38) never reach it.
#[cfg(feature = "_wide-support")]
pub(crate) mod sincos_tang_table;
// Baked binary Tang `exp(j · ln2 / M)` lookup table (single `M = 512`
// table; the `M = 128` tier D57 reads index `4·j`) + the width-generic
// accessor that slices a slot to the tier's needed binary precision and
// reconstructs `round(exp(j·ln2/M) · 10^w)` at working scale `w`.
// Replaces the per-call `exp_fixed` Series recompute in the wide `exp`
// Tang kernel. Each slot stores the FRACTIONAL part `exp(j·ln2/M) − 1`
// (a pure fraction, like the ln pilot); the integer `1` is re-added at
// convert time. Generated by `scripts/gen_exp_tang_table.py` (mpmath
// oracle), committed, NOT built at build time (`build.rs` untouched).
// Gated to `_wide-support`: only the wide tiers (D57..D1232) carry the
// Tang `exp` path; the narrow tiers (D18/D38) never reach it.
#[cfg(feature = "_wide-support")]
pub(crate) mod exp_tang_table;

// Newton-Raphson reciprocal divide for `n / 10^SCALE` at the wide tiers.
// Always compiled: the unified `decl_decimal_arithmetic!` mul/div path
// used by D18/D38 (default features) references the dispatcher in a
// const-folded `SCALE > 38` branch — dead for the narrow tiers but still
// type-checked. The kernels are generic over `Int<N>`, so this adds
// compile time, not a feature.
pub(crate) mod newton_reciprocal;
