"""Generate the baked binary Tang `ln(1 + i/M)` lookup table.

This is a ONE-OFF hand-run generator (a sibling of
`gen_const_table.py` / `gen_golden_precision.py`). It is NOT run at build
time: it emits a committed Rust source file
`src/algos/support/ln_tang_table.rs`, and that output is what the crate
compiles. `build.rs` is untouched.

## What it stores

The wide `ln` kernel (`algos::ln::ln_tang`) uses Tang's table-driven
reduction with `M = LN_TANG_M = 128`: it indexes `L_i = ln(1 + i/M)` for
`i in 0..=M`. The previous accessor recomputed `L_i` per call by running
a full `ln_fixed` Series at the working scale — the dominant cost of the
wide-`ln` regression. This table bakes `L_i` ONCE (oracle, mpmath) so the
per-call cost collapses to one multiply + one shift.

## Storage — binary fixed-point, MS-limb-first

Every slot `L_i = ln(1 + i/M)` lies in `[0, ln 2] ⊂ [0, 1)`, so it is a
pure fraction. We store the correctly-rounded binary fixed-point

    slot_i = round(L_i · 2^B)          (an unsigned B-bit integer)

as a fixed-length little-endian `[u64; LIMBS]` array, but emitted
**most-significant limb first** within the entry so that a narrower tier
can read a contiguous HIGH-limb PREFIX (a free slice) and the widest tier
reads the whole entry. `B` is sized for the WIDEST enabled tier's maximum
working scale (D1232: working scale capped at `W::BITS/8 = 2048` decimal
digits) plus generous guard bits, so the slice→convert reconstruction is
correctly rounded at every tier.

    i = 0   -> L_0 = ln(1)   = 0      (stored as all-zero)
    i = M   -> L_M = ln(2)            (the largest slot, < 1)

## How the accessor consumes it

At call time, for working scale `w`, the accessor reconstructs

    round(L_i · 10^w) ≈ round(slot_i · 10^w / 2^B)
                      = (slot_i · 10^w + 2^(B-1)) >> B

in the tier's work integer `W`. One multiply + one add + one shift —
far less than the Series it replaces. The binary store is exact to
`2^-(B+1)`; scaled by `10^w` (w ≤ 2048) that absolute error is
`≤ 10^w · 2^-(B+1)`, and with `B` chosen so `2^B >> 2·10^w` the converted
slot is correctly rounded at scale `w` (the guard bits sit far below the
working ULP, and the artanh reconstruction re-rounds with GUARD digits +
Ziv on top).
"""

from __future__ import annotations

import datetime
from mpmath import mp, mpf, log, floor as mpfloor

# ── Tang table size (do NOT change here; the M-sweep is a separate task) ─
M = 128

# ── Binary precision of the baked entry ──────────────────────────────────
#
# The widest enabled tier is D1232: work integer W = Int<256> = 16384
# bits. The wide-`ln` directed/nearest narrowing caps the working scale
# `w` at `W::BITS / 8` DECIMAL digits (see
# `round_to_storage_directed_impl`'s `cap_digits`), i.e. 2048 digits for
# D1232 — the deepest L_i precision any call can demand.
#
#   need_bits = w_max · log2(10) = 2048 · 3.32193 ≈ 6803 bits
#
# We add generous guard bits and round B up to a u64-limb multiple so the
# converted slot is correctly rounded at every working scale, and so the
# conversion arithmetic `slot · 10^w` (≈ B + 6803 bits) fits inside W
# (16384 bits) with comfortable headroom.
W_MAX_DECIMAL = 2048          # D1232 working-scale cap = Int<256>::BITS / 8
B_LIMBS = 112                 # 112 · 64 = 7168 bits
B = B_LIMBS * 64              # = 7168; guard ≈ 7168 − 6803 = 365 bits ≈ 110 dec digits

# ── Oracle precision ──────────────────────────────────────────────────────
# B bits ≈ B/3.32193 ≈ 2158 decimal digits of value; add wide margin so
# round(L_i · 2^B) is exact.
mp.dps = 2600


def slot_limbs_msb_first(i: int):
    """Return the B-bit `round(ln(1+i/M) · 2^B)` as a fixed-length
    `[u64; B_LIMBS]` little-endian magnitude, emitted MOST-SIGNIFICANT
    limb first (so a narrow tier reads a high-limb prefix)."""
    if i == 0:
        # ln(1) = 0 exactly.
        n = 0
    else:
        val = log(mpf(1) + mpf(i) / mpf(M))   # ln(1 + i/M), in (0, ln2]
        scaled = val * (mpf(2) ** B)
        # round-half-to-even is irrelevant here (irrational, no tie); use
        # round-half-up via floor(scaled + 1/2). The values are all < 2^B
        # (since L_i < 1), so n fits in B bits.
        n = int(mpfloor(scaled + mpf("0.5")))
        assert 0 <= n < (1 << B), f"slot {i} out of B-bit range"
    # little-endian limbs, zero-padded to exactly B_LIMBS.
    le = []
    x = n
    for _ in range(B_LIMBS):
        le.append(x & 0xFFFFFFFFFFFFFFFF)
        x >>= 64
    assert x == 0, f"slot {i} exceeds {B_LIMBS} limbs"
    # emit MS-limb first.
    return list(reversed(le))


def main():
    out = []
    w = out.append

    w("// SPDX-FileCopyrightText: 2026 John Moxley")
    w("// SPDX-License-Identifier: MIT OR Apache-2.0")
    w("")
    w("//! Baked binary Tang `ln(1 + i/M)` lookup table (`M = 128`).")
    w("//!")
    w("//! GENERATED by `scripts/gen_ln_tang_table.py` (mpmath oracle). Do")
    w("//! NOT edit by hand; re-run the script and commit its output. This")
    w("//! file is NOT produced at build time — `build.rs` is untouched.")
    w("//!")
    w("//! Each of the `M + 1 = 129` slots holds the natural log")
    w("//! `L_i = ln(1 + i/128)` (`i ∈ [0, 128]`, all in `[0, ln 2] ⊂ [0,")
    w("//! 1)`) as a correctly-rounded BINARY fixed-point value")
    w(f"//! `round(L_i · 2^{B})` — a `B = {B}`-bit unsigned magnitude stored as a")
    w(f"//! fixed-length `[u64; {B_LIMBS}]` little-endian array, but laid out")
    w("//! **most-significant limb first** within the entry. A narrower")
    w("//! tier reads a contiguous HIGH-limb PREFIX (a free slice); the")
    w("//! widest tier (D1232) reads the whole entry. The `i = 0` slot is")
    w("//! `ln(1) = 0` (all-zero); the `i = 128` slot is `ln 2`.")
    w("//!")
    w(f"//! `B = {B}` is sized for the widest enabled tier's max working scale")
    w(f"//! (D1232: `W = Int<256>`, working scale capped at `W::BITS/8 =")
    w(f"//! {W_MAX_DECIMAL}` decimal digits ≈ {W_MAX_DECIMAL * 332193 // 100000} bits) PLUS guard bits, so")
    w("//! the slice→convert reconstruction `round(slot · 10^w / 2^B)` is")
    w("//! correctly rounded at every tier and the conversion product")
    w("//! `slot · 10^w` fits inside `W`.")
    w("")
    w("/// Tang table size — `ln(1 + i/M)`, `i ∈ [0, M]`. Matches")
    w("/// `LN_TANG_M` in `macros::wide_transcendental`. The M-sweep is a")
    w("/// separate task; do NOT change this here.")
    w(f"pub(crate) const LN_TANG_M: u32 = {M};")
    w("")
    w("/// Binary fixed-point exponent: each slot is `round(ln(1+i/M) ·")
    w(f"/// 2^B)`. `B = {B}` bits = `{B_LIMBS}` u64 limbs.")
    w(f"pub(crate) const LN_TANG_B: u32 = {B};")
    w("")
    w("/// Number of u64 limbs per stored slot (`B / 64`).")
    w(f"pub(crate) const LN_TANG_LIMBS: usize = {B_LIMBS};")
    w("")
    w("/// The `M + 1` baked slots `round(ln(1+i/M) · 2^B)`, each a")
    w(f"/// `[u64; {B_LIMBS}]` little-endian magnitude emitted MOST-SIGNIFICANT")
    w("/// limb FIRST (so a narrow tier reads a high-limb prefix). Index by")
    w("/// `i ∈ [0, 128]`.")
    w(f"pub(crate) static LN_TANG_SLOTS: [[u64; {B_LIMBS}]; {M + 1}] = [")
    for i in range(M + 1):
        limbs = slot_limbs_msb_first(i)
        # one slot per line group; chunk the limbs across lines for
        # readability (4 limbs per line).
        w(f"    // i = {i}: ln(1 + {i}/{M})")
        w("    [")
        for j in range(0, B_LIMBS, 4):
            chunk = limbs[j:j + 4]
            chunk_str = ", ".join(f"0x{l:016x}" for l in chunk)
            w(f"        {chunk_str},")
        w("    ],")
    w("];")
    w("")

    # ── Width-generic accessor ────────────────────────────────────────────
    w("use crate::int::types::traits::BigInt;")
    w("")
    w("/// `ln(1 + idx/M)` reconstructed at working scale `w` (`idx ∈ [0,")
    w("/// M]`) in the tier's work integer `W` (a value `x` held as `x ·")
    w("/// 10^w`). Replaces the per-call `ln_fixed` Series recompute.")
    w("///")
    w("/// The slot is stored as `slot = round(L_idx · 2^B)` (B = LN_TANG_B,")
    w("/// MS-limb first). We SLICE the high-order `p` limbs needed for this")
    w("/// working scale — `slot_hi = floor(slot / 2^(B − 64·p))`, the binary")
    w("/// fixed-point of `L_idx` at exponent `bp = 64·p` — then reconstruct")
    w("///")
    w("///     round(L_idx · 10^w) = round(slot_hi · 10^w / 2^bp)")
    w("///                         = (slot_hi · 10^w + 2^(bp−1)) >> bp")
    w("///")
    w("/// entirely in `W`: one zero-extend, one multiply, one add, one")
    w("/// shift. `p` is chosen so `bp` carries the working scale's bits plus")
    w("/// generous guard, and so the product `slot_hi · 10^w` (≈ bp + w·")
    w("/// log2(10) bits ≈ 6.6·w bits, with w ≤ W::BITS/8) fits `W`.")
    w("///")
    w("/// `idx = 0` short-circuits to `0` (ln 1). The MS-limb-first layout")
    w("/// makes the slice a contiguous high-limb PREFIX: a narrow tier reads")
    w("/// fewer limbs, the widest tier reads the whole entry.")
    w("#[inline]")
    w("pub(crate) fn ln_table_entry_baked<W: BigInt>(w: u32, idx: usize) -> W {")
    w("    if idx == 0 {")
    w("        return W::ZERO;")
    w("    }")
    w("    let slot = &LN_TANG_SLOTS[idx];")
    w("    // Binary precision needed: w·log2(10) value bits + guard. Use the")
    w("    // rational 3322/1000 ≈ log2(10) (a slight over-estimate) and a")
    w("    // 64-bit (one-limb) guard so the converted slot rounds correctly")
    w("    // yet the conversion product `slot_hi · 10^w` (≈ bp + w·log2(10)")
    w("    // ≈ 2·w·log2(10) + 64 ≈ 0.83·W::BITS + 64 at the `w = W::BITS/8`")
    w("    // cap) stays inside `W` even on the narrowest work integer")
    w("    // (Int<16> = 1024 bits: 0.83·1024 + 64 ≈ 914 < 1024). Round the")
    w("    // limb count up; clamp to the stored width.")
    w("    let need_bits = (w as u64) * 3322 / 1000 + 64;")
    w("    let mut p = need_bits.div_ceil(64) as usize;")
    w("    p = p.clamp(1, LN_TANG_LIMBS);")
    w("    // Zero-extend the top `p` limbs (MS-first) into W:")
    w("    //   slot_hi = sum_{k=0..p-1} slot[k] · 2^(64·(p−1−k)).")
    w("    let mut slot_hi = W::ZERO;")
    w("    for s in slot.iter().take(p) {")
    w("        slot_hi = (slot_hi << 64)")
    w("            | W::from_mag_sign_u128(&[*s as u128], false);")
    w("    }")
    w("    let bp = (64 * p) as u32;")
    w("    // pow10(w) in W.")
    w("    let pow10_w = W::TEN.pow(w);")
    w("    let scaled = slot_hi * pow10_w;")
    w("    // Round-half-up: add 2^(bp−1), then shift right by bp.")
    w("    let bias = W::ONE << (bp - 1);")
    w("    (scaled + bias) >> bp")
    w("}")
    w("")

    src = "\n".join(out) + "\n"
    path = "src/algos/support/ln_tang_table.rs"
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)
    print(f"wrote {path} ({len(src)} bytes), B={B} ({B_LIMBS} limbs), "
          f"mp.dps={mp.dps}, M={M}, {datetime.date.today()}")


if __name__ == "__main__":
    main()
