"""Emit the Rust band-edge golden wiring block for ulp_strict_golden.rs.

Scans tests/golden/ for the per-tier {0, capacity-1} band-edge tables and
prints one `#[test]` per existing (func, tier, scale) file, grouped into a
feature-gated module per tier. Only files that actually exist are wired
(include_str! would fail to compile on an absent path; some band-edge cells
have an empty domain — e.g. cosh at MAX_SCALE always overflows — so no table
is emitted and no test is wired).

The wide-tier (d307..d1232) exp cells at {0, S-1} are already wired by the
`wide_s30_exp` module, so exp is skipped there to avoid a duplicate test name.

This is a build-time helper; its output is pasted into ulp_strict_golden.rs.
"""
from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GOLDEN = ROOT / "tests" / "golden"

# (alias, capacity, feature_gate_cfg)
TIERS = [
    ("d18",   18,   "all()"),
    ("d38",   38,   "all()"),
    ("d57",   57,   'any(feature = "d57", feature = "wide")'),
    ("d76",   76,   'any(feature = "d76", feature = "wide")'),
    ("d115",  115,  'any(feature = "d115", feature = "wide")'),
    ("d153",  153,  'any(feature = "d153", feature = "wide")'),
    ("d230",  230,  'any(feature = "d230", feature = "wide")'),
    ("d307",  307,  'any(feature = "d307", feature = "x-wide")'),
    ("d462",  462,  'any(feature = "d462", feature = "x-wide")'),
    ("d616",  616,  'any(feature = "d616", feature = "x-wide")'),
    ("d924",  924,  'any(feature = "d924", feature = "xx-wide")'),
    ("d1232", 1232, 'any(feature = "d1232", feature = "xx-wide")'),
]

WIDTH_ENUM = {
    "d18": "D18", "d38": "D38", "d57": "D57", "d76": "D76", "d115": "D115",
    "d153": "D153", "d230": "D230", "d307": "D307", "d462": "D462",
    "d616": "D616", "d924": "D924", "d1232": "D1232",
}

# The 22 oracle-backed functions, table order.
FUNCS = ["sqrt", "cbrt", "exp", "ln", "log2", "log10", "exp2", "sin", "cos",
         "tan", "atan", "asin", "acos", "sinh", "cosh", "tanh", "asinh",
         "acosh", "atanh", "log", "atan2", "powf"]

# (func, tier, scale) cells already wired elsewhere (wide_s30_exp): exp at
# the wide tiers' {0, S-1}. Skip to avoid a duplicate test fn name.
WIDE = {"d307", "d462", "d616", "d924", "d1232"}

def main() -> None:
    out = []
    out.append("// ─── Band-edge {0, capacity-1} cells (auto-listed) ─────────────────────")
    out.append("//")
    out.append("// Generated by scripts/gen_band_edge_wiring.py. One test per existing")
    out.append("// (func, tier, scale) golden table at the two SCALE extremes (0 and")
    out.append("// capacity-1 = MAX_SCALE). The canonical bands above cover ~S/2; these")
    out.append("// complete the {0, S/2, S-1} coverage so every (function, width) face is")
    out.append("// validity-gated across its whole SCALE range. Absent cells (empty domain")
    out.append("// at the edge, e.g. cosh at MAX_SCALE which always overflows) are not")
    out.append("// emitted by the generator and so carry no test. The wide-tier exp {0,S-1}")
    out.append("// cells are wired by `wide_s30_exp`, so exp is skipped there.")
    out.append("mod band_edges {")
    out.append("    use super::{check_at_scale, Width};")
    for alias, cap, gate in TIERS:
        scales = [0, cap - 1]
        lines = []
        for func in FUNCS:
            for scale in scales:
                if func == "exp" and alias in WIDE:
                    continue  # already in wide_s30_exp
                fname = f"{func}_{alias}_s{scale}.txt"
                if not (GOLDEN / fname).exists():
                    continue
                test_name = f"{alias}_{func}_s{scale}"
                lines.append(
                    f'        #[test]\n'
                    f'        fn {test_name}() {{\n'
                    f'            check_at_scale("{func}", Width::{WIDTH_ENUM[alias]}, {scale}, '
                    f'include_str!("golden/{fname}"));\n'
                    f'        }}'
                )
        if not lines:
            continue
        out.append(f"    #[cfg({gate})]")
        out.append(f"    mod {alias} {{")
        out.append("        use super::{check_at_scale, Width};")
        out.extend(lines)
        out.append("    }")
    out.append("}")
    (ROOT / "scripts" / "band_edge_wiring.rs").write_text(
        "\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {sum(1 for l in out if l.strip() == '#[test]')} tests")

if __name__ == "__main__":
    main()
