//! Hand-rolled generic wide-integer arithmetic.
//!
//! This module is the in-tree big-integer backend for the wide decimal
//! tiers (D256 / D512 / D1024) and for the guard-digit work integers
//! their strict transcendentals run on.
//!
//! # Structure
//!
//! - **Slice primitives** — the actual arithmetic, written once over
//!   `&[u128]` limb slices (little-endian, `limbs[0]` least
//!   significant). Operating on slices sidesteps the const-generic
//!   return-type problem a widening multiply would otherwise hit. The
//!   core routines are `const fn` so the integer types built on them
//!   can expose `const` constructors and constants.
//! - **`decl_hint!`** — a macro that emits a concrete two's-complement
//!   signed integer newtype (and its unsigned sibling) of a fixed limb
//!   count, delegating its arithmetic to the slice primitives.
//! - The concrete `WInt* / SInt*` type pairs generated by that macro.

// ─────────────────────────────────────────────────────────────────────
// Slice primitives — unsigned limb-array arithmetic.
//
// Every routine treats its slices as little-endian unsigned integers.
// Lengths are taken from the slices; callers size output buffers.
// ─────────────────────────────────────────────────────────────────────

/// Full 128×128 → 256 unsigned product, `(high, low)`.
#[inline]
const fn mul_128(a: u128, b: u128) -> (u128, u128) {
    let (a_hi, a_lo) = (a >> 64, a & u64::MAX as u128);
    let (b_hi, b_lo) = (b >> 64, b & u64::MAX as u128);
    let (mid, carry1) = (a_lo * b_hi).overflowing_add(a_hi * b_lo);
    let (low, carry2) = (a_lo * b_lo).overflowing_add(mid << 64);
    let high = a_hi * b_hi + (mid >> 64) + ((carry1 as u128) << 64) + carry2 as u128;
    (high, low)
}

/// `a == 0`.
#[inline]
pub(crate) const fn limbs_is_zero(a: &[u128]) -> bool {
    let mut i = 0;
    while i < a.len() {
        if a[i] != 0 {
            return false;
        }
        i += 1;
    }
    true
}

/// `a == b` for two limb slices of possibly different lengths.
#[inline]
pub(crate) const fn limbs_eq(a: &[u128], b: &[u128]) -> bool {
    let n = if a.len() > b.len() { a.len() } else { b.len() };
    let mut i = 0;
    while i < n {
        let av = if i < a.len() { a[i] } else { 0 };
        let bv = if i < b.len() { b[i] } else { 0 };
        if av != bv {
            return false;
        }
        i += 1;
    }
    true
}

/// Three-way comparison of two limb slices of possibly different
/// lengths. Returns `-1`, `0`, or `1` for less / equal / greater.
#[inline]
pub(crate) const fn limbs_cmp(a: &[u128], b: &[u128]) -> i32 {
    let n = if a.len() > b.len() { a.len() } else { b.len() };
    let mut i = n;
    while i > 0 {
        i -= 1;
        let av = if i < a.len() { a[i] } else { 0 };
        let bv = if i < b.len() { b[i] } else { 0 };
        if av < bv {
            return -1;
        }
        if av > bv {
            return 1;
        }
    }
    0
}

/// Bit length (`0` for zero, else `floor(log2)+1`).
#[inline]
pub(crate) const fn limbs_bit_len(a: &[u128]) -> u32 {
    let mut i = a.len();
    while i > 0 {
        i -= 1;
        if a[i] != 0 {
            return (i as u32) * 128 + (128 - a[i].leading_zeros());
        }
    }
    0
}

/// `a += b`, returning the carry out. `a.len() >= b.len()`.
#[inline]
pub(crate) const fn limbs_add_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut carry = 0u128;
    let mut i = 0;
    while i < a.len() {
        let bv = if i < b.len() { b[i] } else { 0 };
        let (s1, c1) = a[i].overflowing_add(bv);
        let (s2, c2) = s1.overflowing_add(carry);
        a[i] = s2;
        carry = (c1 as u128) + (c2 as u128);
        i += 1;
    }
    carry != 0
}

/// `a -= b`, returning the borrow out. `a.len() >= b.len()`.
#[inline]
pub(crate) const fn limbs_sub_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut borrow = 0u128;
    let mut i = 0;
    while i < a.len() {
        let bv = if i < b.len() { b[i] } else { 0 };
        let (d1, b1) = a[i].overflowing_sub(bv);
        let (d2, b2) = d1.overflowing_sub(borrow);
        a[i] = d2;
        borrow = (b1 as u128) + (b2 as u128);
        i += 1;
    }
    borrow != 0
}

/// `out = a << shift`. `out` is zeroed then filled; bits shifted past
/// `out`'s width are dropped.
pub(crate) const fn limbs_shl(a: &[u128], shift: u32, out: &mut [u128]) {
    let mut z = 0;
    while z < out.len() {
        out[z] = 0;
        z += 1;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    let mut i = 0;
    while i < a.len() {
        let dst = i + limb_shift;
        if dst < out.len() {
            if bit == 0 {
                out[dst] |= a[i];
            } else {
                out[dst] |= a[i] << bit;
                if dst + 1 < out.len() {
                    out[dst + 1] |= a[i] >> (128 - bit);
                }
            }
        }
        i += 1;
    }
}

/// `out = a >> shift`. `out` is zeroed then filled.
pub(crate) const fn limbs_shr(a: &[u128], shift: u32, out: &mut [u128]) {
    let mut z = 0;
    while z < out.len() {
        out[z] = 0;
        z += 1;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    let mut i = limb_shift;
    while i < a.len() {
        let dst = i - limb_shift;
        if dst < out.len() {
            if bit == 0 {
                out[dst] |= a[i];
            } else {
                out[dst] |= a[i] >> bit;
                if dst >= 1 {
                    out[dst - 1] |= a[i] << (128 - bit);
                }
            }
        }
        i += 1;
    }
}

/// `out = a · b` (schoolbook). `out.len() >= a.len() + b.len()` and
/// `out` must be zeroed by the caller.
pub(crate) const fn limbs_mul(a: &[u128], b: &[u128], out: &mut [u128]) {
    let mut i = 0;
    while i < a.len() {
        if a[i] != 0 {
            let mut carry = 0u128;
            let mut j = 0;
            while j < b.len() {
                let (hi, lo) = mul_128(a[i], b[j]);
                let idx = i + j;
                let (s1, c1) = out[idx].overflowing_add(lo);
                let (s2, c2) = s1.overflowing_add(carry);
                out[idx] = s2;
                carry = hi + (c1 as u128) + (c2 as u128);
                j += 1;
            }
            let mut idx = i + b.len();
            while carry != 0 && idx < out.len() {
                let (s, c) = out[idx].overflowing_add(carry);
                out[idx] = s;
                carry = c as u128;
                idx += 1;
            }
        }
        i += 1;
    }
}

/// Single-bit left shift in place; returns the bit shifted out of the
/// top.
#[inline]
const fn limbs_shl1(a: &mut [u128]) -> u128 {
    let mut carry = 0u128;
    let mut i = 0;
    while i < a.len() {
        let new_carry = a[i] >> 127;
        a[i] = (a[i] << 1) | carry;
        carry = new_carry;
        i += 1;
    }
    carry
}

/// `quot = num / den`, `rem = num % den`. Binary shift-subtract long
/// division. `quot.len() >= num.len()`, `rem.len() >= num.len()`;
/// both are zeroed by this routine. `den` must be non-zero.
pub(crate) const fn limbs_divmod(
    num: &[u128],
    den: &[u128],
    quot: &mut [u128],
    rem: &mut [u128],
) {
    let mut z = 0;
    while z < quot.len() {
        quot[z] = 0;
        z += 1;
    }
    z = 0;
    while z < rem.len() {
        rem[z] = 0;
        z += 1;
    }
    let bits = limbs_bit_len(num);
    let mut i = bits;
    while i > 0 {
        i -= 1;
        limbs_shl1(rem);
        let bit = (num[(i / 128) as usize] >> (i % 128)) & 1;
        rem[0] |= bit;
        limbs_shl1(quot);
        if limbs_cmp(rem, den) >= 0 {
            limbs_sub_assign(rem, den);
            quot[0] |= 1;
        }
    }
}

/// Capacity of the internal scratch buffers — 72 limbs (9216 bits),
/// comfortably above the widest work integer in the crate (4096-bit →
/// 32 limbs, with isqrt scratch ≤ 33).
const SCRATCH_LIMBS: usize = 72;

/// `out = floor(sqrt(n))` via Newton's method. `out` is zeroed then
/// filled.
pub(crate) fn limbs_isqrt(n: &[u128], out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let bits = limbs_bit_len(n);
    if bits == 0 {
        return;
    }
    if bits <= 1 {
        out[0] = 1;
        return;
    }
    let work = n.len() + 1;
    debug_assert!(work <= SCRATCH_LIMBS, "wide-int isqrt scratch overflow");
    let mut x = [0u128; SCRATCH_LIMBS];
    let e = bits.div_ceil(2);
    x[(e / 128) as usize] |= 1u128 << (e % 128);
    loop {
        let mut q = [0u128; SCRATCH_LIMBS];
        let mut r = [0u128; SCRATCH_LIMBS];
        limbs_divmod(n, &x[..work], &mut q[..work], &mut r[..work]);
        limbs_add_assign(&mut q[..work], &x[..work]);
        let mut y = [0u128; SCRATCH_LIMBS];
        limbs_shr(&q[..work], 1, &mut y[..work]);
        if limbs_cmp(&y[..work], &x[..work]) >= 0 {
            break;
        }
        x = y;
    }
    let copy_len = if out.len() < work { out.len() } else { work };
    out[..copy_len].copy_from_slice(&x[..copy_len]);
}

/// `limbs /= radix` in place, returning the remainder. `radix` must fit
/// a `u64` so the per-limb division stays within `u128`.
fn limbs_div_small(limbs: &mut [u128], radix: u128) -> u128 {
    let mut rem = 0u128;
    for limb in limbs.iter_mut().rev() {
        let hi = (*limb) >> 64;
        let lo = (*limb) & u64::MAX as u128;
        let acc_hi = (rem << 64) | hi;
        let q_hi = acc_hi / radix;
        let r1 = acc_hi % radix;
        let acc_lo = (r1 << 64) | lo;
        let q_lo = acc_lo / radix;
        rem = acc_lo % radix;
        *limb = (q_hi << 64) | q_lo;
    }
    rem
}

/// Formats a limb slice into `buf` in the given radix (`2..=16`),
/// returning the written digit subslice. The slice is treated as an
/// unsigned magnitude.
pub(crate) fn limbs_fmt_into<'a>(
    limbs: &[u128],
    radix: u128,
    lower: bool,
    buf: &'a mut [u8],
) -> &'a str {
    let digits: &[u8] = if lower {
        b"0123456789abcdef"
    } else {
        b"0123456789ABCDEF"
    };
    if limbs_is_zero(limbs) {
        let last = buf.len() - 1;
        buf[last] = b'0';
        return core::str::from_utf8(&buf[last..]).unwrap();
    }
    let mut work = [0u128; SCRATCH_LIMBS];
    work[..limbs.len()].copy_from_slice(limbs);
    let wl = limbs.len();
    let mut pos = buf.len();
    while !limbs_is_zero(&work[..wl]) {
        let r = limbs_div_small(&mut work[..wl], radix);
        pos -= 1;
        buf[pos] = digits[r as usize];
    }
    core::str::from_utf8(&buf[pos..]).unwrap()
}

// ─────────────────────────────────────────────────────────────────────
// decl_hint! — concrete fixed-width signed/unsigned integer newtypes.
//
// Each invocation emits an unsigned `$U` ([u128; L]) and a
// two's-complement signed `$S` ([u128; L]), both delegating their
// arithmetic to the slice primitives above. The arithmetic surface is
// `const fn` so the decimal types built on it can be `const`.
// ─────────────────────────────────────────────────────────────────────

/// Emits the `$U` / `$S` integer pair for a fixed limb count.
///
/// - `$U` / `$S` — the unsigned and signed type names.
/// - `$L` — limb count (`[u128; $L]`); the bit width is `$L * 128`.
/// - `$D` — `2 * $L`, the buffer width for widening multiply/divide
///   intermediates.
macro_rules! decl_hint {
    ($U:ident, $S:ident, $L:tt, $D:tt) => {
        // ── Unsigned ──────────────────────────────────────────────────
        /// Hand-rolled fixed-width unsigned integer, little-endian limbs.
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
        pub struct $U(pub(crate) [u128; $L]);

        impl $U {
            pub(crate) const ZERO: $U = $U([0; $L]);
            pub(crate) const MAX: $U = $U([u128::MAX; $L]);
            pub(crate) const BITS: u32 = $L * 128;

            #[inline]
            pub(crate) const fn is_zero(self) -> bool {
                $crate::hint::limbs_is_zero(&self.0)
            }
            #[inline]
            pub(crate) const fn leading_zeros(self) -> u32 {
                Self::BITS - $crate::hint::limbs_bit_len(&self.0)
            }
            #[inline]
            pub(crate) const fn count_ones(self) -> u32 {
                let mut total = 0;
                let mut i = 0;
                while i < $L {
                    total += self.0[i].count_ones();
                    i += 1;
                }
                total
            }
            #[inline]
            pub(crate) const fn is_power_of_two(self) -> bool {
                self.count_ones() == 1
            }
            pub(crate) const fn next_power_of_two(self) -> $U {
                if self.is_zero() {
                    let mut o = [0u128; $L];
                    o[0] = 1;
                    return $U(o);
                }
                if self.is_power_of_two() {
                    return self;
                }
                let bits = $crate::hint::limbs_bit_len(&self.0);
                let mut out = [0u128; $L];
                if (bits as usize) < $L * 128 {
                    out[(bits / 128) as usize] = 1u128 << (bits % 128);
                }
                $U(out)
            }
            /// Reinterprets the bit pattern as the signed sibling.
            #[inline]
            pub(crate) const fn cast_signed(self) -> $S {
                $S(self.0)
            }
            /// Parses an unsigned decimal string. Only base 10 is
            /// supported.
            pub(crate) const fn from_str_radix(
                s: &str,
                radix: u32,
            ) -> ::core::result::Result<$U, ()> {
                if radix != 10 {
                    return ::core::result::Result::Err(());
                }
                let bytes = s.as_bytes();
                let mut acc = [0u128; $L];
                let ten = [10u128];
                let mut k = 0;
                while k < bytes.len() {
                    let ch = bytes[k];
                    if ch < b'0' || ch > b'9' {
                        return ::core::result::Result::Err(());
                    }
                    let d = (ch - b'0') as u128;
                    let mut scaled = [0u128; $D];
                    $crate::hint::limbs_mul(&acc, &ten, &mut scaled);
                    let mut next = [0u128; $L];
                    let mut c = 0;
                    while c < $L {
                        next[c] = scaled[c];
                        c += 1;
                    }
                    $crate::hint::limbs_add_assign(&mut next, &[d]);
                    acc = next;
                    k += 1;
                }
                ::core::result::Result::Ok($U(acc))
            }
            pub(crate) const fn pow(self, mut exp: u32) -> $U {
                let mut acc = {
                    let mut o = [0u128; $L];
                    o[0] = 1;
                    $U(o)
                };
                let mut base = self;
                while exp > 0 {
                    if exp & 1 == 1 {
                        acc = acc.wrapping_mul(base);
                    }
                    exp >>= 1;
                    if exp > 0 {
                        base = base.wrapping_mul(base);
                    }
                }
                acc
            }
            #[inline]
            pub(crate) const fn wrapping_mul(self, rhs: $U) -> $U {
                let mut prod = [0u128; $D];
                $crate::hint::limbs_mul(&self.0, &rhs.0, &mut prod);
                let mut out = [0u128; $L];
                let mut i = 0;
                while i < $L {
                    out[i] = prod[i];
                    i += 1;
                }
                $U(out)
            }
            #[inline]
            pub(crate) fn isqrt(self) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_isqrt(&self.0, &mut out);
                $U(out)
            }
        }

        impl ::core::cmp::Ord for $U {
            #[inline]
            fn cmp(&self, other: &$U) -> ::core::cmp::Ordering {
                $crate::hint::limbs_cmp(&self.0, &other.0).cmp(&0)
            }
        }
        impl ::core::cmp::PartialOrd for $U {
            #[inline]
            fn partial_cmp(&self, other: &$U) -> ::core::option::Option<::core::cmp::Ordering> {
                ::core::option::Option::Some(self.cmp(other))
            }
        }
        impl ::core::ops::Shr<u32> for $U {
            type Output = $U;
            #[inline]
            fn shr(self, n: u32) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shr(&self.0, n, &mut out);
                $U(out)
            }
        }
        impl ::core::ops::Shl<u32> for $U {
            type Output = $U;
            #[inline]
            fn shl(self, n: u32) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shl(&self.0, n, &mut out);
                $U(out)
            }
        }
        impl ::core::ops::Sub for $U {
            type Output = $U;
            #[inline]
            fn sub(mut self, rhs: $U) -> $U {
                $crate::hint::limbs_sub_assign(&mut self.0, &rhs.0);
                self
            }
        }
        impl ::core::ops::Div for $U {
            type Output = $U;
            #[inline]
            fn div(self, rhs: $U) -> $U {
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(&self.0, &rhs.0, &mut q, &mut r);
                $U(q)
            }
        }
        impl ::core::ops::Rem for $U {
            type Output = $U;
            #[inline]
            fn rem(self, rhs: $U) -> $U {
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(&self.0, &rhs.0, &mut q, &mut r);
                $U(r)
            }
        }
        impl ::core::ops::BitAnd for $U {
            type Output = $U;
            #[inline]
            fn bitand(self, rhs: $U) -> $U {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] & rhs.0[i];
                }
                $U(o)
            }
        }
        impl ::core::ops::BitOr for $U {
            type Output = $U;
            #[inline]
            fn bitor(self, rhs: $U) -> $U {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] | rhs.0[i];
                }
                $U(o)
            }
        }
        impl ::core::ops::BitXor for $U {
            type Output = $U;
            #[inline]
            fn bitxor(self, rhs: $U) -> $U {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] ^ rhs.0[i];
                }
                $U(o)
            }
        }

        // ── Signed ────────────────────────────────────────────────────
        /// Hand-rolled fixed-width two's-complement signed integer.
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
        pub struct $S(pub(crate) [u128; $L]);

        impl $S {
            pub(crate) const ZERO: $S = $S([0; $L]);
            pub(crate) const ONE: $S = {
                let mut a = [0u128; $L];
                a[0] = 1;
                $S(a)
            };
            pub(crate) const BITS: u32 = $L * 128;
            pub(crate) const MAX: $S = {
                let mut a = [u128::MAX; $L];
                a[$L - 1] = i128::MAX as u128;
                $S(a)
            };
            pub(crate) const MIN: $S = {
                let mut a = [0u128; $L];
                a[$L - 1] = 1u128 << 127;
                $S(a)
            };

            #[inline]
            pub(crate) const fn is_negative(self) -> bool {
                self.0[$L - 1] >> 127 == 1
            }
            #[inline]
            pub(crate) const fn is_zero(self) -> bool {
                $crate::hint::limbs_is_zero(&self.0)
            }
            #[inline]
            pub(crate) const fn is_positive(self) -> bool {
                !self.is_negative() && !self.is_zero()
            }
            /// Two's-complement negation (wrapping; `MIN.negate() == MIN`).
            #[inline]
            pub(crate) const fn negate(self) -> $S {
                let mut out = [0u128; $L];
                let mut i = 0;
                while i < $L {
                    out[i] = !self.0[i];
                    i += 1;
                }
                $crate::hint::limbs_add_assign(&mut out, &[1]);
                $S(out)
            }
            /// `|self|` as the unsigned sibling. `MIN` maps to `2^(BITS-1)`.
            #[inline]
            pub(crate) const fn unsigned_abs(self) -> $U {
                if self.is_negative() {
                    $U(self.negate().0)
                } else {
                    $U(self.0)
                }
            }
            /// Reinterprets the bit pattern as the unsigned sibling.
            #[inline]
            pub(crate) const fn cast_unsigned(self) -> $U {
                $U(self.0)
            }
            /// Builds a signed value from a non-negative magnitude limb
            /// slice and a sign, truncating the magnitude into `$L`
            /// limbs.
            pub(crate) const fn from_mag_limbs(mag: &[u128], negative: bool) -> $S {
                let mut out = [0u128; $L];
                let n = if mag.len() < $L { mag.len() } else { $L };
                let mut i = 0;
                while i < n {
                    out[i] = mag[i];
                    i += 1;
                }
                let v = $S(out);
                if negative && !v.is_zero() {
                    v.negate()
                } else {
                    v
                }
            }
            #[inline]
            pub(crate) const fn leading_zeros(self) -> u32 {
                Self::BITS - $crate::hint::limbs_bit_len(&self.unsigned_abs().0)
            }
            #[inline]
            pub(crate) const fn count_ones(self) -> u32 {
                let mut total = 0;
                let mut i = 0;
                while i < $L {
                    total += self.0[i].count_ones();
                    i += 1;
                }
                total
            }
            #[inline]
            pub(crate) const fn count_zeros(self) -> u32 {
                Self::BITS - self.count_ones()
            }
            /// `true` if bit `idx` of the two's-complement representation
            /// is set.
            #[inline]
            pub(crate) const fn bit(self, idx: u32) -> bool {
                let limb = (idx / 128) as usize;
                if limb >= $L {
                    return self.is_negative();
                }
                (self.0[limb] >> (idx % 128)) & 1 == 1
            }
            #[inline]
            pub(crate) const fn trailing_zeros(self) -> u32 {
                let mut i = 0;
                while i < $L {
                    if self.0[i] != 0 {
                        return i as u32 * 128 + self.0[i].trailing_zeros();
                    }
                    i += 1;
                }
                Self::BITS
            }
            pub(crate) const fn from_str_radix(
                s: &str,
                radix: u32,
            ) -> ::core::result::Result<$S, ()> {
                let bytes = s.as_bytes();
                let (negative, digits): (bool, &[u8]) =
                    if !bytes.is_empty() && bytes[0] == b'-' {
                        (true, bytes.split_at(1).1)
                    } else {
                        (false, bytes)
                    };
                // Reparse the digit bytes as a decimal magnitude.
                if radix != 10 {
                    return ::core::result::Result::Err(());
                }
                let mut acc = [0u128; $L];
                let ten = [10u128];
                let mut k = 0;
                while k < digits.len() {
                    let ch = digits[k];
                    if ch < b'0' || ch > b'9' {
                        return ::core::result::Result::Err(());
                    }
                    let d = (ch - b'0') as u128;
                    let mut scaled = [0u128; $D];
                    $crate::hint::limbs_mul(&acc, &ten, &mut scaled);
                    let mut next = [0u128; $L];
                    let mut c = 0;
                    while c < $L {
                        next[c] = scaled[c];
                        c += 1;
                    }
                    $crate::hint::limbs_add_assign(&mut next, &[d]);
                    acc = next;
                    k += 1;
                }
                ::core::result::Result::Ok($S::from_mag_limbs(&acc, negative))
            }
            pub(crate) const fn pow(self, mut exp: u32) -> $S {
                let mut acc = $S::ONE;
                let mut base = self;
                while exp > 0 {
                    if exp & 1 == 1 {
                        acc = acc.wrapping_mul(base);
                    }
                    exp >>= 1;
                    if exp > 0 {
                        base = base.wrapping_mul(base);
                    }
                }
                acc
            }
            #[inline]
            pub(crate) const fn wrapping_add(self, rhs: $S) -> $S {
                let mut out = self.0;
                $crate::hint::limbs_add_assign(&mut out, &rhs.0);
                $S(out)
            }
            #[inline]
            pub(crate) const fn wrapping_sub(self, rhs: $S) -> $S {
                self.wrapping_add(rhs.negate())
            }
            #[inline]
            pub(crate) const fn wrapping_neg(self) -> $S {
                self.negate()
            }
            pub(crate) const fn wrapping_mul(self, rhs: $S) -> $S {
                let negative = self.is_negative() ^ rhs.is_negative();
                let prod = self.unsigned_abs().wrapping_mul(rhs.unsigned_abs());
                $S::from_mag_limbs(&prod.0, negative)
            }
            /// `self / rhs` truncating toward zero. `rhs` must be nonzero.
            pub(crate) const fn wrapping_div(self, rhs: $S) -> $S {
                if rhs.is_zero() {
                    panic!("wide integer: division by zero");
                }
                let negative = self.is_negative() ^ rhs.is_negative();
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut q,
                    &mut r,
                );
                $S::from_mag_limbs(&q, negative)
            }
            /// `self % rhs`, result carries the sign of `self`.
            pub(crate) const fn wrapping_rem(self, rhs: $S) -> $S {
                if rhs.is_zero() {
                    panic!("wide integer: remainder by zero");
                }
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut q,
                    &mut r,
                );
                $S::from_mag_limbs(&r, self.is_negative())
            }
            #[inline]
            const fn add_overflows(self, rhs: $S, result: $S) -> bool {
                self.is_negative() == rhs.is_negative()
                    && result.is_negative() != self.is_negative()
            }
            #[inline]
            pub(crate) const fn checked_add(self, rhs: $S) -> ::core::option::Option<$S> {
                let r = self.wrapping_add(rhs);
                if self.add_overflows(rhs, r) {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(r)
                }
            }
            #[inline]
            pub(crate) const fn checked_sub(self, rhs: $S) -> ::core::option::Option<$S> {
                let r = self.wrapping_sub(rhs);
                if self.is_negative() != rhs.is_negative()
                    && r.is_negative() != self.is_negative()
                {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(r)
                }
            }
            #[inline]
            pub(crate) const fn checked_neg(self) -> ::core::option::Option<$S> {
                if $crate::hint::limbs_eq(&self.0, &$S::MIN.0) {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.negate())
                }
            }
            pub(crate) const fn checked_mul(self, rhs: $S) -> ::core::option::Option<$S> {
                let negative = self.is_negative() ^ rhs.is_negative();
                let mut prod = [0u128; $D];
                $crate::hint::limbs_mul(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut prod,
                );
                let (_lo, hi) = prod.split_at($L);
                if !$crate::hint::limbs_is_zero(hi) {
                    return ::core::option::Option::None;
                }
                let r = $S::from_mag_limbs(prod.split_at($L).0, negative);
                if r.is_zero() || r.is_negative() == negative {
                    ::core::option::Option::Some(r)
                } else {
                    ::core::option::Option::None
                }
            }
            #[inline]
            pub(crate) const fn checked_div(self, rhs: $S) -> ::core::option::Option<$S> {
                if rhs.is_zero() {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.wrapping_div(rhs))
                }
            }
            #[inline]
            pub(crate) const fn checked_rem(self, rhs: $S) -> ::core::option::Option<$S> {
                if rhs.is_zero() {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.wrapping_rem(rhs))
                }
            }
            #[inline]
            pub(crate) fn isqrt(self) -> $S {
                $S(self.unsigned_abs().isqrt().0)
            }
            #[inline]
            pub(crate) const fn abs(self) -> $S {
                if self.is_negative() {
                    self.negate()
                } else {
                    self
                }
            }
            #[inline]
            pub(crate) const fn signum(self) -> $S {
                if self.is_zero() {
                    $S::ZERO
                } else if self.is_negative() {
                    $S::ONE.negate()
                } else {
                    $S::ONE
                }
            }
            #[inline]
            pub(crate) const fn overflowing_add(self, rhs: $S) -> ($S, bool) {
                let r = self.wrapping_add(rhs);
                (r, self.add_overflows(rhs, r))
            }
            #[inline]
            pub(crate) const fn overflowing_sub(self, rhs: $S) -> ($S, bool) {
                let r = self.wrapping_sub(rhs);
                let ov = self.is_negative() != rhs.is_negative()
                    && r.is_negative() != self.is_negative();
                (r, ov)
            }
            #[inline]
            pub(crate) const fn overflowing_neg(self) -> ($S, bool) {
                (self.negate(), $crate::hint::limbs_eq(&self.0, &$S::MIN.0))
            }
            #[inline]
            pub(crate) const fn overflowing_rem(self, rhs: $S) -> ($S, bool) {
                (self.wrapping_rem(rhs), false)
            }
            #[inline]
            pub(crate) const fn saturating_add(self, rhs: $S) -> $S {
                match self.checked_add(rhs) {
                    ::core::option::Option::Some(v) => v,
                    ::core::option::Option::None => {
                        if self.is_negative() { $S::MIN } else { $S::MAX }
                    }
                }
            }
            #[inline]
            pub(crate) const fn saturating_sub(self, rhs: $S) -> $S {
                match self.checked_sub(rhs) {
                    ::core::option::Option::Some(v) => v,
                    ::core::option::Option::None => {
                        if self.is_negative() { $S::MIN } else { $S::MAX }
                    }
                }
            }
            #[inline]
            pub(crate) const fn saturating_neg(self) -> $S {
                match self.checked_neg() {
                    ::core::option::Option::Some(v) => v,
                    ::core::option::Option::None => $S::MAX,
                }
            }
            pub(crate) fn rotate_left(self, n: u32) -> $S {
                let n = n % Self::BITS;
                if n == 0 {
                    return self;
                }
                let u = self.cast_unsigned();
                $S(((u << n) | (u >> (Self::BITS - n))).0)
            }
            #[inline]
            pub(crate) fn rotate_right(self, n: u32) -> $S {
                self.rotate_left(Self::BITS - (n % Self::BITS))
            }
            #[inline]
            pub(crate) const fn max(self, rhs: $S) -> $S {
                if $crate::hint::scmp(self.is_negative(), &self.0, rhs.is_negative(), &rhs.0) >= 0 {
                    self
                } else {
                    rhs
                }
            }
            #[inline]
            pub(crate) const fn min(self, rhs: $S) -> $S {
                if $crate::hint::scmp(self.is_negative(), &self.0, rhs.is_negative(), &rhs.0) <= 0 {
                    self
                } else {
                    rhs
                }
            }
            /// Euclidean division: the quotient that leaves a
            /// non-negative remainder.
            pub(crate) const fn div_euclid(self, rhs: $S) -> $S {
                let q = self.wrapping_div(rhs);
                let r = self.wrapping_rem(rhs);
                if r.is_negative() {
                    if rhs.is_negative() {
                        q.wrapping_add($S::ONE)
                    } else {
                        q.wrapping_sub($S::ONE)
                    }
                } else {
                    q
                }
            }
            /// Euclidean remainder — always non-negative.
            pub(crate) const fn rem_euclid(self, rhs: $S) -> $S {
                let r = self.wrapping_rem(rhs);
                if r.is_negative() {
                    r.wrapping_add(rhs.abs())
                } else {
                    r
                }
            }
            /// Exact `i128` value, or `None` if it does not fit.
            pub(crate) const fn to_i128_checked(self) -> ::core::option::Option<i128> {
                let negative = self.is_negative();
                let mag = self.unsigned_abs().0;
                let (lo, hi) = mag.split_at(1);
                if !$crate::hint::limbs_is_zero(hi) {
                    return ::core::option::Option::None;
                }
                if negative {
                    if lo[0] <= (i128::MAX as u128) + 1 {
                        ::core::option::Option::Some((lo[0] as i128).wrapping_neg())
                    } else {
                        ::core::option::Option::None
                    }
                } else if lo[0] <= i128::MAX as u128 {
                    ::core::option::Option::Some(lo[0] as i128)
                } else {
                    ::core::option::Option::None
                }
            }
            /// Exact `u128` value, or `None` if negative / too large.
            pub(crate) const fn to_u128_checked(self) -> ::core::option::Option<u128> {
                let (lo, hi) = self.0.split_at(1);
                if self.is_negative() || !$crate::hint::limbs_is_zero(hi) {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(lo[0])
                }
            }
            /// Builds from a signed 128-bit value.
            #[inline]
            pub(crate) const fn from_i128(v: i128) -> $S {
                $S::from_mag_limbs(&[v.unsigned_abs()], v < 0)
            }
            /// Builds from an unsigned 128-bit value.
            #[inline]
            pub(crate) const fn from_u128(v: u128) -> $S {
                $S::from_mag_limbs(&[v], false)
            }
            /// Truncating cast to `i128` (low 128 bits, sign-applied).
            #[inline]
            pub(crate) const fn as_i128(self) -> i128 {
                let mag = self.unsigned_abs().0[0];
                if self.is_negative() {
                    (mag as i128).wrapping_neg()
                } else {
                    mag as i128
                }
            }
            /// Widening / narrowing cast to any other `WideInt`.
            #[inline]
            pub(crate) fn resize<T: $crate::hint::WideInt>(self) -> T {
                $crate::hint::wide_cast(self)
            }
            /// Approximate `f64` value.
            pub(crate) fn as_f64(self) -> f64 {
                let mag = self.unsigned_abs().0;
                let mut acc = 0.0f64;
                for i in (0..$L).rev() {
                    acc = acc * 340_282_366_920_938_463_463_374_607_431_768_211_456.0
                        + mag[i] as f64;
                }
                if self.is_negative() {
                    -acc
                } else {
                    acc
                }
            }
            /// Builds from an `f64`, truncating toward zero. Saturates
            /// to `MIN` / `MAX` on out-of-range / non-finite input.
            ///
            /// `core`-only: the limb extraction relies on the `f64 →
            /// u128` cast for truncation, so it needs neither
            /// `f64::trunc` nor `f64::abs`.
            pub(crate) fn from_f64(v: f64) -> $S {
                if !v.is_finite() {
                    return $S::ZERO;
                }
                let negative = v < 0.0;
                let mut m = if negative { -v } else { v };
                let radix = 340_282_366_920_938_463_463_374_607_431_768_211_456.0;
                let mut limbs = [0u128; $L];
                let mut i = 0;
                while m >= 1.0 && i < $L {
                    // `rem` is the value modulo 2^128; the `as u128` cast
                    // truncates its fractional part. Subtracting `rem`
                    // leaves a clean multiple of the radix to shift down.
                    let rem = m % radix;
                    limbs[i] = rem as u128;
                    m = (m - rem) / radix;
                    i += 1;
                }
                if m >= 1.0 {
                    return if negative { $S::MIN } else { $S::MAX };
                }
                $S::from_mag_limbs(&limbs, negative)
            }
        }

        impl $crate::hint::WideInt for $S {
            #[inline]
            fn to_mag_sign(self) -> ([u128; 32], bool) {
                let mut out = [0u128; 32];
                let mag = self.unsigned_abs().0;
                out[..$L].copy_from_slice(&mag);
                (out, self.is_negative())
            }
            #[inline]
            fn from_mag_sign(mag: &[u128], negative: bool) -> $S {
                $S::from_mag_limbs(mag, negative)
            }
        }

        impl ::core::cmp::Ord for $S {
            #[inline]
            fn cmp(&self, other: &$S) -> ::core::cmp::Ordering {
                $crate::hint::scmp(
                    self.is_negative(),
                    &self.0,
                    other.is_negative(),
                    &other.0,
                )
                .cmp(&0)
            }
        }
        impl ::core::cmp::PartialOrd for $S {
            #[inline]
            fn partial_cmp(&self, other: &$S) -> ::core::option::Option<::core::cmp::Ordering> {
                ::core::option::Option::Some(self.cmp(other))
            }
        }
        impl ::core::ops::Add for $S {
            type Output = $S;
            #[inline]
            fn add(self, rhs: $S) -> $S {
                self.checked_add(rhs)
                    .expect(concat!(stringify!($S), ": add overflow"))
            }
        }
        impl ::core::ops::Sub for $S {
            type Output = $S;
            #[inline]
            fn sub(self, rhs: $S) -> $S {
                self.checked_sub(rhs)
                    .expect(concat!(stringify!($S), ": sub overflow"))
            }
        }
        impl ::core::ops::Mul for $S {
            type Output = $S;
            #[inline]
            fn mul(self, rhs: $S) -> $S {
                self.checked_mul(rhs)
                    .expect(concat!(stringify!($S), ": mul overflow"))
            }
        }
        impl ::core::ops::Div for $S {
            type Output = $S;
            #[inline]
            fn div(self, rhs: $S) -> $S {
                self.wrapping_div(rhs)
            }
        }
        impl ::core::ops::Rem for $S {
            type Output = $S;
            #[inline]
            fn rem(self, rhs: $S) -> $S {
                self.wrapping_rem(rhs)
            }
        }
        impl ::core::ops::Neg for $S {
            type Output = $S;
            #[inline]
            fn neg(self) -> $S {
                self.checked_neg()
                    .expect(concat!(stringify!($S), ": neg overflow"))
            }
        }
        impl ::core::ops::Shl<u32> for $S {
            type Output = $S;
            #[inline]
            fn shl(self, n: u32) -> $S {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shl(&self.0, n, &mut out);
                $S(out)
            }
        }
        impl ::core::ops::Shr<u32> for $S {
            type Output = $S;
            /// Arithmetic right shift (sign-preserving).
            #[inline]
            fn shr(self, n: u32) -> $S {
                if self.is_negative() {
                    let mag = self.unsigned_abs();
                    let shifted = mag >> n;
                    $S::from_mag_limbs(&shifted.0, true)
                } else {
                    let mut out = [0u128; $L];
                    $crate::hint::limbs_shr(&self.0, n, &mut out);
                    $S(out)
                }
            }
        }
        impl ::core::ops::BitAnd for $S {
            type Output = $S;
            #[inline]
            fn bitand(self, rhs: $S) -> $S {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] & rhs.0[i];
                }
                $S(o)
            }
        }
        impl ::core::ops::BitOr for $S {
            type Output = $S;
            #[inline]
            fn bitor(self, rhs: $S) -> $S {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] | rhs.0[i];
                }
                $S(o)
            }
        }
        impl ::core::ops::BitXor for $S {
            type Output = $S;
            #[inline]
            fn bitxor(self, rhs: $S) -> $S {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = self.0[i] ^ rhs.0[i];
                }
                $S(o)
            }
        }
        impl ::core::ops::Not for $S {
            type Output = $S;
            #[inline]
            fn not(self) -> $S {
                let mut o = [0u128; $L];
                for i in 0..$L {
                    o[i] = !self.0[i];
                }
                $S(o)
            }
        }

        // ── Formatting ────────────────────────────────────────────────
        impl ::core::fmt::Display for $U {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut buf = [0u8; $L * 128];
                let s = $crate::hint::limbs_fmt_into(&self.0, 10, true, &mut buf);
                f.pad_integral(true, "", s)
            }
        }
        impl ::core::fmt::LowerHex for $S {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut buf = [0u8; $L * 128];
                let s = $crate::hint::limbs_fmt_into(&self.0, 16, true, &mut buf);
                f.pad_integral(true, "0x", s)
            }
        }
        impl ::core::fmt::UpperHex for $S {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut buf = [0u8; $L * 128];
                let s = $crate::hint::limbs_fmt_into(&self.0, 16, false, &mut buf);
                f.pad_integral(true, "0x", s)
            }
        }
        impl ::core::fmt::Octal for $S {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut buf = [0u8; $L * 128];
                let s = $crate::hint::limbs_fmt_into(&self.0, 8, true, &mut buf);
                f.pad_integral(true, "0o", s)
            }
        }
        impl ::core::fmt::Binary for $S {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut buf = [0u8; $L * 128];
                let s = $crate::hint::limbs_fmt_into(&self.0, 2, true, &mut buf);
                f.pad_integral(true, "0b", s)
            }
        }
    };
}

/// Signed three-way comparison of two magnitude-limb slices given their
/// signs. Returns `-1` / `0` / `1`.
#[inline]
pub(crate) const fn scmp(a_neg: bool, a: &[u128], b_neg: bool, b: &[u128]) -> i32 {
    match (a_neg, b_neg) {
        (true, false) => -1,
        (false, true) => 1,
        _ => limbs_cmp(a, b),
    }
}

/// A signed integer that can be decomposed into a magnitude + sign and
/// rebuilt from one — the basis of `wide_cast` (widen / narrow between
/// any two widths, or between a wide integer and a primitive
/// `i128` / `i64` / `u128`).
pub(crate) trait WideInt: Copy {
    /// Magnitude limbs (little-endian, zero-padded to 32) and sign.
    fn to_mag_sign(self) -> ([u128; 32], bool);
    /// Rebuilds from a magnitude limb slice and a sign, truncating the
    /// magnitude to this type's width.
    fn from_mag_sign(mag: &[u128], negative: bool) -> Self;
}

/// Implements `WideInt` for a signed primitive integer.
macro_rules! impl_wideint_signed_prim {
    ($($t:ty),*) => {$(
        impl WideInt for $t {
            #[inline]
            fn to_mag_sign(self) -> ([u128; 32], bool) {
                let mut out = [0u128; 32];
                out[0] = self.unsigned_abs() as u128;
                (out, self < 0)
            }
            #[inline]
            fn from_mag_sign(mag: &[u128], negative: bool) -> $t {
                let m = mag.first().copied().unwrap_or(0) as $t;
                if negative { m.wrapping_neg() } else { m }
            }
        }
    )*};
}
impl_wideint_signed_prim!(i8, i16, i32, i64, i128);

impl WideInt for u128 {
    #[inline]
    fn to_mag_sign(self) -> ([u128; 32], bool) {
        let mut out = [0u128; 32];
        out[0] = self;
        (out, false)
    }
    #[inline]
    fn from_mag_sign(mag: &[u128], _negative: bool) -> u128 {
        mag.first().copied().unwrap_or(0)
    }
}

/// Widening / narrowing cast between any two `WideInt` types via a
/// shared magnitude + sign representation.
#[inline]
pub(crate) fn wide_cast<S: WideInt, T: WideInt>(src: S) -> T {
    let (mag, negative) = src.to_mag_sign();
    T::from_mag_sign(&mag, negative)
}

// The concrete wide integer type pairs. The 256/512/1024-bit widths
// back the wide decimal tiers; 2048/4096-bit widths are the
// strict-transcendental work integers.
decl_hint!(WInt256, SInt256, 2, 4);
decl_hint!(WInt512, SInt512, 4, 8);
decl_hint!(WInt1024, SInt1024, 8, 16);
decl_hint!(WInt2048, SInt2048, 16, 32);
decl_hint!(WInt4096, SInt4096, 32, 64);

#[cfg(test)]
mod hint_tests {
    use super::*;

    #[test]
    fn signed_add_sub_neg() {
        let a = SInt256::from_i128(5);
        let b = SInt256::from_i128(3);
        assert_eq!(a.wrapping_add(b), SInt256::from_i128(8));
        assert_eq!(a.wrapping_sub(b), SInt256::from_i128(2));
        assert_eq!(b.wrapping_sub(a), SInt256::from_i128(-2));
        assert_eq!(a.negate(), SInt256::from_i128(-5));
        assert_eq!(SInt256::ZERO.negate(), SInt256::ZERO);
    }

    #[test]
    fn signed_mul_div_rem() {
        let six = SInt512::from_i128(6);
        let two = SInt512::from_i128(2);
        let three = SInt512::from_i128(3);
        assert_eq!(six.wrapping_mul(three), SInt512::from_i128(18));
        assert_eq!(six.wrapping_div(two), three);
        assert_eq!(SInt512::from_i128(7).wrapping_rem(three), SInt512::from_i128(1));
        assert_eq!(SInt512::from_i128(-7).wrapping_rem(three), SInt512::from_i128(-1));
        assert_eq!(six.negate().wrapping_mul(three), SInt512::from_i128(-18));
    }

    #[test]
    fn checked_overflow() {
        assert_eq!(SInt256::MAX.checked_add(SInt256::ONE), None);
        assert_eq!(SInt256::MIN.checked_sub(SInt256::ONE), None);
        assert_eq!(SInt256::MIN.checked_neg(), None);
        assert_eq!(
            SInt256::from_i128(2).checked_add(SInt256::from_i128(3)),
            Some(SInt256::from_i128(5))
        );
    }

    #[test]
    fn from_str_and_pow() {
        let ten = SInt1024::from_str_radix("10", 10).unwrap();
        assert_eq!(ten, SInt1024::from_i128(10));
        assert_eq!(ten.pow(3), SInt1024::from_i128(1000));
        let big = SInt1024::from_str_radix("10", 10).unwrap().pow(40);
        let from_str = SInt1024::from_str_radix(
            "10000000000000000000000000000000000000000",
            10,
        )
        .unwrap();
        assert_eq!(big, from_str);
        assert_eq!(SInt256::from_str_radix("-42", 10).unwrap(), SInt256::from_i128(-42));
    }

    #[test]
    fn ordering_and_resize() {
        assert!(SInt256::from_i128(-1) < SInt256::ZERO);
        assert!(SInt256::MIN < SInt256::MAX);
        let v = SInt256::from_i128(-123_456_789);
        let wide: SInt1024 = v.resize();
        let back: SInt256 = wide.resize();
        assert_eq!(back, v);
        assert_eq!(wide, SInt1024::from_i128(-123_456_789));
    }

    #[test]
    fn isqrt_and_f64() {
        assert_eq!(SInt512::from_i128(144).isqrt(), SInt512::from_i128(12));
        assert_eq!(SInt256::from_i128(1_000_000).as_f64(), 1_000_000.0);
        assert_eq!(SInt256::from_f64(-2_500.0), SInt256::from_i128(-2500));
    }
}

#[cfg(test)]
mod slice_tests {
    use super::*;

    #[test]
    fn mul_and_divmod_round_trip() {
        let a = [123u128, 7, 0, 0];
        let b = [456u128, 0, 0, 0];
        let mut prod = [0u128; 8];
        limbs_mul(&a, &b, &mut prod);
        let mut q = [0u128; 8];
        let mut r = [0u128; 8];
        limbs_divmod(&prod, &b, &mut q, &mut r);
        assert_eq!(&q[..4], &a, "quotient");
        assert!(limbs_is_zero(&r), "remainder");
    }

    #[test]
    fn shifts() {
        let a = [1u128, 0];
        let mut out = [0u128; 2];
        limbs_shl(&a, 130, &mut out);
        assert_eq!(out, [0, 4]);
        let mut back = [0u128; 2];
        limbs_shr(&out, 130, &mut back);
        assert_eq!(back, [1, 0]);
    }

    #[test]
    fn isqrt_basic() {
        let n = [0u128, 0, 1, 0];
        let mut out = [0u128; 4];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [0, 1, 0, 0]);
        let n = [144u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [12, 0]);
        let n = [2u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [1, 0]);
    }

    #[test]
    fn add_sub_carry() {
        let mut a = [u128::MAX, 0];
        let carry = limbs_add_assign(&mut a, &[1, 0]);
        assert!(!carry);
        assert_eq!(a, [0, 1]);
        let borrow = limbs_sub_assign(&mut a, &[1, 0]);
        assert!(!borrow);
        assert_eq!(a, [u128::MAX, 0]);
    }
}
