//! Hand-rolled generic wide-integer arithmetic.
//!
//! This module is the in-tree big-integer backend for the wide decimal
//! tiers (D256 / D512 / D1024) and for the guard-digit work integers
//! their strict transcendentals run on. It replaces `bnum` in normal
//! builds — `bnum` is kept only as a benchmark baseline (see
//! `src/benchmark/`).
//!
//! # Structure
//!
//! - **Slice primitives** — the actual arithmetic, written once over
//!   `&[u128]` limb slices (little-endian, `limbs[0]` least
//!   significant). Operating on slices sidesteps the const-generic
//!   return-type problem a widening multiply would otherwise hit.
//! - **`decl_hint!`** — a macro that emits a concrete two's-complement
//!   signed integer newtype of a fixed limb count, delegating its
//!   arithmetic to the slice primitives.
//! - The concrete types `HInt256` / `HInt512` / `HInt1024` /
//!   `HInt2048` / `HInt4096`, plus their unsigned-magnitude limb
//!   counts, generated by that macro.

// ─────────────────────────────────────────────────────────────────────
// Slice primitives — unsigned limb-array arithmetic.
//
// Every routine treats its slices as little-endian unsigned integers.
// Lengths are taken from the slices; callers size output buffers.
// ─────────────────────────────────────────────────────────────────────

/// Full 128×128 → 256 unsigned product, `(high, low)`.
#[inline]
const fn mul_128(a: u128, b: u128) -> (u128, u128) {
    let (a_hi, a_lo) = (a >> 64, a & u64::MAX as u128);
    let (b_hi, b_lo) = (b >> 64, b & u64::MAX as u128);
    let (mid, carry1) = (a_lo * b_hi).overflowing_add(a_hi * b_lo);
    let (low, carry2) = (a_lo * b_lo).overflowing_add(mid << 64);
    let high = a_hi * b_hi + (mid >> 64) + ((carry1 as u128) << 64) + carry2 as u128;
    (high, low)
}

/// `a == 0`.
#[inline]
pub(crate) fn limbs_is_zero(a: &[u128]) -> bool {
    a.iter().all(|&l| l == 0)
}

/// Three-way comparison of two equal-length-or-not limb slices.
#[inline]
pub(crate) fn limbs_cmp(a: &[u128], b: &[u128]) -> core::cmp::Ordering {
    use core::cmp::Ordering;
    let n = a.len().max(b.len());
    for i in (0..n).rev() {
        let av = a.get(i).copied().unwrap_or(0);
        let bv = b.get(i).copied().unwrap_or(0);
        match av.cmp(&bv) {
            Ordering::Equal => {}
            other => return other,
        }
    }
    Ordering::Equal
}

/// Bit length (`0` for zero, else `floor(log2)+1`).
#[inline]
pub(crate) fn limbs_bit_len(a: &[u128]) -> u32 {
    for i in (0..a.len()).rev() {
        if a[i] != 0 {
            return (i as u32) * 128 + (128 - a[i].leading_zeros());
        }
    }
    0
}

/// `a += b`, returning the carry out. `a.len() >= b.len()`.
#[inline]
pub(crate) fn limbs_add_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut carry = 0u128;
    for i in 0..a.len() {
        let bv = b.get(i).copied().unwrap_or(0);
        let (s1, c1) = a[i].overflowing_add(bv);
        let (s2, c2) = s1.overflowing_add(carry);
        a[i] = s2;
        carry = (c1 as u128) + (c2 as u128);
    }
    carry != 0
}

/// `a -= b`, returning the borrow out. `a.len() >= b.len()`.
#[inline]
pub(crate) fn limbs_sub_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut borrow = 0u128;
    for i in 0..a.len() {
        let bv = b.get(i).copied().unwrap_or(0);
        let (d1, b1) = a[i].overflowing_sub(bv);
        let (d2, b2) = d1.overflowing_sub(borrow);
        a[i] = d2;
        borrow = (b1 as u128) + (b2 as u128);
    }
    borrow != 0
}

/// `out = a << shift`. `out` is zeroed then filled; bits shifted past
/// `out`'s width are dropped.
pub(crate) fn limbs_shl(a: &[u128], shift: u32, out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    for i in 0..a.len() {
        let dst = i + limb_shift;
        if dst >= out.len() {
            break;
        }
        if bit == 0 {
            out[dst] |= a[i];
        } else {
            out[dst] |= a[i] << bit;
            if dst + 1 < out.len() {
                out[dst + 1] |= a[i] >> (128 - bit);
            }
        }
    }
}

/// `out = a >> shift`. `out` is zeroed then filled.
pub(crate) fn limbs_shr(a: &[u128], shift: u32, out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    for i in 0..a.len() {
        if i < limb_shift {
            continue;
        }
        let dst = i - limb_shift;
        if dst >= out.len() {
            continue;
        }
        if bit == 0 {
            out[dst] |= a[i];
        } else {
            out[dst] |= a[i] >> bit;
            if dst >= 1 {
                out[dst - 1] |= a[i] << (128 - bit);
            }
        }
    }
}

/// `out = a · b` (schoolbook). `out.len() >= a.len() + b.len()` and
/// `out` must be zeroed by the caller.
pub(crate) fn limbs_mul(a: &[u128], b: &[u128], out: &mut [u128]) {
    for i in 0..a.len() {
        if a[i] == 0 {
            continue;
        }
        let mut carry = 0u128;
        for j in 0..b.len() {
            let (hi, lo) = mul_128(a[i], b[j]);
            // out[i+j] += lo + carry; new carry = hi + overflow.
            let idx = i + j;
            let (s1, c1) = out[idx].overflowing_add(lo);
            let (s2, c2) = s1.overflowing_add(carry);
            out[idx] = s2;
            carry = hi + (c1 as u128) + (c2 as u128);
        }
        // Propagate the final carry.
        let mut idx = i + b.len();
        while carry != 0 && idx < out.len() {
            let (s, c) = out[idx].overflowing_add(carry);
            out[idx] = s;
            carry = c as u128;
            idx += 1;
        }
    }
}

/// Single-bit left shift in place; returns the bit shifted out of the
/// top.
#[inline]
fn limbs_shl1(a: &mut [u128]) -> u128 {
    let mut carry = 0u128;
    for limb in a.iter_mut() {
        let new_carry = *limb >> 127;
        *limb = (*limb << 1) | carry;
        carry = new_carry;
    }
    carry
}

/// `quot = num / den`, `rem = num % den`. Binary shift-subtract long
/// division. `quot.len() >= num.len()`, `rem.len() >= num.len()`;
/// both are zeroed by this routine. `den` must be non-zero.
pub(crate) fn limbs_divmod(num: &[u128], den: &[u128], quot: &mut [u128], rem: &mut [u128]) {
    for q in quot.iter_mut() {
        *q = 0;
    }
    for r in rem.iter_mut() {
        *r = 0;
    }
    let bits = limbs_bit_len(num);
    for i in (0..bits).rev() {
        // rem <<= 1; bring in bit i of num.
        limbs_shl1(rem);
        let bit = (num[(i / 128) as usize] >> (i % 128)) & 1;
        rem[0] |= bit;
        // quot <<= 1.
        limbs_shl1(quot);
        if limbs_cmp(rem, den) != core::cmp::Ordering::Less {
            limbs_sub_assign(rem, den);
            quot[0] |= 1;
        }
    }
}

/// `out = floor(sqrt(n))` via Newton's method. `out` is zeroed then
/// filled; `out.len()` must cover `ceil(bit_len(n)/2)` bits.
pub(crate) fn limbs_isqrt(n: &[u128], out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let bits = limbs_bit_len(n);
    if bits == 0 {
        return;
    }
    if bits <= 1 {
        out[0] = 1;
        return;
    }
    // Initial overestimate x0 = 2^(ceil(bits/2)).
    let work = n.len() + 1;
    let mut x = alloc_buf(work);
    let mut x_slice = &mut x[..];
    let e = bits.div_ceil(2);
    set_bit(x_slice, e);
    loop {
        // y = (x + n / x) / 2.
        let mut q = alloc_buf(work);
        let mut r = alloc_buf(work);
        limbs_divmod(n, x_slice, &mut q, &mut r);
        // q += x.
        limbs_add_assign(&mut q, x_slice);
        // q >>= 1.
        let mut y = alloc_buf(work);
        limbs_shr(&q, 1, &mut y);
        if limbs_cmp(&y, x_slice) != core::cmp::Ordering::Less {
            break;
        }
        x = y;
        x_slice = &mut x[..];
    }
    let copy_len = out.len().min(x_slice.len());
    out[..copy_len].copy_from_slice(&x_slice[..copy_len]);
}

/// A fixed-capacity limb buffer for the internal scratch of `isqrt`.
/// Capped at 64 limbs (8192 bits), comfortably above the widest work
/// integer in the crate (`HInt4096` → 32 limbs, isqrt scratch ≤ 33).
const SCRATCH_LIMBS: usize = 72;

/// Zeroed scratch buffer of `len` limbs (`len <= SCRATCH_LIMBS`).
#[inline]
fn alloc_buf(len: usize) -> [u128; SCRATCH_LIMBS] {
    debug_assert!(len <= SCRATCH_LIMBS, "wide-int scratch buffer overflow");
    let _ = len;
    [0u128; SCRATCH_LIMBS]
}

/// Sets bit `b` of a limb slice.
#[inline]
fn set_bit(a: &mut [u128], b: u32) {
    let limb = (b / 128) as usize;
    if limb < a.len() {
        a[limb] |= 1u128 << (b % 128);
    }
}

// ─────────────────────────────────────────────────────────────────────
// decl_hint! — concrete fixed-width signed/unsigned integer newtypes.
//
// Each invocation emits an unsigned `$U` ([u128; L]) and a
// two's-complement signed `$S` ([u128; L]), both delegating their
// arithmetic to the slice primitives above. The API surface mirrors
// the subset of `bnum`'s integer types the wide decimal macros depend
// on, so the existing `wide`-arm macros need only their `bnum::cast`
// call sites swapped for the conversion helpers emitted here.
// ─────────────────────────────────────────────────────────────────────

/// Emits the `$U` / `$S` integer pair for a fixed limb count.
///
/// - `$U` / `$S` — the unsigned and signed type names.
/// - `$L` — limb count (`[u128; $L]`); the bit width is `$L * 128`.
/// - `$D` — `2 * $L`, the buffer width for widening multiply/divide
///   intermediates.
macro_rules! decl_hint {
    ($U:ident, $S:ident, $L:tt, $D:tt) => {
        // ── Unsigned ──────────────────────────────────────────────────
        /// Hand-rolled fixed-width unsigned integer, little-endian limbs.
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug, Default)]
        pub(crate) struct $U(pub(crate) [u128; $L]);

        impl $U {
            pub(crate) const ZERO: $U = $U([0; $L]);
            pub(crate) const MAX: $U = $U([u128::MAX; $L]);
            pub(crate) const BITS: u32 = $L * 128;

            #[inline]
            pub(crate) fn is_zero(self) -> bool {
                $crate::hint::limbs_is_zero(&self.0)
            }
            #[inline]
            pub(crate) fn leading_zeros(self) -> u32 {
                Self::BITS - $crate::hint::limbs_bit_len(&self.0)
            }
            #[inline]
            pub(crate) fn count_ones(self) -> u32 {
                self.0.iter().map(|l| l.count_ones()).sum()
            }
            #[inline]
            pub(crate) fn is_power_of_two(self) -> bool {
                self.count_ones() == 1
            }
            pub(crate) fn next_power_of_two(self) -> $U {
                if self.is_zero() || self.is_power_of_two() {
                    if self.is_zero() {
                        let mut o = [0u128; $L];
                        o[0] = 1;
                        return $U(o);
                    }
                    return self;
                }
                let bits = $crate::hint::limbs_bit_len(&self.0);
                let mut out = [0u128; $L];
                if (bits as usize) < $L * 128 {
                    out[(bits / 128) as usize] = 1u128 << (bits % 128);
                }
                $U(out)
            }
            /// Reinterprets the bit pattern as the signed sibling.
            #[inline]
            pub(crate) fn cast_signed(self) -> $S {
                $S(self.0)
            }
            /// Builds `10^exp` (or any `radix^…`): parses a decimal
            /// string. Only base 10 is supported.
            pub(crate) fn from_str_radix(
                s: &str,
                radix: u32,
            ) -> ::core::result::Result<$U, ()> {
                if radix != 10 {
                    return ::core::result::Result::Err(());
                }
                let mut acc = [0u128; $L];
                let ten = [10u128; 1];
                for ch in s.bytes() {
                    let d = match ch {
                        b'0'..=b'9' => (ch - b'0') as u128,
                        _ => return ::core::result::Result::Err(()),
                    };
                    let mut scaled = [0u128; $D];
                    $crate::hint::limbs_mul(&acc, &ten, &mut scaled);
                    let mut next = [0u128; $L];
                    next.copy_from_slice(&scaled[..$L]);
                    $crate::hint::limbs_add_assign(&mut next, &[d]);
                    acc = next;
                }
                ::core::result::Result::Ok($U(acc))
            }
            pub(crate) fn pow(self, mut exp: u32) -> $U {
                let mut acc = {
                    let mut o = [0u128; $L];
                    o[0] = 1;
                    $U(o)
                };
                let mut base = self;
                while exp > 0 {
                    if exp & 1 == 1 {
                        acc = acc.wrapping_mul(base);
                    }
                    exp >>= 1;
                    if exp > 0 {
                        base = base.wrapping_mul(base);
                    }
                }
                acc
            }
            #[inline]
            pub(crate) fn wrapping_mul(self, rhs: $U) -> $U {
                let mut prod = [0u128; $D];
                $crate::hint::limbs_mul(&self.0, &rhs.0, &mut prod);
                let mut out = [0u128; $L];
                out.copy_from_slice(&prod[..$L]);
                $U(out)
            }
            #[inline]
            pub(crate) fn isqrt(self) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_isqrt(&self.0, &mut out);
                $U(out)
            }
        }

        impl ::core::cmp::Ord for $U {
            #[inline]
            fn cmp(&self, other: &$U) -> ::core::cmp::Ordering {
                $crate::hint::limbs_cmp(&self.0, &other.0)
            }
        }
        impl ::core::cmp::PartialOrd for $U {
            #[inline]
            fn partial_cmp(&self, other: &$U) -> ::core::option::Option<::core::cmp::Ordering> {
                ::core::option::Option::Some(self.cmp(other))
            }
        }
        impl ::core::ops::Shr<u32> for $U {
            type Output = $U;
            #[inline]
            fn shr(self, n: u32) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shr(&self.0, n, &mut out);
                $U(out)
            }
        }
        impl ::core::ops::Shl<u32> for $U {
            type Output = $U;
            #[inline]
            fn shl(self, n: u32) -> $U {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shl(&self.0, n, &mut out);
                $U(out)
            }
        }
        impl ::core::ops::Sub for $U {
            type Output = $U;
            #[inline]
            fn sub(mut self, rhs: $U) -> $U {
                $crate::hint::limbs_sub_assign(&mut self.0, &rhs.0);
                self
            }
        }
        impl ::core::ops::Rem for $U {
            type Output = $U;
            #[inline]
            fn rem(self, rhs: $U) -> $U {
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(&self.0, &rhs.0, &mut q, &mut r);
                $U(r)
            }
        }

        // ── Signed ────────────────────────────────────────────────────
        /// Hand-rolled fixed-width two's-complement signed integer.
        #[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
        pub(crate) struct $S(pub(crate) [u128; $L]);

        impl $S {
            pub(crate) const ZERO: $S = $S([0; $L]);
            pub(crate) const ONE: $S = {
                let mut a = [0u128; $L];
                a[0] = 1;
                $S(a)
            };
            pub(crate) const BITS: u32 = $L * 128;
            pub(crate) const MAX: $S = {
                let mut a = [u128::MAX; $L];
                a[$L - 1] = i128::MAX as u128;
                $S(a)
            };
            pub(crate) const MIN: $S = {
                let mut a = [0u128; $L];
                a[$L - 1] = 1u128 << 127;
                $S(a)
            };

            #[inline]
            pub(crate) fn is_negative(self) -> bool {
                self.0[$L - 1] >> 127 == 1
            }
            #[inline]
            pub(crate) fn is_zero(self) -> bool {
                $crate::hint::limbs_is_zero(&self.0)
            }
            #[inline]
            pub(crate) fn is_positive(self) -> bool {
                !self.is_negative() && !self.is_zero()
            }
            /// Two's-complement negation (wrapping; `MIN.negate() == MIN`).
            #[inline]
            pub(crate) fn negate(self) -> $S {
                let mut out = [0u128; $L];
                for i in 0..$L {
                    out[i] = !self.0[i];
                }
                $crate::hint::limbs_add_assign(&mut out, &[1]);
                $S(out)
            }
            /// `|self|` as the unsigned sibling. `MIN` maps to `2^(BITS-1)`.
            #[inline]
            pub(crate) fn unsigned_abs(self) -> $U {
                if self.is_negative() {
                    $U(self.negate().0)
                } else {
                    $U(self.0)
                }
            }
            /// Reinterprets the bit pattern as the unsigned sibling.
            #[inline]
            pub(crate) fn cast_unsigned(self) -> $U {
                $U(self.0)
            }
            /// Builds a signed value from a non-negative magnitude limb
            /// slice and a sign, truncating the magnitude into `$L`
            /// limbs.
            pub(crate) fn from_mag_limbs(mag: &[u128], negative: bool) -> $S {
                let mut out = [0u128; $L];
                let n = mag.len().min($L);
                out[..n].copy_from_slice(&mag[..n]);
                let v = $S(out);
                if negative && !v.is_zero() {
                    v.negate()
                } else {
                    v
                }
            }
            #[inline]
            pub(crate) fn leading_zeros(self) -> u32 {
                Self::BITS - $crate::hint::limbs_bit_len(&self.unsigned_abs().0)
            }
            #[inline]
            pub(crate) fn count_ones(self) -> u32 {
                self.0.iter().map(|l| l.count_ones()).sum()
            }
            pub(crate) fn from_str_radix(
                s: &str,
                radix: u32,
            ) -> ::core::result::Result<$S, ()> {
                let (neg, digits) = match s.strip_prefix('-') {
                    ::core::option::Option::Some(rest) => (true, rest),
                    ::core::option::Option::None => (false, s),
                };
                let mag = $U::from_str_radix(digits, radix)?;
                ::core::result::Result::Ok($S::from_mag_limbs(&mag.0, neg))
            }
            pub(crate) fn pow(self, mut exp: u32) -> $S {
                let mut acc = $S::ONE;
                let mut base = self;
                while exp > 0 {
                    if exp & 1 == 1 {
                        acc = acc.wrapping_mul(base);
                    }
                    exp >>= 1;
                    if exp > 0 {
                        base = base.wrapping_mul(base);
                    }
                }
                acc
            }
            #[inline]
            pub(crate) fn wrapping_add(self, rhs: $S) -> $S {
                let mut out = self.0;
                $crate::hint::limbs_add_assign(&mut out, &rhs.0);
                $S(out)
            }
            #[inline]
            pub(crate) fn wrapping_sub(self, rhs: $S) -> $S {
                self.wrapping_add(rhs.negate())
            }
            #[inline]
            pub(crate) fn wrapping_neg(self) -> $S {
                self.negate()
            }
            pub(crate) fn wrapping_mul(self, rhs: $S) -> $S {
                let negative = self.is_negative() ^ rhs.is_negative();
                let prod = self.unsigned_abs().wrapping_mul(rhs.unsigned_abs());
                $S::from_mag_limbs(&prod.0, negative)
            }
            /// `self / rhs` truncating toward zero. `rhs` must be nonzero.
            pub(crate) fn wrapping_div(self, rhs: $S) -> $S {
                let negative = self.is_negative() ^ rhs.is_negative();
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut q,
                    &mut r,
                );
                $S::from_mag_limbs(&q, negative)
            }
            /// `self % rhs`, result carries the sign of `self`.
            pub(crate) fn wrapping_rem(self, rhs: $S) -> $S {
                let mut q = [0u128; $L];
                let mut r = [0u128; $L];
                $crate::hint::limbs_divmod(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut q,
                    &mut r,
                );
                $S::from_mag_limbs(&r, self.is_negative())
            }
            #[inline]
            fn add_overflows(self, rhs: $S, result: $S) -> bool {
                // Overflow iff operands share a sign and the result's
                // sign differs from it.
                self.is_negative() == rhs.is_negative()
                    && result.is_negative() != self.is_negative()
            }
            #[inline]
            pub(crate) fn checked_add(self, rhs: $S) -> ::core::option::Option<$S> {
                let r = self.wrapping_add(rhs);
                if self.add_overflows(rhs, r) {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(r)
                }
            }
            #[inline]
            pub(crate) fn checked_sub(self, rhs: $S) -> ::core::option::Option<$S> {
                let r = self.wrapping_sub(rhs);
                if self.is_negative() != rhs.is_negative()
                    && r.is_negative() != self.is_negative()
                {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(r)
                }
            }
            #[inline]
            pub(crate) fn checked_neg(self) -> ::core::option::Option<$S> {
                if self == $S::MIN {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.negate())
                }
            }
            pub(crate) fn checked_mul(self, rhs: $S) -> ::core::option::Option<$S> {
                let negative = self.is_negative() ^ rhs.is_negative();
                let mut prod = [0u128; $D];
                $crate::hint::limbs_mul(
                    &self.unsigned_abs().0,
                    &rhs.unsigned_abs().0,
                    &mut prod,
                );
                // Overflow if any limb above the low `$L` is set, or the
                // magnitude exceeds the signed range for its sign.
                if !$crate::hint::limbs_is_zero(&prod[$L..]) {
                    return ::core::option::Option::None;
                }
                let r = $S::from_mag_limbs(&prod[..$L], negative);
                // `from_mag_limbs` of an out-of-range magnitude flips the
                // sign; detect that.
                if r.is_zero() || r.is_negative() == negative {
                    ::core::option::Option::Some(r)
                } else {
                    ::core::option::Option::None
                }
            }
            #[inline]
            pub(crate) fn checked_div(self, rhs: $S) -> ::core::option::Option<$S> {
                if rhs.is_zero() {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.wrapping_div(rhs))
                }
            }
            #[inline]
            pub(crate) fn checked_rem(self, rhs: $S) -> ::core::option::Option<$S> {
                if rhs.is_zero() {
                    ::core::option::Option::None
                } else {
                    ::core::option::Option::Some(self.wrapping_rem(rhs))
                }
            }
            #[inline]
            pub(crate) fn isqrt(self) -> $S {
                $S(self.unsigned_abs().isqrt().0)
            }
            // ── Conversions (replace `bnum::cast::As`) ────────────────
            /// Builds from a signed 128-bit value.
            #[inline]
            pub(crate) fn from_i128(v: i128) -> $S {
                $S::from_mag_limbs(&[v.unsigned_abs()], v < 0)
            }
            /// Builds from an unsigned 128-bit value.
            #[inline]
            pub(crate) fn from_u128(v: u128) -> $S {
                $S::from_mag_limbs(&[v], false)
            }
            /// Truncating cast to `i128` (low 128 bits, sign-applied).
            #[inline]
            pub(crate) fn as_i128(self) -> i128 {
                let mag = self.unsigned_abs().0[0];
                if self.is_negative() {
                    (mag as i128).wrapping_neg()
                } else {
                    mag as i128
                }
            }
            /// Widening / narrowing reinterpretation to another `decl_hint!`
            /// signed type via magnitude + sign.
            #[inline]
            pub(crate) fn resize<T: $crate::hint::HIntFromMag>(self) -> T {
                T::from_mag_and_sign(&self.unsigned_abs().0, self.is_negative())
            }
            /// Approximate `f64` value.
            pub(crate) fn as_f64(self) -> f64 {
                let mag = self.unsigned_abs().0;
                let mut acc = 0.0f64;
                for i in (0..$L).rev() {
                    acc = acc * 340_282_366_920_938_463_463_374_607_431_768_211_456.0
                        + mag[i] as f64;
                }
                if self.is_negative() {
                    -acc
                } else {
                    acc
                }
            }
            /// Builds from an `f64`, truncating toward zero. Saturates
            /// to `MIN` / `MAX` on out-of-range / non-finite input.
            pub(crate) fn from_f64(v: f64) -> $S {
                if !v.is_finite() {
                    return $S::ZERO;
                }
                let negative = v < 0.0;
                let mut m = v.abs().trunc();
                let radix = 340_282_366_920_938_463_463_374_607_431_768_211_456.0;
                let mut limbs = [0u128; $L];
                let mut i = 0;
                while m >= 1.0 && i < $L {
                    let limb = (m % radix) as u128;
                    limbs[i] = limb;
                    m = (m / radix).trunc();
                    i += 1;
                }
                if m >= 1.0 {
                    // Overflowed the width — saturate.
                    return if negative { $S::MIN } else { $S::MAX };
                }
                $S::from_mag_limbs(&limbs, negative)
            }
        }

        impl $crate::hint::HIntFromMag for $S {
            #[inline]
            fn from_mag_and_sign(mag: &[u128], negative: bool) -> $S {
                $S::from_mag_limbs(mag, negative)
            }
        }

        impl ::core::cmp::Ord for $S {
            #[inline]
            fn cmp(&self, other: &$S) -> ::core::cmp::Ordering {
                match (self.is_negative(), other.is_negative()) {
                    (true, false) => ::core::cmp::Ordering::Less,
                    (false, true) => ::core::cmp::Ordering::Greater,
                    _ => $crate::hint::limbs_cmp(&self.0, &other.0),
                }
            }
        }
        impl ::core::cmp::PartialOrd for $S {
            #[inline]
            fn partial_cmp(&self, other: &$S) -> ::core::option::Option<::core::cmp::Ordering> {
                ::core::option::Option::Some(self.cmp(other))
            }
        }
        impl ::core::ops::Add for $S {
            type Output = $S;
            #[inline]
            fn add(self, rhs: $S) -> $S {
                self.checked_add(rhs).expect(concat!(stringify!($S), ": add overflow"))
            }
        }
        impl ::core::ops::Sub for $S {
            type Output = $S;
            #[inline]
            fn sub(self, rhs: $S) -> $S {
                self.checked_sub(rhs).expect(concat!(stringify!($S), ": sub overflow"))
            }
        }
        impl ::core::ops::Mul for $S {
            type Output = $S;
            #[inline]
            fn mul(self, rhs: $S) -> $S {
                self.checked_mul(rhs).expect(concat!(stringify!($S), ": mul overflow"))
            }
        }
        impl ::core::ops::Div for $S {
            type Output = $S;
            #[inline]
            fn div(self, rhs: $S) -> $S {
                self.wrapping_div(rhs)
            }
        }
        impl ::core::ops::Rem for $S {
            type Output = $S;
            #[inline]
            fn rem(self, rhs: $S) -> $S {
                self.wrapping_rem(rhs)
            }
        }
        impl ::core::ops::Neg for $S {
            type Output = $S;
            #[inline]
            fn neg(self) -> $S {
                self.checked_neg().expect(concat!(stringify!($S), ": neg overflow"))
            }
        }
        impl ::core::ops::Shl<u32> for $S {
            type Output = $S;
            #[inline]
            fn shl(self, n: u32) -> $S {
                let mut out = [0u128; $L];
                $crate::hint::limbs_shl(&self.0, n, &mut out);
                $S(out)
            }
        }
        impl ::core::ops::Shr<u32> for $S {
            type Output = $S;
            /// Arithmetic right shift (sign-preserving).
            #[inline]
            fn shr(self, n: u32) -> $S {
                if self.is_negative() {
                    // −((−self − 1) >> n) − 1  keeps the floor semantics.
                    let mag = self.unsigned_abs();
                    let shifted = mag >> n;
                    $S::from_mag_limbs(&shifted.0, true)
                } else {
                    let mut out = [0u128; $L];
                    $crate::hint::limbs_shr(&self.0, n, &mut out);
                    $S(out)
                }
            }
        }
    };
}

pub(crate) use decl_hint;

/// Trait that lets a `decl_hint!` signed type be rebuilt from another
/// width's magnitude + sign — the basis of `resize` (widen / narrow).
pub(crate) trait HIntFromMag {
    fn from_mag_and_sign(mag: &[u128], negative: bool) -> Self;
}

// The concrete wide integer types. `HInt256` (the existing
// hand-rolled D256H storage) is generalised to this family;
// `HInt2048` / `HInt4096` exist for the strict-transcendental work
// integers.
decl_hint!(WInt256, SInt256, 2, 4);
decl_hint!(WInt512, SInt512, 4, 8);
decl_hint!(WInt1024, SInt1024, 8, 16);
decl_hint!(WInt2048, SInt2048, 16, 32);
decl_hint!(WInt4096, SInt4096, 32, 64);

#[cfg(test)]
mod hint_tests {
    use super::*;

    #[test]
    fn signed_add_sub_neg() {
        let a = SInt256::from_i128(5);
        let b = SInt256::from_i128(3);
        assert_eq!(a.wrapping_add(b), SInt256::from_i128(8));
        assert_eq!(a.wrapping_sub(b), SInt256::from_i128(2));
        assert_eq!(b.wrapping_sub(a), SInt256::from_i128(-2));
        assert_eq!(a.negate(), SInt256::from_i128(-5));
        assert_eq!(SInt256::ZERO.negate(), SInt256::ZERO);
    }

    #[test]
    fn signed_mul_div_rem() {
        let six = SInt512::from_i128(6);
        let two = SInt512::from_i128(2);
        let three = SInt512::from_i128(3);
        assert_eq!(six.wrapping_mul(three), SInt512::from_i128(18));
        assert_eq!(six.wrapping_div(two), three);
        assert_eq!(SInt512::from_i128(7).wrapping_rem(three), SInt512::from_i128(1));
        assert_eq!(SInt512::from_i128(-7).wrapping_rem(three), SInt512::from_i128(-1));
        assert_eq!(six.negate().wrapping_mul(three), SInt512::from_i128(-18));
    }

    #[test]
    fn checked_overflow() {
        assert_eq!(SInt256::MAX.checked_add(SInt256::ONE), None);
        assert_eq!(SInt256::MIN.checked_sub(SInt256::ONE), None);
        assert_eq!(SInt256::MIN.checked_neg(), None);
        assert_eq!(SInt256::from_i128(2).checked_add(SInt256::from_i128(3)),
                   Some(SInt256::from_i128(5)));
    }

    #[test]
    fn from_str_and_pow() {
        let ten = SInt1024::from_str_radix("10", 10).unwrap();
        assert_eq!(ten, SInt1024::from_i128(10));
        assert_eq!(ten.pow(3), SInt1024::from_i128(1000));
        // 10^40 overflows i128 — check via round-trip string.
        let big = SInt1024::from_str_radix("10", 10).unwrap().pow(40);
        let from_str = SInt1024::from_str_radix(
            "10000000000000000000000000000000000000000", 10).unwrap();
        assert_eq!(big, from_str);
    }

    #[test]
    fn ordering_and_resize() {
        assert!(SInt256::from_i128(-1) < SInt256::ZERO);
        assert!(SInt256::MIN < SInt256::MAX);
        // resize widen then narrow round-trips a small value.
        let v = SInt256::from_i128(-123_456_789);
        let wide: SInt1024 = v.resize();
        let back: SInt256 = wide.resize();
        assert_eq!(back, v);
        assert_eq!(wide, SInt1024::from_i128(-123_456_789));
    }

    #[test]
    fn isqrt_and_f64() {
        assert_eq!(SInt512::from_i128(144).isqrt(), SInt512::from_i128(12));
        assert_eq!(SInt256::from_i128(1_000_000).as_f64(), 1_000_000.0);
        assert_eq!(SInt256::from_f64(-2_500.0), SInt256::from_i128(-2500));
    }
}

#[cfg(test)]
mod slice_tests {
    use super::*;

    #[test]
    fn mul_and_divmod_round_trip() {
        let a = [123u128, 7, 0, 0];
        let b = [456u128, 0, 0, 0];
        let mut prod = [0u128; 8];
        limbs_mul(&a, &b, &mut prod);
        let mut q = [0u128; 8];
        let mut r = [0u128; 8];
        limbs_divmod(&prod, &b, &mut q, &mut r);
        assert_eq!(&q[..4], &a, "quotient");
        assert!(limbs_is_zero(&r), "remainder");
    }

    #[test]
    fn shifts() {
        let a = [1u128, 0];
        let mut out = [0u128; 2];
        limbs_shl(&a, 130, &mut out);
        assert_eq!(out, [0, 4]);
        let mut back = [0u128; 2];
        limbs_shr(&out, 130, &mut back);
        assert_eq!(back, [1, 0]);
    }

    #[test]
    fn isqrt_basic() {
        // sqrt(2^256) = 2^128.
        let n = [0u128, 0, 1, 0];
        let mut out = [0u128; 4];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [0, 1, 0, 0]);
        // sqrt(144) = 12.
        let n = [144u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [12, 0]);
        // sqrt(2) = 1 (floor).
        let n = [2u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [1, 0]);
    }

    #[test]
    fn add_sub_carry() {
        let mut a = [u128::MAX, 0];
        let carry = limbs_add_assign(&mut a, &[1, 0]);
        assert!(!carry);
        assert_eq!(a, [0, 1]);
        let borrow = limbs_sub_assign(&mut a, &[1, 0]);
        assert!(!borrow);
        assert_eq!(a, [u128::MAX, 0]);
    }
}
