//! Hand-rolled generic wide-integer arithmetic.
//!
//! This module is the in-tree big-integer backend for the wide decimal
//! tiers (D256 / D512 / D1024) and for the guard-digit work integers
//! their strict transcendentals run on. It replaces `bnum` in normal
//! builds — `bnum` is kept only as a benchmark baseline (see
//! `src/benchmark/`).
//!
//! # Structure
//!
//! - **Slice primitives** — the actual arithmetic, written once over
//!   `&[u128]` limb slices (little-endian, `limbs[0]` least
//!   significant). Operating on slices sidesteps the const-generic
//!   return-type problem a widening multiply would otherwise hit.
//! - **`decl_hint!`** — a macro that emits a concrete two's-complement
//!   signed integer newtype of a fixed limb count, delegating its
//!   arithmetic to the slice primitives.
//! - The concrete types `HInt256` / `HInt512` / `HInt1024` /
//!   `HInt2048` / `HInt4096`, plus their unsigned-magnitude limb
//!   counts, generated by that macro.

// ─────────────────────────────────────────────────────────────────────
// Slice primitives — unsigned limb-array arithmetic.
//
// Every routine treats its slices as little-endian unsigned integers.
// Lengths are taken from the slices; callers size output buffers.
// ─────────────────────────────────────────────────────────────────────

/// Full 128×128 → 256 unsigned product, `(high, low)`.
#[inline]
const fn mul_128(a: u128, b: u128) -> (u128, u128) {
    let (a_hi, a_lo) = (a >> 64, a & u64::MAX as u128);
    let (b_hi, b_lo) = (b >> 64, b & u64::MAX as u128);
    let (mid, carry1) = (a_lo * b_hi).overflowing_add(a_hi * b_lo);
    let (low, carry2) = (a_lo * b_lo).overflowing_add(mid << 64);
    let high = a_hi * b_hi + (mid >> 64) + ((carry1 as u128) << 64) + carry2 as u128;
    (high, low)
}

/// `a == 0`.
#[inline]
pub(crate) fn limbs_is_zero(a: &[u128]) -> bool {
    a.iter().all(|&l| l == 0)
}

/// Three-way comparison of two equal-length-or-not limb slices.
#[inline]
pub(crate) fn limbs_cmp(a: &[u128], b: &[u128]) -> core::cmp::Ordering {
    use core::cmp::Ordering;
    let n = a.len().max(b.len());
    for i in (0..n).rev() {
        let av = a.get(i).copied().unwrap_or(0);
        let bv = b.get(i).copied().unwrap_or(0);
        match av.cmp(&bv) {
            Ordering::Equal => {}
            other => return other,
        }
    }
    Ordering::Equal
}

/// Bit length (`0` for zero, else `floor(log2)+1`).
#[inline]
pub(crate) fn limbs_bit_len(a: &[u128]) -> u32 {
    for i in (0..a.len()).rev() {
        if a[i] != 0 {
            return (i as u32) * 128 + (128 - a[i].leading_zeros());
        }
    }
    0
}

/// `a += b`, returning the carry out. `a.len() >= b.len()`.
#[inline]
pub(crate) fn limbs_add_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut carry = 0u128;
    for i in 0..a.len() {
        let bv = b.get(i).copied().unwrap_or(0);
        let (s1, c1) = a[i].overflowing_add(bv);
        let (s2, c2) = s1.overflowing_add(carry);
        a[i] = s2;
        carry = (c1 as u128) + (c2 as u128);
    }
    carry != 0
}

/// `a -= b`, returning the borrow out. `a.len() >= b.len()`.
#[inline]
pub(crate) fn limbs_sub_assign(a: &mut [u128], b: &[u128]) -> bool {
    let mut borrow = 0u128;
    for i in 0..a.len() {
        let bv = b.get(i).copied().unwrap_or(0);
        let (d1, b1) = a[i].overflowing_sub(bv);
        let (d2, b2) = d1.overflowing_sub(borrow);
        a[i] = d2;
        borrow = (b1 as u128) + (b2 as u128);
    }
    borrow != 0
}

/// `out = a << shift`. `out` is zeroed then filled; bits shifted past
/// `out`'s width are dropped.
pub(crate) fn limbs_shl(a: &[u128], shift: u32, out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    for i in 0..a.len() {
        let dst = i + limb_shift;
        if dst >= out.len() {
            break;
        }
        if bit == 0 {
            out[dst] |= a[i];
        } else {
            out[dst] |= a[i] << bit;
            if dst + 1 < out.len() {
                out[dst + 1] |= a[i] >> (128 - bit);
            }
        }
    }
}

/// `out = a >> shift`. `out` is zeroed then filled.
pub(crate) fn limbs_shr(a: &[u128], shift: u32, out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let limb_shift = (shift / 128) as usize;
    let bit = shift % 128;
    for i in 0..a.len() {
        if i < limb_shift {
            continue;
        }
        let dst = i - limb_shift;
        if dst >= out.len() {
            continue;
        }
        if bit == 0 {
            out[dst] |= a[i];
        } else {
            out[dst] |= a[i] >> bit;
            if dst >= 1 {
                out[dst - 1] |= a[i] << (128 - bit);
            }
        }
    }
}

/// `out = a · b` (schoolbook). `out.len() >= a.len() + b.len()` and
/// `out` must be zeroed by the caller.
pub(crate) fn limbs_mul(a: &[u128], b: &[u128], out: &mut [u128]) {
    for i in 0..a.len() {
        if a[i] == 0 {
            continue;
        }
        let mut carry = 0u128;
        for j in 0..b.len() {
            let (hi, lo) = mul_128(a[i], b[j]);
            // out[i+j] += lo + carry; new carry = hi + overflow.
            let idx = i + j;
            let (s1, c1) = out[idx].overflowing_add(lo);
            let (s2, c2) = s1.overflowing_add(carry);
            out[idx] = s2;
            carry = hi + (c1 as u128) + (c2 as u128);
        }
        // Propagate the final carry.
        let mut idx = i + b.len();
        while carry != 0 && idx < out.len() {
            let (s, c) = out[idx].overflowing_add(carry);
            out[idx] = s;
            carry = c as u128;
            idx += 1;
        }
    }
}

/// Single-bit left shift in place; returns the bit shifted out of the
/// top.
#[inline]
fn limbs_shl1(a: &mut [u128]) -> u128 {
    let mut carry = 0u128;
    for limb in a.iter_mut() {
        let new_carry = *limb >> 127;
        *limb = (*limb << 1) | carry;
        carry = new_carry;
    }
    carry
}

/// `quot = num / den`, `rem = num % den`. Binary shift-subtract long
/// division. `quot.len() >= num.len()`, `rem.len() >= num.len()`;
/// both are zeroed by this routine. `den` must be non-zero.
pub(crate) fn limbs_divmod(num: &[u128], den: &[u128], quot: &mut [u128], rem: &mut [u128]) {
    for q in quot.iter_mut() {
        *q = 0;
    }
    for r in rem.iter_mut() {
        *r = 0;
    }
    let bits = limbs_bit_len(num);
    for i in (0..bits).rev() {
        // rem <<= 1; bring in bit i of num.
        limbs_shl1(rem);
        let bit = (num[(i / 128) as usize] >> (i % 128)) & 1;
        rem[0] |= bit;
        // quot <<= 1.
        limbs_shl1(quot);
        if limbs_cmp(rem, den) != core::cmp::Ordering::Less {
            limbs_sub_assign(rem, den);
            quot[0] |= 1;
        }
    }
}

/// `out = floor(sqrt(n))` via Newton's method. `out` is zeroed then
/// filled; `out.len()` must cover `ceil(bit_len(n)/2)` bits.
pub(crate) fn limbs_isqrt(n: &[u128], out: &mut [u128]) {
    for o in out.iter_mut() {
        *o = 0;
    }
    let bits = limbs_bit_len(n);
    if bits == 0 {
        return;
    }
    if bits <= 1 {
        out[0] = 1;
        return;
    }
    // Initial overestimate x0 = 2^(ceil(bits/2)).
    let work = n.len() + 1;
    let mut x = alloc_buf(work);
    let mut x_slice = &mut x[..];
    let e = bits.div_ceil(2);
    set_bit(x_slice, e);
    loop {
        // y = (x + n / x) / 2.
        let mut q = alloc_buf(work);
        let mut r = alloc_buf(work);
        limbs_divmod(n, x_slice, &mut q, &mut r);
        // q += x.
        limbs_add_assign(&mut q, x_slice);
        // q >>= 1.
        let mut y = alloc_buf(work);
        limbs_shr(&q, 1, &mut y);
        if limbs_cmp(&y, x_slice) != core::cmp::Ordering::Less {
            break;
        }
        x = y;
        x_slice = &mut x[..];
    }
    let copy_len = out.len().min(x_slice.len());
    out[..copy_len].copy_from_slice(&x_slice[..copy_len]);
}

/// A fixed-capacity limb buffer for the internal scratch of `isqrt`.
/// Capped at 64 limbs (8192 bits), comfortably above the widest work
/// integer in the crate (`HInt4096` → 32 limbs, isqrt scratch ≤ 33).
const SCRATCH_LIMBS: usize = 72;

/// Zeroed scratch buffer of `len` limbs (`len <= SCRATCH_LIMBS`).
#[inline]
fn alloc_buf(len: usize) -> [u128; SCRATCH_LIMBS] {
    debug_assert!(len <= SCRATCH_LIMBS, "wide-int scratch buffer overflow");
    let _ = len;
    [0u128; SCRATCH_LIMBS]
}

/// Sets bit `b` of a limb slice.
#[inline]
fn set_bit(a: &mut [u128], b: u32) {
    let limb = (b / 128) as usize;
    if limb < a.len() {
        a[limb] |= 1u128 << (b % 128);
    }
}

#[cfg(test)]
mod slice_tests {
    use super::*;

    #[test]
    fn mul_and_divmod_round_trip() {
        let a = [123u128, 7, 0, 0];
        let b = [456u128, 0, 0, 0];
        let mut prod = [0u128; 8];
        limbs_mul(&a, &b, &mut prod);
        let mut q = [0u128; 8];
        let mut r = [0u128; 8];
        limbs_divmod(&prod, &b, &mut q, &mut r);
        assert_eq!(&q[..4], &a, "quotient");
        assert!(limbs_is_zero(&r), "remainder");
    }

    #[test]
    fn shifts() {
        let a = [1u128, 0];
        let mut out = [0u128; 2];
        limbs_shl(&a, 130, &mut out);
        assert_eq!(out, [0, 4]);
        let mut back = [0u128; 2];
        limbs_shr(&out, 130, &mut back);
        assert_eq!(back, [1, 0]);
    }

    #[test]
    fn isqrt_basic() {
        // sqrt(2^256) = 2^128.
        let n = [0u128, 0, 1, 0];
        let mut out = [0u128; 4];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [0, 1, 0, 0]);
        // sqrt(144) = 12.
        let n = [144u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [12, 0]);
        // sqrt(2) = 1 (floor).
        let n = [2u128, 0];
        let mut out = [0u128; 2];
        limbs_isqrt(&n, &mut out);
        assert_eq!(out, [1, 0]);
    }

    #[test]
    fn add_sub_carry() {
        let mut a = [u128::MAX, 0];
        let carry = limbs_add_assign(&mut a, &[1, 0]);
        assert!(!carry);
        assert_eq!(a, [0, 1]);
        let borrow = limbs_sub_assign(&mut a, &[1, 0]);
        assert!(!borrow);
        assert_eq!(a, [u128::MAX, 0]);
    }
}
